### ISSUE TITLE
Support gzip

### ISSUE THREAD

**Issue by rakyll** [google/google-api-nodejs-client#10]

**Comment by wearhere** [comment]
If I read `request`'s [documentation](https://github.com/request/request) correctly, we wouldn't need to manually decompress the data except for perhaps the response:

> To accept gzip-compressed responses, set the gzip option to true. Note that the body data passed through request is automatically decompressed while the response object is unmodified and will contain compressed data if the server sent a compressed response.

**Comment by Josecamero** [comment]
How is the gzip content encoding header set?
