### ISSUE TITLE
TypeError: Cannot read property 'getApplicationDefault' of undefined

### ISSUE THREAD

**Issue by noamackerman** [google/google-api-nodejs-client#1004]
Hi,
When executing the following code in a cloud function:

```js
const google = require('googleapis');

exports.goWithTheDataFlow = function(event, callback) {
  google.auth.getApplicationDefault(function(err, authClient, projectId) {
  if (err) {
    throw err;
  }
```

I get the following exception: 
```
TypeError: Cannot read property 'getApplicationDefault' of undefined
```

This function is invoked when a new item is added to a GCS bucket. I deployed it using the following command: `gcloud beta functions deploy goWithTheDataFlow  --stage-bucket [BUCKET-NAME]--trigger-resource [TRIGGER-BUCKET] --trigger-event google.storage.object.finalize`

Am I missing something?

Thank you for your help!
Noam

**Comment by JustinBeckwith** [comment]
Greetings!  You probably just need to change up your import:
const {google} = require('googleapis');

For more, checkout the usage guide!
https://github.com/google/google-api-nodejs-client#usage

**Comment by JustinBeckwith** [comment]
Let us know if this is still an issue :)
