### ISSUE TITLE
gmail quickstart guide only works with version 25 and not 26 of this package

### ISSUE THREAD

**Issue by johngrabner** [google/google-api-nodejs-client#1006]
https://developers.google.com/gmail/api/quickstart/nodejs

should specify a version in step 2. This way if other breaking changes are introduced, new users will not be lost.

step 3 should be changed from 
var google = require('googleapis');

to 

var {google} = require('googleapis');

**Comment by JustinBeckwith** [comment]
Similar to google-auth-library, we need to figure out the best way to store, test, and update samples for these repositories.

**Comment by johngrabner** [comment]
If version is specified in npm install
In the example
Then student gets a working version of example rather than one that does not if example ever falls behind.


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by meer1992** [comment]
I guess the quickstart guide needs to be updated. I have tried to use the google drive API to upload a simple text or image but it gives me Invalid multipart request. Some people ends up downgrading to v24: see https://stackoverflow.com/questions/48492592/google-drive-sdk-with-node-js-googleapis-package-throws-error-invalid-multipart#comment83978644_48492592 , and https://stackoverflow.com/questions/48492592/google-drive-sdk-with-node-js-googleapis-package-throws-error-invalid-multipart#comment83978644_48492592

**Comment by johngrabner** [comment]
I figured out how to fix the quick start to work with the current version of the API.


But the solution does not answer the fundamental question of:

- how does one map the API parameters in the api playground to parameters in the actual api call?  Magically "Request body {'raw':'xxx'} " becomes raw = new Buffer(str).toString("base64").replace(/\+/g, '-').replace(/\//g, '_');"resource: { raw: raw}". Since the quick start is so sparse in its coverage of the API, it would be nice to know what the rules are so when other aspects of the API are needed, the user has something to build on.


These are detailed description but they are abstracted by the api

https://developers.google.com/gmail/api/v1/reference/

https://developers.google.com/gmail/api/v1/reference/users/messages/send


The api does not say what the mapping formula is:

https://www.npmjs.com/package/googleapis




-  why is "replace(/\+/g, '-').replace(/\//g, '_');" required?


Also, I would suggest the quick start be augmented to sending emails.  This is more common for a task than reading labels.


I posted my partial solutions here


https://stackoverflow.com/questions/48914332

https://stackoverflow.com/questions/48579566


Maybe obvious to some, but not me or the G Suite help line:  gmail api applies to custom email domains purchased from G suite.  I gave up on them after 30 minutes of G suite help not finding instructions on how to programmatically sending emails using these custom email accounts.




Regards,

John









________________________________

**Comment by JustinBeckwith** [comment]
Greetings folks!
We have a few updated samples of using gmail to get you started here: 
https://github.com/google/google-api-nodejs-client/tree/master/samples/gmail

I've filed an issue here you can track for the developers.google.com docs update:
https://issuetracker.google.com/issues/74344263

Thanks for the heads up!
