### ISSUE TITLE
generate-docs not working

### ISSUE THREAD

**Issue by samaystops4no1** [google/google-api-nodejs-client#1009]
Hello,
[contributing.md](https://github.com/google/google-api-nodejs-client/blob/master/.github/CONTRIBUTING.md) file mentions about using  "npm run generate-docs" to generate documentation. But the "generate-docs" script is not present in the package.json file.

P.S: It's my first time raising any issue so please correct me if I did anything incorrectly.

Thanks!

**Comment by JustinBeckwith** [comment]
Apologies for the troubles.  Right now we're stuck between worlds with TypeScript and jsdoc annotations.  To generate TypeScript based docs, we need to get more of the typing moved over and available from the `d.ts`.  This is (slowly) in the works.
