### ISSUE TITLE
Progress upload not found

### ISSUE THREAD

**Issue by condorman** [google/google-api-nodejs-client#1017]
Hi, i try the youtube example: https://github.com/google/google-api-nodejs-client/blob/master/samples/youtube/upload.js.

The callback work fine, and Video is on youtube

```js
const req = youtube.videos.insert({
    part: 'id,snippet,status',
    notifySubscribers: false,
    resource: {
      snippet: {
        title: 'Node.js YouTube Upload Test',
        description: 'Testing YouTube upload via Google APIs Node.js Client'
      },
      status: {
        privacyStatus: 'private'
      }
    },
    media: {
      body: fs.createReadStream(FILENAME)
    }
  }, (err, data) => {
    if (err) {
      throw err;
    }
    console.log(data);
    process.exit();
  });
```

but the Req variable is "undefined"
`console.log(req) => undefined`

The progress upload fail:

```js
const id = setInterval(() => {
  const uploadedBytes = req.req.connection._bytesDispatched;
  const uploadedMBytes = uploadedBytes / 1000000;
  const progress = uploadedBytes > fileSize
    ? 100 : (uploadedBytes / fileSize) * 100;
  process.stdout.clearLine();
  process.stdout.cursorTo(0);
  process.stdout.write(uploadedMBytes.toFixed(2) + ' MBs uploaded. ' +
    progress.toFixed(2) + '% completed.');
  if (progress === 100) {
    process.stdout.write('\nDone uploading, waiting for response...\n');
    clearInterval(id);
  }
}, 250);
```

How can I get the progress of upload? Thank you.

My step:

- npm install googleapis --save
- configuration oauth2.keys.json
- video successfully uploaded on youtube but req variable empty

thank you!

**Comment by JustinBeckwith** [comment]
Greetings folks!  This is now fixed, and includes a sample.  You can see it here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/youtube/upload.js

This will be available in v28 :)
