### ISSUE TITLE
Google Sign-in and Google Sheets API V4

### ISSUE THREAD

**Issue by sashaskull** [google/google-api-nodejs-client#1042]
Hello there!

I am trying without success to ["Add Google Sign-In to Your Web App"](https://developers.google.com/identity/sign-in/web/) and then use Node.js with [Google Sheets API V4](https://developers.google.com/sheets/api/quickstart/nodejs) to be able allow my app to use the sheets api on behalf of the user (with scope: https://www.googleapis.com/auth/spreadsheets). 

I'm really confused on how to achieve this. Reading through most of the documentation from [OAuth2 ](https://developers.google.com/identity/protocols/OAuth2) doesn't clarify me best practices to achieve this with the Google Sign-In button.

Furthermore, I haven't found any documentation/guides related to this. I was hoping someone can guide me towards a good direction.

P.S: I managed to use the sheets api by following the [Node.js quickstart for Sheets API](https://developers.google.com/sheets/api/quickstart/nodejs), which allows me to achieve authorization through console, however I believe using the Sign-In button might simplify the process while making a nicer UX.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Are you trying to use this library from the browser, or from node.js?  If you're using the Google Sign In button, I'm left to guess that you're trying to use the browser. If that's the case, you should really look at this library:
https://developers.google.com/identity/sign-in/web/sign-in

If you are trying to use Node.js, I have a sample that shows you how to do it with a web browser:
https://github.com/google/google-api-nodejs-client/blob/master/samples/sheets/quickstart.js

Let me know if you still have any questions!

**Comment by sashaskull** [comment]
Thanks for the reply @JustinBeckwith ! At first I was trying to learn how to do it from node js, my purpose is to build an Electron app that uses Node js, Express and Express-handlerbars and interact with google's sheets API, but I really got confused in the process. Then I saw the same website you are suggesting ([Add Google Sign-In to Your Web App](https://developers.google.com/identity/sign-in/web/sign-in)) and gaved it a try, however I didn't know how to pass on the data from the html script to the node js scripts - if that makes any sense. Novice learner as you may see... Is it possible to use the google sign in button so that it automatically "authorizes" all future api requests? Any handy examples or guides?

Anyway, I had a look at your [quickstart.js](https://github.com/google/google-api-nodejs-client/blob/master/samples/sheets/quickstart.js) and I see yours is a much cleaner and simpler version, which doesn't even require to writeFile for the token...? I still got lots to learn xD

If you may suggest any docs, links or any useful data to achieve my purpose, it would be much appreciated.

**Comment by JustinBeckwith** [comment]
If you're going to be working primarily from the front end, then I really suggest using the front-end focused lib :)  This is the best place to start:
https://developers.google.com/api-client-library/javascript/start/start-js

Good luck!
