### ISSUE TITLE
Calendar API gives an error while inserting events using events.insert

### ISSUE THREAD

**Issue by rohitnaik246** [google/google-api-nodejs-client#1053]
Hi,
I used the code sample in Quickstart and tried inserting an event using the example on - [https://developers.google.com/calendar/v3/reference/events/insert#examples](https://developers.google.com/calendar/v3/reference/events/insert#examples)

I checked the resources available over the web and none of them seem to be working for me (downgrading googleapis package to version 24.0.0 or using different ways of writing the insert event).
This is the code of the **_addEvents function currently_** -

```js
function addEvents(auth){

var event = {
  "summary": "Google I/O 2015",
  "location": "800 Howard St., San Francisco, CA 94103",
  "description": "A chance to hear more about Google\'s developer products.",
  "start": {
    "dateTime": "2015-05-28T09:00:00-07:00",
    "timeZone": "America/Los_Angeles",
  },
  "end": {
    "dateTime": "2015-05-28T17:00:00-07:00",
    "timeZone": "America/Los_Angeles",
  },
  "recurrence": [
    "RRULE:FREQ=DAILY;COUNT=2"
  ],
  "reminders": {
    "useDefault": false,
    "overrides": [
      {"method": "email", "minutes": 24 * 60},
      {"method": "popup", "minutes": 10},
    ],
  },
};

//console.log(event)

  var calendar = google.calendar("v3");

  calendar.events.insert({
  auth: auth,
  calendarId: "primary",
  resource: event,
}, function(err, event) {
  if (err) {
    console.log("There was an error contacting the Calendar service: " + err);
    return;
  }
  console.log("Event created: %s", event.htmlLink);
});

}
```

It is on the same lines as the **_listEvents function_** -

```js
function listEvents(auth) {
var calendar = google.calendar('v3');
calendar.events.list({
    auth: auth,
    calendarId: 'primary',
    timeMin: (new Date()).toISOString(),
    maxResults: 10,
    singleEvents: true,
    orderBy: 'startTime'
    },
    function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }
    var events = response.items;
    if (events.length == 0) {
      console.log('No upcoming events found.');
    }
    else {
      console.log('Upcoming 10 events:');
      for (var i = 0; i < events.length; i++) {
        var event = events[i];
        var start = event.start.dateTime || event.start.date;
        console.log('%s - %s', start, event.summary);
    }
    }
  });
}
```

Can anyone please help me with this?

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Sadly the docs on developers.google.com are out of date; we are working to get them fixed.  In the interim - here are a few changes you need to make:

1. Make sure you didn't `npm install google-auth-library`.  If you did, delete it from your package.json, and run `npm install` again.

2. Import the library using `const {google} = require('googleapis');`, notice the `{}` around google. 

3. In your callback, instead of looking for `response.items`, use `response.data.items`.  This will be required in any of the callbacks coming from the API.  

I am guessing that after doing these things, you'll be back on rails :)  Let me know if you run into any problems!

**Comment by rohitnaik246** [comment]
Hey! Thanks for the quick reply!

Actually, I was getting an error in the addEvents function. The error was -
`There was an error contacting the Calendar service: Error: Missing end time.`

I followed the steps you mentioned, but I got the following error -
```
  var calendar = {google}.calendar("v3");
                                          ^
TypeError: {(intermediate value)}.calendar is not a function
```
Am I missing something here? Or am I doing anything wrong?

Also, I am trying to change the addEvents function rather than the listEvents function (which is working perfectly), where I do not need the callback as much. Will I still need to use response.data.items here?

**Comment by JustinBeckwith** [comment]
Heh, sorry for the confusion.  Use it like this:

```js
const {google} = require('googleapis');
const calendar = google.calendar("v3");
```

For any callback where you want the data, you can check in `response.data` :)  If you need it - it's there.  If not, that's fine too!

**Comment by rohitnaik246** [comment]
Hey!
I made those two changes and it is still not working.
I am getting a slightly different error -
```js
const calendar = google.calendar("v3");

TypeError: Cannot read property 'calendar' of undefined
```
What should I do about this? Is the remaining part of the addEvents method correct?

**Comment by JustinBeckwith** [comment]
Can you share your package.json?  and what version of Node.js you're running?

**Comment by rohitnaik246** [comment]
Sure!
This is the nodejs version I am running -
```
Rohits-MacBook-Pro:~ rohitnaik$ node -v
v9.6.1
```

Here is the `package.json` file -
```
{
  "name": "wolfplanner",
  "version": "1.0.0",
  "description": "Task Scheduling Bot",
  "main": "bot.js",
  "scripts": {
    "start": "node bot.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/neelkapadia/WolfPlanner.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/neelkapadia/WolfPlanner/issues"
  },
  "homepage": "https://github.com/neelkapadia/WolfPlanner#readme",
  "dependencies": {
    "apiai": "^4.0.3",
    "axios": "^0.18.0",
    "botkit": "^0.6.11",
    "debug": "^2.3.3",
    "dotenv": "^5.0.1",
    "express": "^4.14.0",
    "googleapis": "^24.0.0",
    "mongoose": "^5.0.9",
    "node-env-file": "^0.1.8",
    "request": "^2.83.0",
    "request-promise": "^4.2.2",
    "slack-node": "^0.1.8",
    "util": "^0.10.3"
  }
}
```

**Comment by JustinBeckwith** [comment]
Ah!  Please upgrade to version 27.

**Comment by rohitnaik246** [comment]
Hey! I did it. Still, the error remains the same.
I think there is some issue with the initial authentication part.
When you asked me to remove `npm install google-auth-library` did you also want me to remove the lines `var googleAuth = require('google-auth-library');` and `var auth = new googleAuth();` and 
```
function addEvents(auth){
...
}
```
since they use the google-auth-library?
Can this be causing the problem? Do you want me to share the starting authentication part of the nodejs file?

**Comment by idoadse** [comment]
Hey @rohitnaik246 encountered the same issues you had. I have followed all the suggestions above and for the auth part I have used the google.auth.OAuth2
Attached my current implementation of quickstart.js that results in a new event:

`var fs = require('fs');
var readline = require('readline');
var {google} = require('googleapis');
var OAuth2 = google.auth.OAuth2;
//var googleAuth = require('google-auth-library');


// If modifying these scopes, delete your previously saved credentials
// at ~/.credentials/calendar-nodejs-quickstart.json
var SCOPES = ['https://www.googleapis.com/auth/calendar'];
var TOKEN_DIR = (process.env.HOME || process.env.HOMEPATH ||
    process.env.USERPROFILE) + '/.credentials/';
var TOKEN_PATH = TOKEN_DIR + 'calendar-nodejs-quickstart.json';

// Load client secrets from a local file.
fs.readFile('client_secret.json', function processClientSecrets(err, content) {
  if (err) {
    console.log('Error loading client secret file: ' + err);
    return;
  }
  // Authorize a client with the loaded credentials, then call the
  // Google Calendar API.
  authorize(JSON.parse(content), listEvents);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 *
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  var clientSecret = credentials.installed.client_secret;
  var clientId = credentials.installed.client_id;
  var redirectUrl = credentials.installed.redirect_uris[0];
  var oauth2Client = new OAuth2(clientId, clientSecret, redirectUrl);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, function(err, token) {
    if (err) {
      getNewToken(oauth2Client, callback);
    } else {
      oauth2Client.credentials = JSON.parse(token);
      callback(oauth2Client);
    }
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 *
 * @param {google.auth.OAuth2} oauth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback to call with the authorized
 *     client.
 */
function getNewToken(oauth2Client, callback) {
  var authUrl = oauth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES
  });
  console.log('Authorize this app by visiting this url: ', authUrl);
  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  rl.question('Enter the code from that page here: ', function(code) {
    rl.close();
    oauth2Client.getToken(code, function(err, token) {
      if (err) {
        console.log('Error while trying to retrieve access token', err);
        return;
      }
      oauth2Client.credentials = token;
      storeToken(token);
      callback(oauth2Client);
    });
  });
}

/**
 * Store token to disk be used in later program executions.
 *
 * @param {Object} token The token to store to disk.
 */
function storeToken(token) {
  try {
    fs.mkdirSync(TOKEN_DIR);
  } catch (err) {
    if (err.code != 'EEXIST') {
      throw err;
    }
  }
  fs.writeFile(TOKEN_PATH, JSON.stringify(token));
  console.log('Token stored to ' + TOKEN_PATH);
}

/**
 * Lists the next 10 events on the user's primary calendar.
 *
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function listEvents(auth) {
  var calendar = google.calendar('v3');
  calendar.events.list({
    auth: auth,
    calendarId: 'primary',
    timeMin: (new Date()).toISOString(),
    maxResults: 10,
    singleEvents: true,
    orderBy: 'startTime'
  }, function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }
    var events = response.data.items;
    if (events.length == 0) {
      console.log('No upcoming events found.');
    } else {
      console.log('Upcoming 10 events:');
      for (var i = 0; i < events.length; i++) {
        var event = events[i];
        if (!event.start) {
          continue;
        }
        var start = event.start.dateTime || event.start.date;
        console.log('%s - %s', start, event.summary);
      }
    }
  // Refer to the Node.js quickstart on how to setup the environment:
// https://developers.google.com/calendar/quickstart/node
// Change the scope to 'https://www.googleapis.com/auth/calendar' and delete any
// stored credentials.

  var event = {
    'summary': 'Google I/O 2015',
    'location': '800 Howard St., San Francisco, CA 94103',
    'description': 'A chance to hear more about Google\'s developer products.',
    'start': {
      'dateTime': '2018-03-11T09:00:00-07:00',
      'timeZone': 'America/Los_Angeles',
    },
    'end': {
      'dateTime': '2018-03-11T17:00:00-07:00',
      'timeZone': 'America/Los_Angeles',
    },
    'recurrence': [
      'RRULE:FREQ=DAILY;COUNT=2'
    ],
    'attendees': [
      {'email': 'lpage@example.com'},
      {'email': 'sbrin@example.com'},
    ],
    'reminders': {
      'useDefault': false,
      'overrides': [
        {'method': 'email', 'minutes': 24 * 60},
        {'method': 'popup', 'minutes': 10},
      ],
    },
  };

  calendar.events.insert({
    auth: auth,
    calendarId: 'primary',
    resource: event,
  }, function(err, event) {
    if (err) {
      console.log('There was an error contacting the Calendar service: ' + err);
      return;
    }
    console.log('Event created: %s', event.htmlLink);
  });
});
  
}
`

**Comment by rohitnaik246** [comment]
Hey! Thanks for the detailed reply!
I tried running your code, but it gave me the same error as I was getting before.
I don't know why but I am getting this error -
```js
var OAuth2 = google.auth.OAuth2;
TypeError: Cannot read property 'auth' of undefined
```
Are you aware about this issue?
Thanks

**Comment by JustinBeckwith** [comment]
Try: `npm install googleapis@27` and then run again :)

**Comment by rohitnaik246** [comment]
Ah!
Finally it works!

Thanks a lot @JustinBeckwith and @idoadse for the help!

**Comment by JustinBeckwith** [comment]
Awesome!  Glar the hear you're back on track :D

**Comment by idoadse** [comment]
Great! Good luck :)

**Comment by jiang1224** [comment]
I'm facing the same problem. I've already tried npm install googleapis@27 and then run, but got the same err: There was an error contacting the Calendar service: Error: Insufficient Permission.
How did you fix this problem?

**Comment by naveenkash** [comment]
it is throwing this error after i install the googleapis library and if i uninstall the library the error goes away. here's the error

`ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\google-auth-library\build\src\auth'     
 @ ./node_modules/google-auth-library/build/src/auth/googleauth.js 17:24-48
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\google-auth-library\build\src\auth'
 @ ./node_modules/google-auth-library/build/src/auth/googleauth.js 18:11-24
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/google-p12-pem/build/src/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\google-p12-pem\build\src'
 @ ./node_modules/google-p12-pem/build/src/index.js 10:11-24
 @ ./node_modules/gtoken/build/src/index.js
 @ ./node_modules/google-auth-library/build/src/auth/jwtclient.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/googleapis-common/build/src/discovery.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\googleapis-common\build\src'
 @ ./node_modules/googleapis-common/build/src/discovery.js 16:11-24
 @ ./node_modules/googleapis-common/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/gtoken/build/src/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\gtoken\build\src'
 @ ./node_modules/gtoken/build/src/index.js 10:11-24
 @ ./node_modules/google-auth-library/build/src/auth/jwtclient.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/googleapis-common/build/src/http2.js
Module not found: Error: Can't resolve 'http2' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\googleapis-common\build\src'
 @ ./node_modules/googleapis-common/build/src/http2.js 16:14-30
 @ ./node_modules/googleapis-common/build/src/apirequest.js
 @ ./node_modules/googleapis-common/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\https-proxy-agent\dist'
 @ ./node_modules/https-proxy-agent/dist/agent.js 15:30-44
 @ ./node_modules/https-proxy-agent/dist/index.js
 @ ./node_modules/gaxios/build/src/gaxios.js
 @ ./node_modules/gaxios/build/src/index.js
 @ ./node_modules/google-auth-library/build/src/transporters.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js

ERROR in ./node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\navee\Desktop\chrome-extension-boilerplate-react-master\chrome-extension-boilerplate-react-master\node_modules\https-proxy-agent\dist'
 @ ./node_modules/https-proxy-agent/dist/agent.js 16:30-44
 @ ./node_modules/https-proxy-agent/dist/index.js
 @ ./node_modules/gaxios/build/src/gaxios.js
 @ ./node_modules/gaxios/build/src/index.js
 @ ./node_modules/google-auth-library/build/src/transporters.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/pages/Background/index.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/pages/Background/index.js`

here's the package.json

`{
  "name": "chrome-extension-boilerplate-react",
  "version": "2.7.0",
  "description": "A chrome extension boilerplate built with React 16 and Webpack 4",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "build": "node utils/build.js",
    "start": "node utils/webserver.js",
    "prettier": "prettier --write '**/*.{js,jsx,css,html}'"
  },
  "dependencies": {
    "@hot-loader/react-dom": "^16.13.0",
    "@types/chrome": "0.0.104",
    "@types/react": "^16.9.26",
    "googleapis": "^61.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hot-loader": "^4.12.20"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "babel-preset-react-app": "^9.1.2",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.1.1",
    "css-loader": "^3.4.2",
    "eslint": "^6.8.0",
    "eslint-config-react-app": "^5.2.1",
    "eslint-plugin-flowtype": "^4.7.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^3.0.0",
    "file-loader": "^6.0.0",
    "fs-extra": "^9.0.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "^4.0.2",
    "node-sass": "^4.14.1",
    "prettier": "^2.0.2",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "3.2.1",
    "write-file-webpack-plugin": "^4.5.1"
  }
}
`

**Comment by Sai-kiran-Yalagandhala** [comment]
> (for some reason my code is not displayed correctly, let me know if you need entire quickstart.js file content)

if you could share us the snippet it will be very helpful
