### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by jmartindivmedianet** [google/google-api-nodejs-client#1059]
Trying out the "Using API keys" node code.  Adapted it for Google Sheets.  
My own API key and spreadsheet id are in place of the dummies below.
The response from the API call is an error:
"unable to verify the first certificate".

If I remove the spreadsheetId line, it will respond "Missing required parameters: spreadsheetId".
I can't tell, from the error message, if this is a node or Google issue for me.

Code:

```js
var { google } = require('googleapis');
var sheets = google.sheets('v4');

var API_KEY = 'my_api_key';

sheets.spreadsheets.get({
    auth: API_KEY,
    spreadsheetId: 'my_spreadsheet_id',
}, function(err, response) {
    console.log('response: ' + response);
    console.log('Result: ' + (err ? err.message : 'good'));
});
```

Thanks!

**Comment by JustinBeckwith** [comment]
Weird.  Does this work for you from here?
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get

**Comment by JustinBeckwith** [comment]
Also - are you by chance behind a proxy?

**Comment by jmartindivmedianet** [comment]
Hey, thanks so much for the quick reply.  It DOES work on the developers.google.com site.  I'm told we just installed a Barracuda firewall only about a month ago.  I need to run the node.js server on a standalone PC.  Any idea which IP(s) I'd need to whitelist on the Barracuda?

**Comment by jmartindivmedianet** [comment]
The certs link works great, the spreadsheets one is definitely being blocked by Barracuda.  You're right!

**Comment by jmartindivmedianet** [comment]
Switched to our guest network... there's the traffic!  (not sure if the image can be pasted)...

![image](https://user-images.githubusercontent.com/10353292/37313160-5e3e4210-2624-11e8-8e72-b1240980ea40.png)

**Comment by jmartindivmedianet** [comment]
Very psyched.  Able to read values from the spreadsheet's Sheet1.  Excellent questions, Justin, thanks for saving me a lot of time! Very much appreciated.

**Comment by JustinBeckwith** [comment]
Great to hear you're on track :)
