### ISSUE TITLE
Two way to use API

### ISSUE THREAD

**Issue by enguerran** [google/google-api-nodejs-client#1070]
I am asking myself if there is two ways to use the API:

```js
const { google } = require("googleapis");
const OAuth2Client = google.auth.OAuth2;
// configure a new OAuth2Client to get an access_token
const personFields = ["emailAddresses", "names"];
const url = `https://people.googleapis.com/v1/people/me/connections?personFields=${personFields.join(
  ","
)}`;
const res = await oAuth2Client.request({ url });
console.log(JSON.stringify(res.data.connections, null, 2));
```
and

```js
const { google } = require("googleapis");
const OAuth2Client = google.auth.OAuth2;
// configure a new OAuth2Client to get an access_token
const people = await google.people({
  version: "v1",
  auth: oAuth2Client
});
const res = await people.people.connections.list(
  { resourceName: "people/me" },
  async (res, err) => {
    console.log("error: ", err);
    console.log("res1: ", res);
  }
);
console.log("res2:", res);
```
1. are they equivalent?
1. how to use the second version?
1. what do you recommand?

PS : I opened a [SO question because I cannot manage to get a response with the second version](https://stackoverflow.com/questions/49304273/enable-to-get-an-response-with-people-connections-list).

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  With the first method, you're really just using https://github.com/google/google-auth-library-nodejs to handle authentication tokens, and then making the direct HTTP calls to googleapis yourself.  That's a perfectly valid way to do things.  However - there are *lots* of corner cases that can make doing that across all the APIs kinda hard.  

This library includes the google-auth-library, *and* it has auto-generated methods that make talking to the various endpoints easier.  

They're mostly equivalent.  On how to use the second version - we don't natively support promises with this library, so the code you wrote there likely won't work.  I would start by taking a look at the many samples we have pushed here:
https://github.com/google/google-api-nodejs-client/tree/master/samples

Unless you have a reason to go down to the HTTP layer - I'd generally recommend sticking with this library (method 2) instead of trying to do the calls yourself :) 

Hope this helps, and let us know if you have any other questions!

**Comment by enguerran** [comment]
Thanks @JustinBeckwith for your answer.
I should edit my code sample: async/await keywords were a test.

I can't manage to get this example to work: https://github.com/google/google-api-nodejs-client#making-authenticated-requests

I will follow your advice to use the _method 2_ to request data, but I cannot at this moment.

**Comment by JustinBeckwith** [comment]
Got it!  If you're specifically trying to use plus like that API, look at this sample:
https://github.com/google/google-api-nodejs-client/blob/master/samples/people/me.js

**Comment by enguerran** [comment]
@JustinBeckwith That is my problem, I tried with `people.people.get` or `people.people.connections.list` or with this exact sample `plus.people.get` (with new scope). I can get tokens without any problem, and those tokens work fine with the low level https://github.com/google/google-auth-library-nodejs API. But not with this one. (Sorry to pollutate this issue)

**Comment by JustinBeckwith** [comment]
It doesn't look like you're passing the auth client into the `get` call.  Try this?

```js
var plus = google.plus({ version: "v1", auth: oAuth2Client });
```

That will ensure the credentials you're setting get passed to the api client.

**Comment by enguerran** [comment]
Yet another mistake on my part, but only in code and screenshots I post on this issue.
I do pass the auth client with `google.plus({ version: "v1", auth: oAuth2Client })` and I also tried the other way illustrated in the documentation (https://github.com/google/google-api-nodejs-client/#making-authenticated-requests) `plus.people.get({ userId: 'me', auth: oauth2Client }, function (err, response) {});`.

But still no error nor response. And I am still stucked with this API.

**Comment by enguerran** [comment]
I tried with
```js
var people = google.people({ version: "v1", auth: oAuth2Client });
const res = people.people.connections.list(
  { resourceName: "people/me", personFields: ["names"] },
  (res, err) => {
    console.log("error: ", err);
    console.log("res1: ", res);
  }
);
console.log("res2:", res);
```

The callback is never called and `res2` is `undefined`.

**Comment by enguerran** [comment]
And the final mistake on my own, here was my code:

```js
async function start () {
  const tokens = await googleHelper.getTokens();
  const oAuth2Client = googleHelper.getOAuthClient();
  oAuth2Client.setCredentials({
    access_token: tokens.access_token,
    refresh_token: tokens.refresh_token
  });
  // const contacts = googleHelper.getConnectionsList()
  var peopleAPI = google.people({ version: "v1", auth: oAuth2Client });
  const res = peopleAPI.people.connections.list(
    { resourceName: "people/me", personFields: ["names"] },
    (err, res) => {
      console.log("err", err);
      console.log("res", util.inspect(res.data));
    }
  );
  process.exit(0); // write this because I do not want the following from a boilerplate to be executed, I am an ~~idiot~~ tired developer
  return request(`${baseUrl}/index.html`).then($ => {
    const entries = Array.from($("article")).map(article =>
      parseArticle($, article)
    );
    console.log(entries);
  });
}

start();
```

I just saw the `process.exit(0)`: the main thread was terminated before the callback was called.

:persevere: :confounded: :tired_face:
