### ISSUE TITLE
Insufficient permission error when trying to modify store listings of an app

### ISSUE THREAD

**Issue by soniaioan** [google/google-api-nodejs-client#1071]
I am using nodes client for google publisher api and I have created a service account with permissions: Restricted app visibility, Edit store listing, pricing & distribution and View financial data. In Google Developers console this account has been set to be used as a service account actor.
My issue is that whenever I use this service account to edit store listings of the application the response is "The current user has insufficient permissions to perform the requested operation." If I granted service account Release Manager rights it works as it should.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share a code snippet that shows the behavior?  If it works with the expanded set of rights, it's possible this is more an issue with the underlying service than the node.js client.  More details would be super helpful!

**Comment by soniaioan** [comment]
I have contacted with Google . It is a known issue in the architecture.
Thanks for your help.

**Comment by JustinBeckwith** [comment]
Great to hear!  Can you share a few more details for others that may run into the same issue?

**Comment by soniaioan** [comment]
Hi, 
Sure, the complete response is that bizarrely, this actually seems to be working as intended where the API is concerned. Apparently, the user interface segments (edit store listing, manage releases, etc) as defined in the developer console are not strictly identical on the API side. For certain things, the API has to assume that whole releases are being changed, and that includes store listing locales. This is a known issue in the architecture (the engineer described it as "not pretty"), and unfortunately, there's no real workaround at the moment. Either the permissions level must be increased, or the user must log into the developer console and edit through the UI, not through the API.
