### ISSUE TITLE
Admin.Users.List not working (return Bad request)

### ISSUE THREAD

**Issue by gueei** [google/google-api-nodejs-client#1072]
Following the quickstart guide in this url:
https://developers.google.com/admin-sdk/directory/v1/quickstart/nodejs

In calling this function: 
`service.users.list({
   auth: auth,
   customer: 'my_customer'
}...)`

It always returns bad request without any further useful information. 
I'm quite sure I have certain rights required as I can test the same function in the online api explorer. And I also tried to change the above example program into:
`service.users.get({
    auth: auth,
    userKey: 'someuserkey@mydomain'
...`

And it returns correct results. 
Both V25 and V27 of the api library is tested.

**Comment by gueei** [comment]
I did a dirty fix and it works.. 
the params should called qs when it send to the Request object. So I eventually copy the params to qs like:
Line 2370 of directory_v1.js:
`               params: params,
                qs: params,
`

**Comment by JustinBeckwith** [comment]
Greetings!  The real problem here is likely a mismatched version of google-auth-library.  Please make sure google-auth-library IS NOT in your package.json.
