### ISSUE TITLE
Feature request: allow to stream compressed data into BigQuery

### ISSUE THREAD

**Issue by xgalen** [google/google-api-nodejs-client#1075]
Hi all,

In order to save data transfer (out) costs, we would want to stream the data compressed with `gzip`.

I have made some tries and it works, requesting directly to the API. Example (omitting values for the sake of simplicity):

```
#!/bin/bash

...

OBJECT="{'kind': 'bigquery#tableDataInsertAllRequest', 'skipInvalidRows': true, 'ignoreUnknownValues': true, 'rows': $ROWS}"

echo $OBJECT | gzip -cf > compressed.gz

curl -v -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: text/plain" \
     -H "Content-Encoding: gzip" \
     --data-binary @compressed.gz \
"https://www.googleapis.com/bigquery/v2/projects/$GOOGLE_CLOUD_PROJECT/datasets/$DATASET_ID/tables/$TABLE_ID/insertAll"
```

But I couldn't find where to set the header to change the `content-encoding` to `gzip`.
I know it's an option to the responses and to store files ( https://github.com/googleapis/nodejs-bigquery/blob/fbe4f93f9167e904ee9d0beaf27f0d0b9da6d7bb/src/table.js#L728 ) but no for requesting.

Is it possible to add a new setting to allow compress or not? In that case, the responsibility of the compression is for the server, not for this module. I think it would be worth :)

Of course, I could help if needed.

Thanks!

Alfredo

**Comment by JustinBeckwith** [comment]
Greetings!  Which npm module are you trying to use?  Are you using `@google-cloud/bigquery` or`googleapis`?  In general, if there's a standalone module that does what you're looking for, it's usually a better bet than this module :) 

If you're looking for gzip compression on the *download* - we actually just landed that, and it will be in the v28 release!
https://github.com/google/google-api-nodejs-client/commit/e900d4cec460f5b01fc766a2f8a4420e1d39731d

If you're looking for compression on uploads....   I was kind of waiting for someone to ask for that :) That having been said, it's likely something we should just do over in `google-cloud/bigquery`.

cc @alexander-fenster @stephenplusplus

**Comment by stephenplusplus** [comment]
This issue looks familiar! :) https://github.com/googleapis/nodejs-bigquery/issues/75

**Comment by JustinBeckwith** [comment]
hah, in that case - lets just track this over there :)

**Comment by xgalen** [comment]
Thanks! I put here first by error but then I decided to let it here just in case :D
