### ISSUE TITLE
Query attribute doesn't work on drive.files.list v3

### ISSUE THREAD

**Issue by mbbender** [google/google-api-nodejs-client#1076]
When calling

```
const req = drive.files.list({q: "name='BC01-TSP10'"}, (error, response) => {
        if(error) reject(error)
        console.log(response)
        resolve(response)
      })
```

The q property does nothing. Actually it seems to me none of the identified properties do anything. I tried searching through the source but was unable to determine what was wrong. When using the API tester it works fine.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you please check to see if `google-auth-library` is in your package.json?  If it is, please remove it, run `npm install`, and try again :)

**Comment by mbbender** [comment]
Thanks Justin. It is in there, but all the examples are using it to generate the Oauth2 object. Should I look at a different library for OAuth2 authentication with google?

**Comment by JustinBeckwith** [comment]
Not at all!  We include a specific version of google-auth-library inside of this npm module.  You really just have to follow this guide:
https://github.com/google/google-api-nodejs-client/#generating-an-authentication-url

```js
const google = require('googleapis');
var oauth2Client = new google.auth.OAuth2Client(
  YOUR_CLIENT_ID,
  YOUR_CLIENT_SECRET,
  YOUR_REDIRECT_URL
);
```

Let me know if you have any questions!

**Comment by mbbender** [comment]
In case anyone else finds this it is `new google.auth.OAuth2(...)`  not OAuth2Client.

**Comment by JustinBeckwith** [comment]
ooooops :) Updated!

**Comment by mbbender** [comment]
@gorangio OAuth2 is a function in that library try ` var OAuth2 = new google.auth.OAuth2(....)` like in Justin's comment.

**Comment by gorangio** [comment]
@mbbender Thanks, and I see what you mean, but the error message "TypeError: Cannot read property 'OAuth2' of undefined" is referring to "auth" being "undefined". So adding the parameters to OAuth2 doesn't change anything.

**Comment by mbbender** [comment]
I believe these are the important part of the code that got it working for me
``` javascript
var google = require('googleapis');
...
// If modifying these scopes, delete your previously saved credentials
// at ~/.credentials/sheets.googleapis.com-nodejs-quickstart.json
const SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/drive.metadata.readonly'];
const TOKEN_DIR = (process.env.HOME || process.env.HOMEPATH ||
    process.env.USERPROFILE) + '/.credentials/';
const TOKEN_PATH = TOKEN_DIR + 'sheets.googleapis.com-nodejs-quickstart.json';


/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 *
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
const authorize = async () => {
  const credentials = JSON.parse(fs.readFileSync(path.join(__dirname,'../google_client_secret.json'))) 
  const clientSecret = credentials.installed.client_secret;
  const clientId = credentials.installed.client_id;
  const redirectUrl = credentials.installed.redirect_uris[0];
  const oauth2Client = new google.auth.OAuth2(clientId, clientSecret, redirectUrl);
  
  // Check if we have previously stored a token.
  try {
    const token = JSON.parse(fs.readFileSync(TOKEN_PATH))
    if(!token) { throw new Error('Invalid token file on disk. Attempting to get a new one.') }
    oauth2Client.credentials = token
    return oauth2Client
  } catch (error) {
    return await getNewToken(oauth2Client)
  }
}
```

**Comment by mbbender** [comment]
I did just notice I have version 25 though.
```javascript
    "googleapis": "^25.0.0",
```
