### ISSUE TITLE
Listing all files with GSuite Drive v3

### ISSUE THREAD

**Issue by chunggabriel** [google/google-api-nodejs-client#1089]
We are using JWT(success) in nodejs environment to access drive.files.list().
It should shows all files but it does not.
What can we do?

**Comment by fengmao** [comment]
same problem here, i can list files uploaded with JWT, but cannot list files manually uploaded

**Comment by JustinBeckwith** [comment]
Greetings!  Are you using a G-Suite account?  I *think* the service account you're using in your JWT credentials needs to be granted domain wide delegation:
https://developers.google.com/admin-sdk/directory/v1/guides/delegation

Can you give those steps a shot and let me know how it goes?

**Comment by JustinBeckwith** [comment]
If this is still an issue, please let me know :)

**Comment by saritaf** [comment]
I am facing same issue. I have given domain wide delegation but I cannot view all the files. I can see the files shared with service email and admin email only
