### ISSUE TITLE
[androidpublisher] Manage Testers in PlayStore closed Testing (alpha/beta)

### ISSUE THREAD

**Issue by ulfgebhardt** [google/google-api-nodejs-client#1092]
It is currently not possible to manage the Testers of an App via API. You can either upload CSV files or add them manually.

The [API reference](https://developers.google.com/android-publisher/api-ref/edits/testers/update) contains a reference to this feature, but its largely undocumented and unfunctional since it operates on Google Groups.

![image](https://user-images.githubusercontent.com/1238238/38085173-e77dec00-334f-11e8-8d9f-7e6778e026df.png)

---

Prequesites:
- googleapis installed via packagemanager
- Google Developer Service Key (Get it in the Play Developer Console - if you are the AppOwner)

```
let { google } = require('googleapis');
let privatekey = require("../Google_Play_Android_Developer-***.json");

// configure a JWT auth client
let jwtClient = new google.auth.JWT(
    privatekey.client_email,
    null,
    privatekey.private_key,
    ['https://www.googleapis.com/auth/androidpublisher']
);

var androidpublisher = google.androidpublisher({ version: 'v2', auth: jwtClient });

// insert edit transaction
androidpublisher.edits.insert({ packageName: 'de.democracydeutschland.app', auth: jwtClient }, (err, editResource) => {
    const editId = editResource.data.id;
    androidpublisher.edits.testers.get({ packageName: 'de.democracydeutschland.app', track: 'alpha', editId }, (err, data) => {
      console.log(data); //data.data = {} 
      console.log(err); // = null
    });
  });
```

The API call returns an empty Object - the alpha Track has Testers set.

The documented API Result:

![image](https://user-images.githubusercontent.com/1238238/38085066-765774e2-334f-11e8-867d-61402590ce64.png)

---

**Providing a Method to add Testers to an alpha/beta Test via API would allow alot more automation with testing apps.**

An old closed Issue describing the same Problem: #516

@google-admin  If this is not the right place to report Problems/FeatureRequests for the Google API, please provide me with the right location or migrate this Issue there.

[API reference](https://developers.google.com/android-publisher/api-ref/edits/testers/) & [API Explorer](https://developers.google.com/apis-explorer/#p/androidpublisher/v2/androidpublisher.edits.testers.update)

**Comment by JustinBeckwith** [comment]
Greetings!  Sadly, there's nothing we can really do with this from the API.  This library is really only capable of working with the API endpoints that are already available. 

For changers to the underlying API, I'd suggest opening an issue with the Android Developer Platform team:
https://issuetracker.google.com/issues/new?component=190923&template=841312

Sorry this wasn't the answer you're looking for... but I hope this helps!

**Comment by noelstieglitz** [comment]
@ulfgebhardt - did you make any progress with this issue?  I followed the link you posted above, but found that it has been closed with a recommendation that you reach out to a different group.  Can you point me to the issue (if it exists)?

**Comment by ulfgebhardt** [comment]
@noelstieglitz I did make an appeal there. But this is not linkable. You can just send them some text.
I gave up on that particular issue. I mean: I reported this issue on 3 different locations and nobody felt responsible. Don't expect this to get fixed anytime soon.

**Comment by noelstieglitz** [comment]
@ulfgebhardt - thanks for the response.  I went through the same process and had the same experience.  To work around the issue, we're moving to App Center to distribute beta builds out of band.

**Comment by ulfgebhardt** [comment]
We inserted 5k EMails manually - you know - there is nothing else to do ;-)
