### ISSUE TITLE
createApiRequest encodes url, resulting in 404 for pubsub endpoints

### ISSUE THREAD

**Issue by tushar-singh** [google/google-api-nodejs-client#1099]
I'm trying to pull() a subscription using `pubsub.projects.subscriptions.pull()` 

```javascript
const pubsub = google.pubsub('v1');
const request = {
    subscription: 'projects/project-1235/subscriptions/my-subscription',
    auth: oAuthClient,
    resource: {
        maxMessages: 1,
        returnImmediately: true,
    },
};

pubsub.projects.subscriptions.pull(request, cb);
```
But it results in a 404. 

I looked around and apparently it is because [this line here](https://github.com/google/google-api-nodejs-client/blob/master/src/lib/apirequest.ts#L128
) encodes the URI and forward slashes become `%2F` and google doesn't recognise it. 

This is probably required for other requests so i'm not quite sure what the fix would be.

Currently I'm creating the request myself and calling it with `authClient.request()`. If anyone else is stuck with this, here's my temporary fix:

```javascript
const project = 'my-project-12345';
const subscription = 'my-subscription';

const pullReq = {
    url: `https://pubsub.googleapis.com/v1/projects/${project}/subscriptions/${subscription}:pull`,
    method: 'POST',
    paramsSerializer: params =>
        qs.stringify(params, { arrayFormat: 'repeat' }), // qs = require('qs')
    params: {
        maxMessages: 1,
        returnImmediately: true,
    },
    maxContentLength: 2147483648,
    validateStatus: status =>
        (status >= 200 && status < 300) || status === 304,
};

oAuthClient.request(pullReq).then(response => { ...
```

**Comment by jamie-pate** [comment]
This also affects `serviceusage.list` etc

**Comment by jamie-pate** [comment]
Looks like it's caused by this commit?

https://github.com/google/google-api-nodejs-client/commit/d89a735d54a5346cd326aef1b41939989d3f6506

**Comment by JustinBeckwith** [comment]
Apologies for the trouble folks "It seemed like a good idea time" (™).  Taking a look now.

**Comment by MennoTammens** [comment]
From the [API Discovery Service Documentation](https://developers.google.com/discovery/v1/using#build-compose):
> The `path` property of each method in the API uses [URI Template v04](http://code.google.com/p/uri-templates/) syntax. This property may contain variables, which are surrounded by curly braces.

In `google-api-nodejs-client` the special URI Template operators (`+`, `/` and `*`) were stripped from the path, to make the templates compatible with the `string-template` module.  
The `string-template` module should be replaced with a URI Template module.

**Comment by SpencerHehl** [comment]
Looks like it is already in progress but just want to throw out there that it is affecting the IoT APIs as well. Specifically I've the modifycloudtodeviceconfig method, but I would assume it affects other methods within that API as well.

**Comment by parnurzeal** [comment]
Also, affecting ml api -> ml.projects.predict(...)
clearly the error returns url not found with %2F in it.

**Comment by tomnewton** [comment]
it is affecting a ton of apis. Looks like a fix is almost there.
