### ISSUE TITLE
JSDocs links are invalid.

### ISSUE THREAD

**Issue by ktkaushik** [google/google-api-nodejs-client#1120]
Hello,

The link to the JSDocs are going to a 404 here => https://github.com/google/google-api-nodejs-client/tree/master/samples#samples-by-api

Thanks!

**Comment by JustinBeckwith** [comment]
Thanks!  Could you be a little more specific? Which sample specifically is giving you trouble?  Which links?

**Comment by JustinBeckwith** [comment]
Awesome.  Thanks!  Fix is in #1122

**Comment by ktkaushik** [comment]
👍
