### ISSUE TITLE
title and content is not being added to post BLOGGER

### ISSUE THREAD

**Issue by m-afrasiab** [google/google-api-nodejs-client#1139]
I am having an issue with blogger api. When I try to publish a post to my blogger, the empty post got published. No title or content get included in it. Below is the code:

```js
var express = require('express');
var app = express();
var request = require('request');
var rp = require('request-promise');
const google = require ('googleapis');
const Youtube = require("youtube-api");
const blogger = google.google.blogger('v3')
    , fs = require("fs")
    , readJson = require("r-json")
    , Lien = require("lien")
    , Logger = require("bug-killer")
    , opn = require("opn")
    , prettyBytes = require("pretty-bytes")
    ;
// I downloaded the file from OAuth2 -> Download JSON
const CREDENTIALS = readJson('./bcreds.json');
// Init lien server
let server = new Lien({
    host: "localhost"
  , port: 6111
});
// Authenticate
let oauth = Youtube.authenticate({
    type: "oauth"
  , client_id: CREDENTIALS.web.client_id
  , client_secret: CREDENTIALS.web.client_secret
  , redirect_url: CREDENTIALS.web.redirect_uris[0]
});
opn(oauth.generateAuthUrl({
    access_type: "offline"
  , scope: ["https://www.googleapis.com/auth/blogger"]
}));
// Handle oauth2 callback
server.addPage("/oauth2callback", lien => {
    Logger.log("Trying to get the token using the following code: " + lien.query.code);
    oauth.getToken(lien.query.code, (err, tokens) => {
        if (err) {
            lien.lien(err, 400);
            return Logger.log(err);
        }
        Logger.log("Got the tokens.");
        oauth.setCredentials(tokens);
        lien.end("The video is being uploaded. Check out the logs in the terminal.");

        blogger.posts.insert({
                auth: oauth,
                blogId: "7525914434133284870",
                resource: {
                  content: "postContent",
                  title: "postTitle",
                },  
            }, function(err, success){
                console.log(success);
            });
    });
});
```

**Comment by JustinBeckwith** [comment]
Aiight, that's good at least.  I'm sorry for asking this - but can you make 100% sure the title and content you're passing to the API isn't in fact blank?  Just add a little console.log magic to make 100% sure?

Alright - a few other things to check:
- What version of node.js are you running?
- What version of googleapis is in your package.json?
- Please verify YOU DO NOT have `google-auth-library` in your package.json.

**Comment by m-afrasiab** [comment]
the node version is `8.10.0`
googleapis version is `27.0.0`
and I do not have` google-auth-library` in my package.json

**Comment by JustinBeckwith** [comment]
Can you try upgrading to the latest version?  I think we're on 29 now :)

**Comment by m-afrasiab** [comment]
I have upgraded to latest version but still it is posting empty post to blogger.

**Comment by JustinBeckwith** [comment]
I'm running out of ideas here 🤣  I merged #1140 earlier - can you clone the repo, and try running that sample?

**Comment by m-afrasiab** [comment]
I have run the sample and got this error
`TypeError: Cannot read property 'data' of undefined
    at runSample (C:\Program Files\nodejs\proj\apv.js:19:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by m-afrasiab** [comment]
Ok I have fixed it. Now it is working properly. thanks very much to you for your time and help.

**Comment by m-afrasiab** [comment]
I have question that, it would requires me to choose account for every single post. is it possible in anyway that I only have to select account in browser for only once for multiple posts.
