### ISSUE TITLE
Content Shopping API customBatch not working

### ISSUE THREAD

**Issue by bretthadley** [google/google-api-nodejs-client#1147]
Hi,

Trying to use the `datafeedstatuses.custombatch` method which doesn't appear to be working correctly.

```js
return client.datafeedstatuses.custombatch({
  entries: [
    {merchantId: '121827835', datafeedId: '104916117', method: 'get', batchId: 1}
  ]
}).then((res) => {
  return res.data;
});

// returns { kind: 'content#datafeedstatusesCustomBatchResponse' } 
// with nothing else (200 OK response)
```

Yet the API playground here : https://developers.google.com/shopping-content/v2/reference/v2/datafeedstatuses/custombatch works perfectly fine.

**Comment by JustinBeckwith** [comment]
Greetings!  I know this isn't readily obvious, but you need to add a `resource` field that contains those objects since they're sent as part of the body:

```js
return client.datafeedstatuses.custombatch({
  resource: {
    entries: [
      {merchantId: '121827835', datafeedId: '104916117', method: 'get', batchId: 1}
    ]
  }
}).then((res) => {
  return res.data;
});
```

Could you give this a try and let me know what you get?

**Comment by bretthadley** [comment]
@JustinBeckwith Thanks that seems to be going though now but getting another error related to batch requests across multiple MCA's which is an issue for me to fix.

Cheers!
