### ISSUE TITLE
Documentation on getting new access token with refresh token

### ISSUE THREAD

**Issue by abea** [google/google-api-nodejs-client#1157]
The documentation is great for using the OAuth API to get tokens, but it's not clear how it can be used to get a new access token. If someone would clarify that for me I'd be happy to make a PR.

I see an [issue from early last year](https://github.com/google/google-api-nodejs-client/issues/673#issuecomment-279616392) that seems to pass in the `oauth2Client` object as authentication to one of the other APIs in this client. I'm using the OAuth API here, but a Google service that's not included in the other APIs (Google My Business). Is there not a way to get the new access token more directly?

**Comment by usamamashkoor** [comment]
Did you find any solution for this?

**Comment by abea** [comment]
@usamamashkoor Yes, I documented what I did in this PR: https://github.com/googleapis/google-api-nodejs-client/pull/1177/files

**Comment by usamamashkoor** [comment]
Thanks man for the quick response.
