### ISSUE TITLE
"appProperties" field not being returned for files

### ISSUE THREAD

**Issue by Mk-Etlinger** [google/google-api-nodejs-client#1166]
**Edit**
Please Close:

See here for solution: https://stackoverflow.com/questions/50301159/googleapis-appproperties-field-not-being-returned-for-files-in-node
** 

I'm trying to get the `appProperties` field to be returned with my files on gdrive, but currently unable to get it working.

    "googleapis": "^29.0.0"

  
Here's my scopes and fields:
```
    scopes: [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/drive.metadata.readonly"
      ]

    fields = ["id", "name", "mimeType", "parents", "description", "modifiedTime", "appProperties"]
```
All of the other properties come back using `drive.files.list` without issue, but it won't return the `appProperties` field.
```
     getFilesByQuery: function( queryString , extraFields ){
    
        var fields = ["id", "name", "mimeType", "parents", "description", "modifiedTime", "appProperties"];
        if( extraFields && extraFields.length )
          fields = fields.concat( extraFields );
    
        return drive.files.list({
          'pageSize': 200,
          'fields': `nextPageToken, files(${ fields.join(', ') })`,
          'q': queryString
        });
      }
```

When I query directly through files/get on dev.google API, this is what I get back for that file:

```
    {
     "name": "US",
     "appProperties": {
      "order": "1"
     }
    }
```

Any ideas?

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like this all got sorted out over here 😀
https://stackoverflow.com/questions/50301159/googleapis-appproperties-field-not-being-returned-for-files-in-node

If you're still running into issues...  Let us know!
