### ISSUE TITLE
Cannot find module 'googleapis/lib/apirequest'

### ISSUE THREAD

**Issue by zachschultz** [google/google-api-nodejs-client#1171]
I'm trying to access `createAPIRequest` from https://google.github.io/google-api-nodejs-client/modules/_lib_apirequest_.html but the following code: 

```
const { createAPIRequest } = require("googleapis/lib/apirequest");
``` 

gives me this error: `Cannot find module 'googleapis/lib/apirequest'`.

My `package.json` is:

```
{
  "name": "my_app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "googleapis": "^30.0.0",
  }
}
```
I'm sure I must be forgetting something silly, but for the life of me I can't figure this one out.

**Comment by JustinBeckwith** [comment]
Greetings!  Why are you trying to directly call `createAPIRequest`?  This is very much an internal implementation detail of the library.

**Comment by zachschultz** [comment]
Hi! Thanks for the response. I inherited some old code that directly calls that function, but now looking through the examples/docs more it seems like you're right. I'll close this issue.

**Comment by niftylettuce** [comment]
`npm install googleapis-common` and then `const { createAPIRequest } = require('googleapis-common')`
