### ISSUE TITLE
Unauthorized Client on Google App Engine

### ISSUE THREAD

**Issue by bevbomb** [google/google-api-nodejs-client#1181]
Hi, I am using Google App Engine to host both server side code and a web app.
The server is used to handle Google Auth and access for Calendars.
It uses the server side authentication flow by generating an authorisation token from the client and sending it to the server to exchange for tokens.

This works well when running my client from my localhost but when i run through the same flow using the live client i receive an unauthorised_client error.

I've declared both the server side and client side domains under the credentials section, using both the custom domains and the originally generated Google App Engine paths.

Server side code using express. Obviously i've blanked out my client keys.

```javascript
var express = require('express');
var router = express.Router();
const {google} = require('googleapis');

router.post('/', function(req, res, next) {
  const oauth2Client = new google.auth.OAuth2(
		"CLIENT_ID",
		"CLIENT_SECRET",
		"postmessage"
	);

  var code = req.body.code
  var userId = req.body.userId
  oauth2Client.getToken(code).then(resp => {
    if (resp.tokens) {
      let tokens = resp.tokens
      res.json({status: "success"})
    } else {
      res.json({status: "failed"})
    }
  }).catch(error => {
    console.log(error)
    res.json({status: "failed", error: error.message})
  })
})

module.exports = router;
```

Client side code:
Angular 5+
ng-gapi to load Google api.

```Typescript
public getGoogleAuth(): Promise<any> {
    return new Promise(resolve => {
      this.googleAuth.getAuth().subscribe(auth => {
        resolve(auth)
      })
    });
  }

async googleSignIn() {
    try {
      let auth = await this.getGoogleAuth()
      let { code } = await auth.grantOfflineAccess({
        'redirect_uri' : 'postmessage',
        scope: "https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar"
      })
    } catch(error) {
      console.log(error)
      return Promise.reject(error);
    }
  }
```

**Comment by JustinBeckwith** [comment]
Greetings!  A few questions/thoughts:
- Are you using App Engine Flexible, or App Engine standard?
- Can you share the full call stack you receive?  Is the error you're getting on the client or on the server?

At a first glance, this doesn't seem to be quite right:

```js
const oauth2Client = new google.auth.OAuth2(
		"CLIENT_ID",
		"CLIENT_SECRET",
		"postmessage"
	);
```

The third parameter in the constructor is the redirect_uri.  I don't think `postmessage` would make much sense here.

**Comment by JustinBeckwith** [comment]
Greetings! If this is still an issue, please do let us know 🤗

**Comment by bevbomb** [comment]
Hi @JustinBeckwith 
This is no longer an issue. After hours spent searching i found that postmessage is required if there isn't any redirect from the web but if i were to use the same function to handle it from an iOS device i had to remove the redirect uri all together.

Thanks
