### ISSUE TITLE
oauth2: keys.redirect_uris[0] , TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by aarontanzk** [google/google-api-nodejs-client#1183]
Hi i'm trying this sample out.

Generated my Google API Web Client credential, with my redirect url to https://xxxxxx.ngrok.io

Then downloaded JSON and renamed to oauth2.keys.json in samples folder.

When i run node oauth2.js, i'm directed to a website and am prompted to login to a google account. the above error occurs.

Any idea how to solve?

**Comment by JustinBeckwith** [comment]
Greetings!  What does the web-client credential look like?  Can you post your JSON file with the keys all `***`'d out?

**Comment by aarontanzk** [comment]
{"web":{"client_id":"XXXXX.apps.googleusercontent.com","project_id":"XXXX","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"XXXX","redirect_uris":["https://XXXX.ngrok.io"]}}

**Comment by aarontanzk** [comment]
I'm running a dialogflow fulfilment server on ngrok

UPDATE 24 may:

after logging into google account:

Headers { "host": "xxxx.ngrok.io", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/xx.x.xxxx.xxx Safari/537.36", "accept": "image/webp,image/apng,image/,/*;q=0.8", "referer": "https://xxxxxxx.ngrok.io/?code=xxxxxxxxxxxxxxxxxxxxxxxxx", "accept-encoding": "gzip, deflate, br", "accept-language": "en-GB,en-US;q=0.9,en;q=0.8", "x-forwarded-proto": "https", "x-forwarded-for": "xxx.xx.xx.xxx" }

TypeError: Cannot read property 'payload' of undefined at getRequest (/Users/xxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/conv.js:30:45) at new DialogflowConversation (/Users/xxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/conv.js:37:22) at Function. (/Users/xxxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:113:24) at Generator.next () at /Users/xxxxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:22:71 at new Promise () at __awaiter (/Users/xxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:18:12) at Function.handler (/Users/xxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:84:16) at Object. (/Users/xxxxxx/Desktop/facts/functions/node_modules/actions-on-google/dist/assistant.js:55:32) at Generator.next ()

**Comment by JustinBeckwith** [comment]
This now looks to be unrelated to this library.  I'd suggest stopping by https://github.com/actions-on-google/actions-on-google-nodejs for help with that one :)  Let me know if this should be re-opened!
