### ISSUE TITLE
Google + API

### ISSUE THREAD

**Issue by ephrondharma** [google/google-api-nodejs-client#1184]
Can give the sample Google+ API ?

<your detailed question and code samples go here>

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  We have a sample of using the Google+ API to create a post here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/plus/post.js

If there's anything more specific you'd like..... let me know!

**Comment by ephrondharma** [comment]
Thanks for your reply,

I am using node v8.10.0 and I have Google plus user access token, I want to post images and videos with content to Google+ user profile, How to do this ?

I have installed google-api-nodejs-client and I dont want Ouath because I already created access token from another website.

Can you please advice.
