### ISSUE TITLE
31.0.0 has empty NPM package

### ISSUE THREAD

**Issue by dboune** [google/google-api-nodejs-client#1186]
Hi!

Just updated to 31.0.0, and the package seems to be mostly empty.

Only three files appear in the root of the package.

> README.md
> node_modules
> package.json

Indeed, the build folder is not in the package.
https://registry.npmjs.org/googleapis/-/googleapis-31.0.0.tgz

Thanks!

**Comment by JustinBeckwith** [comment]
Yeah, I totally broke that 😦 Taking a look now.

**Comment by SebastianEdwards** [comment]
Think this still needs to be republished to NPM?
