### ISSUE TITLE
Version 31.0.1 is not on npm

### ISSUE THREAD

**Issue by AdriVanHoudt** [google/google-api-nodejs-client#1189]
`$ npm info googleapis versions` does not show 31.0.1 for me

**Comment by ziudeso** [comment]
Same here!

**Comment by Pietro89** [comment]
on version 31.00 cannot find module after npm install googleapis

**Comment by eduardoewgo** [comment]
@Pietro89 use npm install googleapis@30.0.0 for now.

**Comment by JustinBeckwith** [comment]
Greetings folks!  We just published 31.0.2, which took care of the issue.  Apologies!
