### ISSUE TITLE
javascript - gmail.users.messages.list() Bad Request

### ISSUE THREAD

**Issue by erwin16** [google/google-api-nodejs-client#1190]
"firebase-admin": "~5.12.0",
    "firebase-functions": "^1.0.1",
    "googleapis": "^30.0.0"

I am trying to test the Gmail APi users.messages.list() using server-server authentication ( from default App Engine service account in PROJECT:  'chocha-dev'  

        `function gMailListUserMessages (user_email) {
          // Create a new JWT client using the key file downloaded from the Google Developer Console
          return google.auth.getClient({
            keyFile: path.join(__dirname, 'service-key.json'),
            scopes: 'https://mail.google.com/'
          }).then(client => {

              // Obtain a new gmail client, making sure we pass along the auth client
              const gmail = google.gmail({
                version: 'v1',
                auth: client
              });

              // Make an authorized request to list User Messages
              return gmail.users.messages.list({
                userId: 'admin@mygsuiteorganisation.org' . -< also tried with 'me'
              });

          }).then(res => res.data);
        }`

        getting  400 - "Bad Request"

Note:   This piece of code runs well with Drive API

        `function googleDriveFilesList () {
          // Create a new JWT client using the key file downloaded from the Google Developer Console
          return google.auth.getClient({
            keyFile: path.join(__dirname, 'service-key.json'),
            scopes: 'https://www.googleapis.com/auth/drive.readonly'
          }).then(client => {
              // Obtain a new drive client, making sure you pass along the auth client
              const drive = google.drive({
                version: 'v3',
                auth: client
              });

              // Make an authorized request to list Drive files.
              return drive.files.list();
          }).then(res => res.data);
        }`

debugging info ... 

**console.log(client)**

        ` client:  JWT {
          domain: null,
          _events: {},
          _eventsCount: 0,
          _maxListeners: undefined,
          transporter: DefaultTransporter {},
          credentials: { refresh_token: 'jwt-placeholder', expiry_date: 1 },
          certificateCache: null,
          certificateExpiry: null,
          refreshTokenPromises: Map {},
          _clientId: undefined,
          _clientSecret: undefined,
          redirectUri: undefined,
          authBaseUrl: undefined,
          tokenUrl: undefined,
          eagerRefreshThresholdMillis: 300000,
          email: 'chocha-dev@appspot.gserviceaccount.com',
          keyFile: undefined,
          key: '-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhk....W0DLh6iF4w==\n-----END PRIVATE KEY-----\n',
          scopes: 'https://mail.google.com/',
          subject: undefined,
          additionalClaims: undefined,
          projectId: 'chocha-dev' }`

        **console.log(gmail)**

            `gmail:  Gmail {
          root: [Circular],
          _options:
           { auth:
              JWT {
                domain: null,
                _events: {},
                _eventsCount: 0,
                _maxListeners: undefined,
                transporter: DefaultTransporter {},
                credentials: [Object],
                certificateCache: null,
                certificateExpiry: null,
                refreshTokenPromises: Map {},
                _clientId: undefined,
                _clientSecret: undefined,
                redirectUri: undefined,
                authBaseUrl: undefined,
                tokenUrl: undefined,
                eagerRefreshThresholdMillis: 300000,
                email: 'chocha-dev@appspot.gserviceaccount.com',
                keyFile: undefined,
                key: '-----BEGIN PRIVATE KEY-----\nMIIEvA.....h6iF4w==\n-----END PRIVATE KEY-----\n',
                scopes: 'https://mail.google.com/',
                subject: undefined,
                additionalClaims: undefined,
                projectId: 'chocha-dev' } },

          google:
           GoogleApis {
             _discovery: Discovery { transporter: DefaultTransporter {}, options: [Object] },
             auth:
              AuthPlus {
                checkIsGCE: undefined,
                jsonContent: [Object],
                cachedCredential: [Object],
                _cachedProjectId: null,
                keyFilename: '/Users/yves/Developments/...../functions/service-key.json',
                scopes: 'https://mail.google.com/',
                JWT: [Function: JWT],
                Compute: [Object],
                OAuth2: [Object] },
             _options: {} },

          users:
           Resource$Users {
             root: [Circular],
             drafts: Resource$Users$Drafts { root: [Circular] },
             history: Resource$Users$History { root: [Circular] },
             labels: Resource$Users$Labels { root: [Circular] },
             messages: Resource$Users$Messages { root: [Circular], attachments: [Object] },
             settings:
              Resource$Users$Settings {
                root: [Circular],
                filters: [Object],
                forwardingAddresses: [Object],
                sendAs: [Object] },
             threads: Resource$Users$Threads { root: [Circular] } } }`

**Comment by erwin16** [comment]
seems I should not use :  google.auth.getClient)  but rather create a new jwtClient, onst jwtClient = new google.auth.JWT) myself then authorize') it before accessing the gmail.users.messages.list()

here is the up and running code 👍 

    `        function gMailListUserMessages (user_email) {

          // Create a new JWT client using the key file downloaded from the Google Developer Console
          const jwtClient = new google.auth.JWT(
            google_key.client_email,
            null,
            google_key.private_key,
            ['https://mail.google.com/'], //full access for now, we can restrict more
            user_email // subject (or sub)
          );

          return jwtClient.authorize().then(tokens => {
              // Obtain a new gmail client, making sure we pass along the auth client
              const gmail = google.gmail({
                version: 'v1',
                auth: jwtClient
               });

              //Make an authorized request to list User Messages
              return gmail.users.messages.list({
                userId: user_email
              });
          }).then(res => res.data);
        }
`

using the latest version :  "googleapis": "^31.0.2",

**Comment by AnthonyDugarte** [comment]
I was struggling with this, your approach also worked for me. Thanks, mate!
