### ISSUE TITLE
VISION OCR

### ISSUE THREAD

**Issue by udhaymanhas** [google/google-api-nodejs-client#1203]
Can a sample for this be added?
https://vision.googleapis.com/v1/images

**Comment by JustinBeckwith** [comment]
Greetings!  You really don't want to use this library for that :) You want to follow the guide here:
https://cloud.google.com/vision/docs/libraries#client-libraries-install-nodejs

And there are tons of great samples here:
https://github.com/googleapis/nodejs-vision/tree/master/samples

Hope this helps!
