### ISSUE TITLE
GDPR delete user from google firebase analytics (not DB)

### ISSUE THREAD

**Issue by kalitas** [google/google-api-nodejs-client#1205]
I would like to delete user from analytics of firebase i saw that this api is supported by:https://developers.google.com/analytics/devguides/config/userdeletion/v3/
Thanks!

**Comment by kalitas** [comment]
if it is possible to get user data (GDPR requires to send the user all of his data) if requested.

**Comment by JustinBeckwith** [comment]
Greetings! For any GDPR + Firebase stuff, I would start here:
https://firebase.google.com/support/privacy/

Alternatively, it's worth following up with our friends over in https://github.com/firebase/firebase-admin-node :)

**Comment by kalitas** [comment]
so i guess this:https://developers.google.com/analytics/devguides/config/userdeletion/v3/ wont be include in your nodejs SDK?
