### ISSUE TITLE
can be removed

### ISSUE THREAD

**Issue by den4is** [google/google-api-nodejs-client#1210]
solved, remove

**Comment by den4is** [comment]
Sorry, but what does triage me mean? @JustinBeckwith

**Comment by den4is** [comment]
Updated the code to this but still doesn't work;
[![Screenshot from Gyazo](https://gyazo.com/a492e1cedb155fcf39fbe142e6eb265d/raw)](https://gyazo.com/a492e1cedb155fcf39fbe142e6eb265d)

**Comment by den4is** [comment]
Updated my route to this but it still does not work!

[![Screenshot from Gyazo](https://gyazo.com/e29c7a90ab99457d594e113bc79900a0/raw)](https://gyazo.com/e29c7a90ab99457d594e113bc79900a0)

**Comment by den4is** [comment]
bump :/

**Comment by JustinBeckwith** [comment]
Greetings!  Are you 100% sure this route is getting hit after you log in?  Can you add a `console.log(req.query)` at the beginning of your route, just to get a good idea of what's happening?

If the value of `req.query.code` is undefined or null, this is never going to work :)
