### ISSUE TITLE
Issue with returning presentationId in slides API

### ISSUE THREAD

**Issue by winappsdandandandan** [google/google-api-nodejs-client#1213]
Hi,

I am trying to use the slides API with node on cloud functions. There seems to be an issue with the response that the slides api is returning. There seems to be no "presentationId" in the response body.

``` javascript
return new Promise((resolve, reject) => {
	slides.presentations.create({
		auth: oauth2Client,
		title: "test preso",
	}, (err, presentation) => {
		if (err) {
			console.log(err);
		}
		else {
			resolve(presentation);
		}
	})
})
.then(function(presentation){
	console.log(presentation.presentationId);
})
```
The console log return >> undefined
EDIT: Just to clarify, the presentation gets created in my drive, but there is no presentationId in the response json. 

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  You can really simplify all of this :)  We now return promises by default, so you don't have to do your own promise wrapping.  

```js
async function main() {
  const res = slides.presentations.create({
    auth: oauth2Client,
    title: "test preso"
  });
  console.log(res.data);
  return res.data;
}

main().then(p => {
  console.log(p.presentationId);
}).catch(console.error);
```

Hope this helps!
