### ISSUE TITLE
NodeJS sheets API Proto field error

### ISSUE THREAD

**Issue by SimonScheerlynck** [google/google-api-nodejs-client#1220]
I am trying to create a Google Spreadsheet using a NodeJs backend and the Google APIs.
I was following this tutorial (https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/create
). However when i create the file using some specified properties, I always get the following error: Error: Invalid JSON payload received. Unknown name "title" at 'spreadsheet.properties': Proto field is not repeating, cannot start list. In the tutorial nothing is mentioned about a Proto field. Is this a bug or am I missing something?

Creating the file does work without any properties, however the properties are used to set a name for the file and the sheets so I do need a way to include this.

Thanks!

**Comment by SimonScheerlynck** [comment]
To further clarify, I have implemented the updateSheetProperties correctly. However the updateSpreadsheetProperties stiil gives the same error as before. Any idea how this is possible?

**Comment by JustinBeckwith** [comment]
Greetings!  I'd be happy to take a look. Can you please share the relevant code?

**Comment by JustinBeckwith** [comment]
Greetings!  If you can provide a code snippet, we'd be happy to check it out.  I'm going to close this out for now.
