### ISSUE TITLE
Analytics v4 batchGet: should we use requestBody or not?

### ISSUE THREAD

**Issue by maxcorbeau** [google/google-api-nodejs-client#1221]
**The code samples use `requestBody`:**

https://github.com/google/google-api-nodejs-client/blob/master/samples/analyticsReporting/batchGet.js
```
  analyticsreporting.reports.batchGet({
    requestBody: {
      reportRequests: [{
```

**The official documentation doesn't:**

https://developers.google.com/analytics/devguides/reporting/core/v4/samples

```
api.client.analyticsreporting.reports.batchGet( {
  "reportRequests":[
  {
```

**Q1: Which one should we use?
Q2: Can code samples in official documentation / github be aligned please?**

Many thanks.

**Comment by maxcorbeau** [comment]
Another variation on the same theme with **resource**:

https://github.com/google/google-api-nodejs-client/issues/561#issuecomment-344887935

```
{
resource:{
  "reportRequests":[
  {
```

My feedback having worked with the various Google APIs with nodejs over the last few years: **the documentation is all over the place**.

My advise would be:

- Keep only code samples from the repository and create tests with them so we know they work
- Remove code samples from the documentation website and point to the Github code samples instead

That way we only have 1 version of the samples and we know what version works

**Comment by JustinBeckwith** [comment]
Greetings!  The samples in this repo will always be the most up to date.  They're also tested :) The winner is:

https://github.com/google/google-api-nodejs-client/blob/master/samples/analyticsReporting/batchGet.js

The official docs you were looking at are pointing out JavaScript docs which sadly...  are different from the node.js docs (at the moment).  I hope this helps!
