### ISSUE TITLE
cannot create a file

### ISSUE THREAD

**Issue by kutlaykural** [google/google-api-nodejs-client#1223]
Hello,
Is there any other issue i have to take care while creating file, other than identifying scope?
`const SCOPES = ['https://www.googleapis.com/auth/drive.file'];`

The code for listing files is working fine.
`drive.files.list`

But the code creating file not works
`drive.files.create`

Thanks!

**Comment by mattwhisenhunt** [comment]
Create requires 3 scopes:
```
['https://www.googleapis.com/auth/drive',
'https://www.googleapis.com/auth/drive.file'
'https://www.googleapis.com/auth/drive.appdata']
```


https://developers.google.com/drive/api/v3/reference/files/create#auth

**Comment by kutlaykural** [comment]
Thank you for response. 
Yes i see the document i also tried this combination but it does not worked for me.
Here is my code for listing existing file list and it works:

`const drive = google.drive({version: 'v3', auth});        
        drive.files.list({
          pageSize: 10,
          fields: 'nextPageToken, files(id, name)',
        }, (err, {data}) => {
          if (err) return console.log('The API returned an error: ' + err);
          const files = data.files;
          if (files.length) {
            console.log('Files:');
            files.map((file) => {
              console.log(`${file.name} (${file.id})`);
            });
          } else {
            console.log('No files found.');
          }
        });`

But create file not works because of 'Error: Insufficient Permission' 
here is code:

`var fileMetadata = {
          'name': 'My Report',
          'mimeType': 'application/vnd.ms-excel'
        };
        var media = {
          mimeType: 'application/vnd.ms-excel',
          body: fs.createReadStream('employee.xlsx')
        };
        drive.files.create({
          resource: fileMetadata,
          media: media,
          fields: 'id'
        }, function (err, file) {
          if (err) {
            // Handle error
            console.error(err);
          } else {
            console.log('File Id:', file.id);
          }
        });`

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  How are you initializing your auth client?  Is this oauth2 or JWT?
