### ISSUE TITLE
Invalid non-string/buffer chunk error while downloading

### ISSUE THREAD

**Issue by kutlaykural** [google/google-api-nodejs-client#1225]
Hello everyone;

I am trying to download a file with following this document:
https://developers.google.com/drive/api/v2/manage-downloads

But it gives error: 
`TypeError: Invalid non-string/buffer chunk`

Here is my code part downloading:
```js
drive.files.get({ //png
          fileId: fileId,
          alt: 'media'
        }, function(err, result) {
          if(err) {
            // Handle error
            console.log(err);
          } else {
            var ostream = fs.createWriteStream("example.png");
            ostream.write(result);
          }
        })
```

is there anybody have any idea?

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  You need to set the `responseType` to `stream`.  See the example here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/download.js

Hope this helps!

**Comment by kutlaykural** [comment]
@JustinBeckwith  thank you for response. But not worked for me.

**Comment by kutlaykural** [comment]
And also tried this. But it was not work too.

```js
 drive.files.export({
    fileId: fileId,
    mimeType: 'application/x-vnd.oasis.opendocument.spreadsheet',
    responseType: 'stream'
  },function (err, response) {
    if (err) {
      console.log(err)
      return 
    }
    var ostream = fs.createWriteStream('export.xlsx');
    ostream.write(response.data);
    return
  })
```

**Comment by Mk-Etlinger** [comment]
@kutlaykural You need to wrap your responseType in brackets, like so:

`{responseType: 'stream'}`

Not sure why honestly, but if you look at the example again, it does it that way.

**Comment by JustinBeckwith** [comment]
Yup :)  Let me know if this is still an issue!
