### ISSUE TITLE
Error using the google plus/post sample.

### ISSUE THREAD

**Issue by alator21** [google/google-api-nodejs-client#1228]
I'm trying to run the plus/post sample but i'm getting an error:

> UnhandledPromiseRejectionWarning: Error: No access, refresh token or API key is set.

Steps i did:
Created and renamed a credentials file(oauth2.keys.json).I placed that in the samples folder.
Called the function runSample at the end of the file (post.js).
`runSample()`
I googled about it a bit and i found references [here](https://github.com/google/google-api-nodejs-client/issues/894) and [here](https://github.com/google/google-api-nodejs-client/issues/672) but i can't make it work. Thanks in advance.

**Comment by JustinBeckwith** [comment]
Greetings!  Sorry that you're having trouble putting this together.  It would be *super* helpful if you could share a github repo with your code so I can poke around and see what's up.  That error message almost always means that there's a problem with finding your keyfile. 

A few questions:
- Are you storing `oauth2.keys.json` in the `samples` directory?
- Are you downloading keyfile from the cloud developers console?
- In the `google-api-nodejs-client` directory, have you run `npm link && npm link googleapis`?

Thanks!
