### ISSUE TITLE
sampleClient file gmail

### ISSUE THREAD

**Issue by webmobiles** [google/google-api-nodejs-client#1250]
hello 
in this url example:
https://github.com/google/google-api-nodejs-client/blob/master/samples/gmail/send.js

there is a requiere to sampleClient file, but i don't know from where find that

I've followed this procedure accord to this link:
https://developers.google.com/gmail/api/quickstart/nodejs

and i have the token.json file  ( I've give credentials.json file like source)
but i dont know how to link token.json file with this sample

thanks

**Comment by duesXMachine** [comment]
When you run `node ./samples/gmail/send.js ` a server is created listening on port 3000.When you get authorization token just make a GET request to your own local server with browser.
Like `localhost:3000/oauth2callback?code={authorizationCode}`.
