### ISSUE TITLE
wrong version on quickstar page, produce  error 'raw' RFC822 payload

### ISSUE THREAD

**Issue by webmobiles** [google/google-api-nodejs-client#1253]
on page:

https://developers.google.com/gmail/api/quickstart/nodejs

the docs say to install version 27:

npm install googleapis@27 --save

I was getting error  'raw' RFC822 payload ...'

after to uninstall and install the new version 32

npm install googleapis --save

all is working well, please correct the guide and delete "@27" part

thanks

**Comment by JustinBeckwith** [comment]
Greetings!  We tend to track updates to developers.google.com on our other issue tracker.  I created a bug here:
https://issuetracker.google.com/112509526

You can track updates over there!  FYI @grant.
