### ISSUE TITLE
Setting global level auth issue

### ISSUE THREAD

**Issue by starcraft0429** [google/google-api-nodejs-client#1259]
I was gonna make authentication with clientID and client secret.
but it return error like below.
"Error: No access, refresh token or API key is set."

here is my code.

```js
const {google} = require('googleapis');

const oauth2Client = new google.auth.OAuth2(
  'xxx',
  'xxx',
  'http://localhost:3000/oauth2callback'
);

// set auth as a global default
google.options({
  auth: oauth2Client
});

module.exports.create = function(email){
    const calendar = google.calendar('v3');
    
    return new Promise((resolve, reject)=>{
        try {
            calendar.calendars.insert({
                resource :{
                    summary: email
                }
            }, (err, resp) => {
                if (err){
                    console.log('The API returned an error: ' + err);
                    reject(err)
                } 
                resolve(resp);
            });
        } catch (err) {
            return console.log(err);
        }
    })
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  You need to go through an OAuth2 authentication flow to authenticate your users.  You can find a good e2e example of this in the samples:

https://github.com/google/google-api-nodejs-client/tree/master/samples

Specifically, checkout `sampleClient.js` :)  You can also read a whole bunch on authentication and how it works here:
https://github.com/google/google-auth-library-nodejs

Hope this helps!
