### ISSUE TITLE
NPM package does not match whats in github for oauth

### ISSUE THREAD

**Issue by juniorfoo** [google/google-api-nodejs-client#1268]
The interface listed below is exported in github but not in the d.ts. Forgive me if I am missing something here.

https://github.com/google/google-api-nodejs-client/blob/v32.0.0/src/apis/oauth2/v2.ts
```
export interface Schema$Userinfoplus
```

But in the produced v2.d.ts
```
interface Schema$Userinfoplus
```

**Comment by JustinBeckwith** [comment]
Greetings!  Interesting observation.  I believe this is fine, because the entire enclosing namespace is exported.  That means all of the interfaces are available :)  Try this!

```js
import {google, oauth2_v2} from 'googleapis';
const oauth2 = google.oauth2('v2');
const foo = {} as oauth2_v2.Schema$Userinfoplus;
```

Seems to "work on my machine" :)

Let me know how it goes!

**Comment by juniorfoo** [comment]
Working, thank you sir!
