### ISSUE TITLE
How to disable Grant permissions screen

### ISSUE THREAD

**Issue by pairmix** [google/google-api-nodejs-client#1276]
I want to send emails in background and i need refresh token.
Here is an example code that helped me:
https://github.com/google/google-api-nodejs-client/blob/master/samples/oauth2.js

But don’t understand how to disable granting permission screen.

I want to send email in background, server side so my user don’t have to view such a screen, i want automatic validation.
What's the correct way to do this?
Can you tell me how to do this?

David

**Comment by JustinBeckwith** [comment]
Greetings!  You're not going to be able to disable the grant permission screen - this is just part of the OAuth2 spec, and is there to inform users what your application is trying to do.  What you *can* do is come up with a model where users sign up for your service, store the refresh token, and then perform actions on their behalf in the background.

The flow would be something like:
1. User signs up for your service.  You redirect them to the consent dialog via `generateAuthUrl`.  
2. The user signs in, and grants permission to your application to send email on their behalf (assuming you pass the right scopes.
3. Access and Refresh tokens are sent back to your application to the redirect URI.  You can store the refresh token that comes back, but make sure to do it securely :)  
4. Any time you want to send an email, set the refresh token on the OAuth2 client, and it will automatically fetch access tokens for you. 

A lot of the flow I just described gets into the details of the OAuth2 client, so I would suggest reading up the docs and checking out the samples available here:
https://github.com/google/google-auth-library-nodejs

If you have any issues - let me know!

**Comment by pairmix** [comment]
Hi @JustinBeckwith , thank you very much, i'm going to do like so.
Just few more questions:
1- I dont' want my application to send email on user behalf (maybe they don't have gmail account), i want my application send email with MY gmail account to my client emails. 
Do they still have to grant this permission screen?

2- I'm going to use getAuthenticatedClient() (https://github.com/google/google-auth-library-nodejs).
Is this method that opens grant premission dialog is stored client side (ionic) or server side (express API) ?

3-I think /oauth2callback is server side url but how can i configure cors to accept this request , what url use google to send this request ? 

Thank you anyway for your great help, Oauth2 is used everywhere now so after that i will be able to connect easily my application to facebook or instagram for example, they use same process.

David

**Comment by JustinBeckwith** [comment]
> I dont' want my application to send email on user behalf (maybe they don't have gmail account), i want my application send email with MY gmail account to my client emails. Do they still have to grant this permission screen?

Nope!  *You* will have to do this once.  After you've approved the app to have these permissions against your account, other users don't have anything to approve. 

> I'm going to use getAuthenticatedClient() (https://github.com/google/google-auth-library-nodejs).
Is this method that opens grant premission dialog is stored client side (ionic) or server side (express API) ?

That's not going to work for you.  That method assumes you're using service<-->service auth credentials.  It's *possible* you can generate a service account credential and just use that with gmail, but I think you need to be a GSuite customer for that to work.  You need to follow a flow similar to what's available in [`sampleclient`](https://github.com/google/google-api-nodejs-client/blob/master/samples/sampleclient.js)

> I think /oauth2callback is server side url but how can i configure cors to accept this request , what url use google to send this request ?

If your app is purely on the client side - it may be worth taking a look at this:
https://developers.google.com/api-client-library/javascript/start/start-js
