### ISSUE TITLE
Please add V3 to Google Jobs

### ISSUE THREAD

**Issue by nwkeeley** [google/google-api-nodejs-client#1292]
Using version latest version 32.0.0 here: https://www.npmjs.com/package/googleapis

Documentation / Code example states that we should be using V3 of the api here: https://cloud.google.com/talent-solution/job-search/docs/before-you-begin

After installing googleapis and trying the example snippet I get

```
Error: Unable to load endpoint jobs("v3"): ctr is not a constructor
    at Object.getAPI (/Users/me/Sites/match/node_modules/googleapis/build/src/shared/src/apiIndex.js:37:15)
    at GoogleApis.jobs (/Users/me/Sites/match/node_modules/googleapis/build/src/apis/jobs/index.js:22:18)
    at google.auth.getApplicationDefault (/Users/me/Sites/match/utils/company.js:21:35)
    at /Users/me/Sites/match/node_modules/google-auth-library/build/src/auth/googleauth.js:179:45
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Further investigation has shown me that in  /node_modules/googleapis/build/src/apis/jobs/index.js has specified: 

```
exports.VERSIONS = {
    'v2': v2_1.jobs_v2.Jobs,
};
```

Please include support for v3.

Thanks!

**Comment by JustinBeckwith** [comment]
We just need to run the generator.  @kinwa91 maybe you could take a crack at this :)  

Just run `make generate`, `make fix`, then submit a PR with the changes!

**Comment by tetreault** [comment]
@JustinBeckwith @kinwa91 has this been resolved yet, I just discovered this one? I actually fixed my first issue of usign the nodejs module with AWS Lambda for a job searching API i'm building because I wasn't uploading and pointing to the JSON file for `GOOGLE_APPLICATION_CREDENTIALS`. Now the module can implicitly verify my credentials in the lambda script, but now I have the same issue as the OP of this issue: 

```
{
  "statusCode": "400",
  "body": "Unable to load endpoint jobs(\"v3\"): ctr is not a constructor",
  "headers": {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
    "Access-Control-Allow-Credentials": true
  }
}
```

I see this [PR](https://github.com/google/google-api-nodejs-client/pull/1299) is open. I understand its Sunday and you're probably busy so I'm curious how I can make this work on my end if the PR is going to take some time to integrate. 

Thanks for your time!

**Comment by tetreault** [comment]
Even though `v2` is deprecated, I can probably just switch to V2 in my code to carry out building the API until v3 is integrated I assume.

**Comment by tetreault** [comment]
Sorry for one last message on this thread, its unclear to me if this is related to me using v2 for right now but in Cloudwatch I see this spit out by the node module when trying to use v2: 

```
  google.auth.getApplicationDefault((err, authClient) => {
    if (err) {
      console.error("Failed to acquire credentials");
      console.error(err);
      done(err, null);
    }
    // rest of code here
```

This `err` block triggers. Is this not the appropriate way to load in the JSON file in something serverless like Lambda with this module?

<img width="1121" alt="screenshot 2018-08-19 11 36 33" src="https://user-images.githubusercontent.com/5934354/44310438-460cad00-a3a4-11e8-9cdb-b2c703fceacc.png">

**Comment by JustinBeckwith** [comment]
Greetings folks - this is out!

**Comment by tetreault** [comment]
awesome thanks @JustinBeckwith !

Sadly, our client ended up cancelling the project I needed this for but its awesome that you've been so prompt and helpful.

**Comment by nwkeeley** [comment]
Thank you for updating with V3!!!
