### ISSUE TITLE
Using async/await on googleapi libraries return undefined

### ISSUE THREAD

**Issue by hainguyents13** [google/google-api-nodejs-client#1302]
Please help, here is the codes:
``` javascript
OAuth2Client.setCredentials(tokens)
const oauth2 = google.oauth2({ version: "v2", auth: OAuth2Client })
const userinfo = await oauth2.userinfo.v2.me.get({})
console.log(userinfo)
```
userinfo is `undefined` in console log and either some other libraries are.
I'm using `googleapis@32.0.0` and `nodejs@8.0.0`

this has accidentally happened, it was running well yesterday...
Is it a bug or am I doing something wrong?

**Comment by Ilchuk-Mihail** [comment]
@hainguyents13 
I have the same issue (   What is wrong ?

**Comment by JustinBeckwith** [comment]
This usually happens when you're using a *super* old version of the library :) Can you check that you're on version 40?

**Comment by Ilchuk-Mihail** [comment]
Yes you are right, I had old version.  Updated to v.40 and everything ok. 
Thanks.
