### ISSUE TITLE
Refresh token automatically on HTTP 401 or 403 response?

### ISSUE THREAD

**Issue by bradvogel** [google/google-api-nodejs-client#261]
I'm using the API (v1.0.10) in the following way:

```
    var oauth2Client = new OAuth2(getGoogleCredentials().clientId, getGoogleCredentials().secret);
    oauth2Client.setCredentials({
      access_token: user.services.google.accessToken,
      refresh_token: user.services.google.refreshToken
    });
    calendar.events.list({
        calendarId: 'primary',
        auth: oauth2Client
      }, ...);
```

When my token is expired I get an HTTP 401 back from the server. However, I'd expect the library to automatically refresh my token and make the request again. It doesn't.

I figured out that a workaround is to add the `expiry_date` when calling setCredentials, e.g.

```
oauth2Client.setCredentials({
      access_token: user.services.google.accessToken,
      refresh_token: user.services.google.refreshToken,
      expiry_date: user.services.google.expiresAt
    });
```

But this isn't mentioned in the docs. I'd expect `expiry_date` to be optional and the API to auto refresh the token.

**Comment by vladmiller** [comment]
So is there any event I can listen and refresh token automatically?

**Comment by zoellner** [comment]
I ran into a similar issue. What works for me is to set expiry_date to true when setting the credentials and I don't have a date availble. This will force a token refresh, you can then store the client's expiry_date after using it.
```
    oauth2Client.setCredentials({
      access_token: user.google.accessToken,
      refresh_token: user.google.refreshToken,
      expiry_date: true
    });
```

**Comment by irisSchaffer** [comment]
As this issue is not closed yet, I thought I'd ask for an update on the matter. As discussed before, the token is not automatically refreshed, when sending both the `refresh_token` and the `access_token` and as @zoellner suggested, adding `expiry_date: true` solves this problem. However, in the documentation ([`README.md`](https://github.com/google/google-api-nodejs-client/blob/master/README.md)) it says: 

>You can start using OAuth2 to authorize and authenticate your requests to Google APIs with the retrieved tokens. If you provide a refresh_token and the access_token has expired, the access_token will be automatically refreshed and the request is replayed.

So you might want to update that.

**Comment by shadowhorst** [comment]
Spent the last hour debugging my code because of the misleading Readme.md :( You should fix this.

**Comment by njcaruso** [comment]
Please update the readme.md.  As was pointed out by the last two posters, the readme is wrong.  The access_token is NOT automatically refreshed.  Thanks above for the tip on `expiry_date: true`.

**Comment by lirbank** [comment]
Actually, setting `expiry_date: true` is forcing a refresh of the access token on every request, which probably is not what you want. 

A better work around is to store the `expiry_date` the API is returning and including it in the following requests. That will make the auto-refresh work, while only refreshing the access token when needed (instead of on every request).

Eg, something like:

```js
const oauth2Client = new OAuth2(clientId, secret, redirectUrl);
let tokens = db.getTokens();
let {access_token, refresh_token, expiry_date} = tokens;
oauth2Client.setCredentials({access_token, refresh_token, expiry_date});

let response = await gmail.users.messages.list({ userId: 'me', auth: oauth2Client });

// If a refresh occured, store the new access_token and expiry_date
if (oauth2Client.credentials.id_token) {
  console.log('Received new tokens');
  db.storeTokens(oauth2Client.credentials);
}
```

**Comment by tux-world** [comment]
@lirbank refresh token work on sockets? such as socket.io

**Comment by Maulik0923** [comment]
Hello,
How can i get access_toke and refresh_token ?

Can anyone help me??

**Comment by Maulik0923** [comment]
Can i call the calendar event(insert,update,delete) by authentication token without authorization process?

**Comment by jmdobry** [comment]
I clarified in the README.

See https://github.com/google/google-api-nodejs-client/issues/261#issuecomment-233215639 for an example.

**Comment by tnguyen14** [comment]
@jmdobry where does the initial `expiry_date` value come from?

**Comment by aduddella** [comment]
After logging into my web app  PassportJs Google Oauth2 
      oAuth2.setCredentials({
          access_tokens: user[0].access_token,
          refresh_tokens: user[0].refresh_token,
          expiry_date: true
        });

        plus.people.get({
          userId: 'me',
          auth: oAuth2
        }, function (err, response) {

          console.log(err);
          res.send(response);

        });

I am always receiving an error **[Error: No access or refresh token is set.]**

Can anyone please help me why the tokens are not set

**Comment by jmdobry** [comment]
@aduddella Here's an example of `plus.people.get`: https://github.com/google/google-api-nodejs-client/pull/690/files#diff-a88bd7f246f78d9b231774787108751f

**Comment by DBjelovuk** [comment]
@lirbank https://github.com/google/google-api-nodejs-client/issues/261#issuecomment-233215639

In contrast, the readme details the following approach:

```
oauth2client.on('tokens', (tokens) => {
  if (tokens.refresh_token) {
    // store the refresh_token in my database!
    console.log(tokens.refresh_token);
  }
  console.log(tokens.access_token);
});
```
Are both approaches fine, or is one recommended? Does `tokens` here include `expiry_date`?

**Comment by JustinBeckwith** [comment]
Greetings!  The event based approach is new, and was added after this post was originally answered :) . Both ways are fine honestly.  The nice thing about using the event is that you get notified not only when the refresh_token changes, but also when the access_token is refreshed.  The tokens returned here should return the expiry_date.

**Comment by DBjelovuk** [comment]
Cheers for the snappy response! 🍻

**Comment by pitops** [comment]
@JustinBeckwith is there a better example with using the event based approach? I mean in a fuller context. i.e do i listen to the event before making a request to youtube api for example or something?
