### ISSUE TITLE
docs: How to refresh/revoke a token

### ISSUE THREAD

**Issue by ryanseys** [google/google-api-nodejs-client#262]
As suggested by #261, we should document how to refresh the token and revoke a token in the README.

**Comment by tnguyen14** [comment]
Is there any update on this? I am seeing a token being expired (getting 401 response from the Drive api) pretty quickly (perhaps within a couple of hours). Is there any way to automatically refresh it?

**Comment by jmdobry** [comment]
Making authenticated requests: https://github.com/google/google-api-nodejs-client#making-authenticated-requests

> If you provide a `refresh_token` and `expiry_date` (milliseconds since the Unix Epoch) and the `access_token` has expired, the `access_token` will be automatically refreshed and the request is replayed

Manually refreshing an access token: https://github.com/google/google-api-nodejs-client#manually-refreshing-access-token

**Comment by tnguyen14** [comment]
@jmdobry what is the logic behind `expiry_date`? does it request with Google how long the token should be valid for? If so, is it my responsibility to refresh it manually before that date ends, or does the library automatically refresh it in the background somehow, at some time?

**Comment by jmdobry** [comment]
`expiry_date` defines when the token expires.

If you provide a `refresh_token` and `expiry_date` the library will automatically refresh the access token if it is expired.

**Comment by jmdobry** [comment]
I am not aware of any limit, nor could I find any evidence of one. However, you should probably code your app to assume tokens are rather short-lived.

**Comment by tnguyen14** [comment]
@jmdobry I tried adding the `expiry_date` property in the `credentials` object for each API call for 15 days out (`new Date()).getTime() + (1000 * 60 * 60 * 24 * 15`). However, it seems like the auth token is still expired way before that (within the same day maybe). Is there a way I could debug this?
When will the token be refreshed automatically by the library?

**Comment by Lewenhaupt** [comment]
@ryanseys if I provide the expiry_date and the access_token is expired, how do I receive the updated accessToken? Because I'm guessing I would like to store that one istead of the old expired one in my db? 

@tnguyen14 I believe I have read in the docs that the token expires in one hour.

**Comment by tnguyen14** [comment]
@Lewenhaupt thanks. if you have a reference to that doc, I'd love to take a look. It would also be good to know if there's any good way to renew this token in the background if possible.

**Comment by coderaven** [comment]
Hi, is there an update to this? I am having the same issue as @Lewenhaupt and had also think of the solution to store the updated access token instead of the expired one in the db - is there any way I can do this?
