### ISSUE TITLE
1.2.0

### ISSUE THREAD

**Issue by ryanseys** [google/google-api-nodejs-client#311]
We've gotten a lot of (non-breaking) features + lots of fixes out and released since 1.0.0... and we've nearly doubled our star count since it was released (!) I'm thinking about 1.1.0. If there's anything we're holding back on breaking that could/should be broken in 1.1.0 (for good reason of course) we'll have to figure that out before. Not sure what would like to be landed. Please use this bug to list your thoughts.

1. 4xx (401 and 403 too) responses returned as errors instead of resp?

**Comment by ryanseys** [comment]
Guess this is 1.2.0 now? haha

**Comment by JustinBeckwith** [comment]
We're about to release 3.0.0 in #532, so I think it's safe to close this :)
