### ISSUE TITLE
New example of using the Drive API  to upload an image to a specific folder?

### ISSUE THREAD

**Issue by gauntface** [google/google-api-nodejs-client#316]
After a weekend of playing around with the Drive API, I would have loved an example of how to upload an existing file (Rather than text) and place it in a specific folder.

If I were to write a simple example of this and PR it, would you be open to reviewing it and accpeting it or are the examples a base set which you aren't looking to extend with more complex demos?

**Comment by ryanseys** [comment]
Hey @gauntface ever get around to making that sample? :)
