### ISSUE TITLE
Encoding query parameters 

### ISSUE THREAD

**Issue by joewoodhouse** [google/google-api-nodejs-client#318]
I'm trying to use the Google Drive search query functionality, but it won't seem to work through the library call.

Basically I'm trying

```
drive.files.list({q: "modifiedDate>='2014-10-31T13:47:52+00:00'"},function(err){
 //...
});
```

Whilst the call works, it doesn't give me the same output as I get through using the API browser. I suspect it's something to do with how the URL is encoded. Any ideas? The response I get back looks like

```
{ kind: 'drive#fileList',
  etag: '"M4l5RvCt2StP2jOGfgyJPGdTZTc/vyGp6PvFo4RvsFtPoIWeCReyIC8"',
  selfLink: 'https://www.googleapis.com/drive/v2/files?q=modifiedDate%3E%3D\'2014-10-31T13:47:52%2B00:00\'',
  items: [] }
```

which looks approximately correct to me

**Comment by JustinBeckwith** [comment]
Greetings!  I'm pretty sure this was fixed when we moved over to axios and qs.  Let me know if you run into any more problems!
