### ISSUE TITLE
Please add YT Partner API to client

### ISSUE THREAD

**Issue by benburkhart1** [google/google-api-nodejs-client#322]
I'd submit a PR, but I'm not sure I can with the paperwork requirements.
[Removed URL]

I generated the stubs on mine and it works fine, but the way you guys do API generation, it'd be lost in subsequent regenerations since you guys don't seem to have an ad-hoc list of things that aren't in the main APIs.

**Comment by ryanseys** [comment]
Created #365 to track this addition but these specific APIs will not be added unless exposed to the default Discovery service.
