### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by wallverb** [google/google-api-nodejs-client#325]
We want to create object in the bucket with empty body.
We tried 2 approaches which both failed:

1. Empty string `""`
2. Buffer with length 0

Ad1) File `apirequest.js` has this code `if (parameters.mediaUrl && media.body)` which resolves to `false`. If you could change it to `if (parameters.mediaUrl && typeof(media.body) != 'undefined')` then it would work fine

Ad2) Unfortunately the issue is in the module `request` that google api is using. There is already open issue for that: https://github.com/request/request/issues/920

**Comment by jmdobry** [comment]
The [Google Cloud Client Library for Node.js](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/latest/storage) is now the more idiomatic way to access Cloud Storage.
