### ISSUE TITLE
Support PKCS12 to .pem conversion for JWT auth

### ISSUE THREAD

**Issue by rayshan** [google/google-api-nodejs-client#326]
Currently the [example](https://github.com/google/google-api-nodejs-client/blob/master/examples/jwt.js) ask the user to convert the `.p12` key to `.pem` before using this library. It would be nice to do this for the user by using https://github.com/digitalbazaar/forge. Here's an example of how:
https://github.com/joyent/node/issues/4050#issuecomment-40268664.

**Comment by JustinBeckwith** [comment]
This should work now!
