### ISSUE TITLE
JWT Credentials should pass in Private Key ID 

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-api-nodejs-client#328]
Private keys for JSon Web Token credentials also have a thing called a Private Key ID, a nonsecret identitifer for the private key, which can be used on the server for better performance and diagnostics. The new JSon format for Service Accounts includes this id as "privateKeyId". It should be sent in the JWT when present in the field named "kid". See the latest Java or Python implementations for reference.

**Comment by jmdobry** [comment]
I believe google-auth-library-nodejs now uses `kid`
