### ISSUE TITLE
Bug when specifying media.body and providing refresh_token that needs refreshed.

### ISSUE THREAD

**Issue by benburkhart1** [google/google-api-nodejs-client#332]
There's a bug in this client library when you try and do a file upload using the media.body property.

Here this expects the return value of authClient.request() to return something meaningful.

https://github.com/google/google-api-nodejs-client/blob/master/lib/apirequest.js#L203

Here's the actual request code, which does asynchronous callbacks, and does not return what this expects.

https://github.com/google/google-api-nodejs-client/blob/master/lib/auth/oauth2client.js#L241-L269

At the point in the first link, in my situation (provided refresh_token that needs refreshed), the returned req is 'undefined'.

**Comment by JustinBeckwith** [comment]
Greetings!  Since our switch to axios, I'm pretty sure this issue has been resolved.  If you're still having problems - please do let us know!
