### ISSUE TITLE
There is no facility for passing a proxy to the oauth2client

### ISSUE THREAD

**Issue by abrgr** [google/google-api-nodejs-client#336]
I haven't found a way to cleanly pass a proxy to the OAuth2Client.

Would you be open to a pull request that added an optional opts argument to the OAuth2Client constructor which was combined with the existing object passed to each invocation of transporter.request?  This would allow clients to set a proxy for the OAuth2Client to use without jumping through hoops patching different objects.

This would make the getToken method look like this:

```
OAuth2Client.prototype.getToken = function(code, opt_callback) {
  var uri = this.opts.tokenUrl || OAuth2Client.GOOGLE_OAUTH2_TOKEN_URL_;
  var values = {
    code: code,
    client_id: this.clientId_,
    client_secret: this.clientSecret_,
    redirect_uri: this.redirectUri_,
    grant_type: 'authorization_code'
  };

  this.transporter.request(utils.extend({}, this.opts, { // THIS IS THE PROPOSED ADDITION
    method: 'POST',
    uri: uri,
    form: values,
    json: true
  }), function(err, tokens) {
    if (!err && tokens && tokens.expires_in) {
      tokens.expiry_date = ((new Date()).getTime() + (tokens.expires_in * 1000));
      delete tokens.expires_in;
    }
    if (opt_callback) {
      opt_callback(err, tokens);
    }
  });
};
```

**Comment by Alaneor** [comment]
This library uses [request](https://github.com/request/request) under the hood, which respects proxy configuration via HTTP_PROXY or HTTPS_PROXY environment variables. Does that work for you?

**Comment by abrgr** [comment]
Sorry for the delay.  I prefer not to mess with HTTP_PROXY and HTTPS_PROXY since my environment has a few hosts that should not be proxied and I find that to be a bit painful with environment variables.  I forked and made the few small changes I mentioned: https://github.com/abrgr/google-api-nodejs-client/commit/f5d735a39a22f689923c10ef5b0f909144b69996

**Comment by ryanseys** [comment]
Oh neat. The transporter might not inherit those request options like I wanted it to. If you open a PR, I can look into landing this.

**Comment by abrgr** [comment]
Sure.  I just submitted https://github.com/google/google-api-nodejs-client/pull/363

**Comment by ryanseys** [comment]
Thanks!

**Comment by JustinBeckwith** [comment]
For future reference, you can totally do that!  
https://github.com/google/google-auth-library-nodejs#using-a-proxy
