### ISSUE TITLE
Geocoding API

### ISSUE THREAD

**Issue by IonicaBizau** [google/google-api-nodejs-client#344]
Do we have access to the geocoding APIs?

**Comment by Alaneor** [comment]
Only APIs available via the [API Explorer](https://developers.google.com/apis-explorer) are available to this library. Geocoding API does not seem to be present there.

**Comment by IonicaBizau** [comment]
Thanks, we currently use this function:

```js
/**
 * findGeocoordinates
 *
 * @name findGeocoordinates
 * @function
 * @param {String} address The textual address to get the coordinates for
 * @return {String} The position object containing lat and lng keys as numbers
 */
function findGeocoordinates(address, callback) {

    var API_URL = 'https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s';
    var API_KEY = '...';
    var url = API_URL.replace('%s', address).replace('%s', API_KEY);
    request({ url: url, json: true }, function (err, response, body) {
        if (err || response.statusCode != 200) {
            return callback('Error while trying to geocode address: ' + address);
        }

        if (!body || !body.results[0]) {
            return callback('Failed to geocode address: ' + address);
        }

        return callback(null, body.results[0].geometry.location);
    });
}
```

**Comment by ryanseys** [comment]
Yep @Alaneor is correct. This API does not support Geocoding APIs.

**Comment by jippi** [comment]
@ryanseys Any reason why geocoding is not part of these API collections? it seems like a weird omission for an official google SDK for node

**Comment by jmdobry** [comment]
Because currently this library only supports Google APIs that have been published to https://www.googleapis.com/discovery/v1/apis. The metadata for each API published to https://www.googleapis.com/discovery/v1/apis all follow the same format, making it feasible to auto-generate this library from that metadata.

**Comment by jippi** [comment]
@jmdobry alright, make sense - do you know if its planned or somewhat easy to add the outstanding api(s) - in this case the geocoding api :)

**Comment by jmdobry** [comment]
> in this case the geocoding api

None that I know of. The Maps API has its own [client libraries](https://developers.google.com/maps/web-services/client-library), but no Node.js client library. 😕
