### ISSUE TITLE
Document list api deprecation

### ISSUE THREAD

**Issue by ajduke** [google/google-api-nodejs-client#357]
I am using this npm module for google drive activities from my application

It is basically using the Listing of all Drive files of authenticated user. and file info for each drive file.
and all drive calls made from this npm module itself.

This morning, i got the email from google that i am using deprecated Document List api, and should upgrade to newer API. 

![screenshot from 2015-02-03 10 14 48](https://cloud.githubusercontent.com/assets/1594650/6014681/d85571fe-ab8e-11e4-9597-1f3cb49ee21c.png)

I was  using version`v1.0.11`  of this module. Now, i upgraded to latest version `v1.1.1`

I was wondering in latest version which is `v1.1.1` is this deprecation handled? or am i missing something.

Many thanks.

Regards,
/ajduke

**Comment by scorpwarp23** [comment]
This is a significant and important issue. Would love an update on this ASAP as it affects production apps.

**Comment by ryanseys** [comment]
Hi, no need to worry. This library doesn't use any of the URLs listed (you can search for yourself to verify), and if you're using this library to interact with Google Drive, you're already on Step 2 of that email so congrats! I would consider you look into your other libraries and ensure that they aren't using those URLs either.

**Comment by ryanseys** [comment]
Please also keep in mind that we strive our best to respond to issues as fast as possible. Also please consider this library [is in Alpha](https://github.com/google/google-api-nodejs-client#alpha) which means it is not subject to any SLA or deprecation policy. Google also reserves the right to make incompatible changes in the future when necessary. Hope you can track down your issue with the Documents List API but I can assure you it is not in this library.

**Comment by ajduke** [comment]
@ryanseys Thanks for response. much appreciated.
