### ISSUE TITLE
Using Service Token for Google Webmaster Tools does provide access

### ISSUE THREAD

**Issue by nwaltham** [google/google-api-nodejs-client#358]
Service account is correctly given access to google webmaster tools API, and delegated as an owner to the website, yet on attempt to call webmastertools.crawlerrorssamples.list with google.auth.JWT client results in error: User does not have sufficient permission for site: "x" where x is the url of  site in question

**Comment by ryanseys** [comment]
A service account is not like a regular Google Service account. You cannot use it to access resources even if you give that specific address "access" to it. See [here](https://developers.google.com/webmaster-tools/v3/how-tos/authorizing) for the different ways you can authorize your requests to the Webmaster API.

**Comment by bogdancss** [comment]
@ryanseys can you please explain how to use the webmaster api with a service account?
