### ISSUE TITLE
Not all errors passed through to error message

### ISSUE THREAD

**Issue by bradvogel** [google/google-api-nodejs-client#360]
I'm seeing a lot of errors passed back to my callbacks that include a null message. Eg:

```
{ [Error: null] code: 500 }
```

However, when examining the body of the actual HTTP response, I see that the message is actually populated:

Actual response object:
```
 {
   "statusCode": 500,
   "body": {
     "error": {
       "errors": [
         {
           "domain": "global",
           "reason": "backendError",
           "message": "Backend Error"
         }
       ],
       "code": 500,
       "message": "Backend Error"
     }
   }
 }
```

**Comment by bradvogel** [comment]
In examining the code, the bug appears to be here: https://github.com/google/google-api-nodejs-client/blob/master/lib/transporters.js#L93

The body is being set to null and then it's hitting the second `if` statement because it happens to be a 500 error.

@ryanseys Why is there a special case for 500s there? Shouldn't that be removed and just let the `if` statement above it handle the error? What about modify the line above from:

```
err.code = body.error.code;
```

to: 

```
err.code = body.error.code || res.statusCode;
```

**Comment by ryanseys** [comment]
Ah yeah looks like an issue with that if block. Should be an else if and probably contain a bit more logic so as to capture the case described in the two line comment about that block.

**Comment by bradvogel** [comment]
Cool. Filed https://github.com/google/google-api-nodejs-client/pull/361/files
