### ISSUE TITLE
Sending emails for a service account

### ISSUE THREAD

**Issue by vioz** [google/google-api-nodejs-client#362]
I want to create a service that sends an email automatically when a user hits an web api endpoint. Prompts don't make sense for this case since I'm not sending an email on behalf of the user, but on behalf of the service that the user is interacting with. 

Is it possible to auth with Google's services with this library in order to send an email on behalf of a service, thus requiring no prompts? If it is possible, are there examples available, and if not, would someone paste a small snippet to get me started?

Thank you for all of the work that has gone into this library!

**Comment by ryanseys** [comment]
Not possible. You can only auth GMail API through OAuth 2.0. Take a look here: https://developers.google.com/gmail/api/auth/about-auth
