### ISSUE TITLE
Is google places supported?

### ISSUE THREAD

**Issue by kilianc** [google/google-api-nodejs-client#364]

**Comment by ryanseys** [comment]
Nope. Supported APIs list found here: https://developers.google.com/apis-explorer/#p/

**Comment by seiyria** [comment]
Any idea when this will be supported?

**Comment by ryanseys** [comment]
Likely not in the near future. Check out https://developers.google.com/places/javascript/ for the officially supported JavaScript library for interacting with Google Places.

**Comment by seiyria** [comment]
That's a shame. I guess in the mean time I'll use [this](https://www.npmjs.com/package/googleplaces) for it. Thanks!
