### ISSUE TITLE
Add generate-apis --api-url option

### ISSUE THREAD

**Issue by ryanseys** [google/google-api-nodejs-client#365]
So we can do something like:

``` sh
node scripts/generate --api-url "https://example.com/custom/api.json"
```

Referenced from https://github.com/google/google-api-nodejs-client/issues/322

**Comment by jmdobry** [comment]
Fixed by #488 and some other commits. Currently works like this:

```
node scripts/generate [file_or_url] [file_or_url] [...]
```
