### ISSUE TITLE
Error in example code [README.md]

### ISSUE THREAD

**Issue by VikramTiwari** [google/google-api-nodejs-client#367]
Error:
ReferenceError: OAuth2 is not defined

How to replicate error:
Copy paste the code in example and run it.

Resolution:
Put missing code at line 3:
`var OAuth2 = google.auth.OAuth2;`

Ref URL: https://github.com/google/google-api-nodejs-client/#generating-an-authentication-url

**Comment by ryanseys** [comment]
Which line? Can you send a PR to fix? Thanks!

**Comment by VikramTiwari** [comment]
@ryanseys Quick response :+1:

**Comment by ryanseys** [comment]
Thanks!
