### ISSUE TITLE
drive.children.insert won't accept folderId and resource properties at the same time?

### ISSUE THREAD

**Issue by SleepyBandit** [google/google-api-nodejs-client#370]
Maybe it is simply the different ways I have been trying this, but I'm having trouble finding a clear answer online.

I've tried a number of ways like 
```
drive.children.insert(
{ folderId: '<insert id>',
     resource: {
         title: 'Test',
         mimeType: 'text/plain'
    },
    media: {
        mimeType: 'text/plain',
        body: 'Hello World updated with metadata'
    },
    auth: oauth2Client
}, function(err, response) {
    console.log('error:', err, 'inserted:', response);
});
```
but i get the following error message back
    error: { [Error: Resource metadata required] code: 400 } inserted: null

If I remove the folder Id property, then I get a different error message
    error: [Error: Missing required parameters: folderId] inserted: undefined

Am i entering something incorrectly here?  It would appear that it accepts my folder Id property, but for some reason no longer recognizes the Resource metadata.

Based on alternative issues here I've gotten the following to work, but I'd prefer to use the above if possible.
```
drive.files.insert({
    resource: {
        title: 'Test',
        mimeType: 'text/plain',
        parents: [{id: '<folder id>'}]
    },
    media: {
        mimeType: 'text/plain',
        body: 'Hello World updated with metadata'
    },
    auth: oauth2Client
}, function(err, response) {
    console.log('error:', err, 'inserted:', response);
});
```

**Comment by ryanseys** [comment]
The `resource` is the request body. So according to [the docs](https://developers.google.com/drive/v2/reference/children/insert) you'll need to do something like this:

``` js
drive.children.insert({
  folderId: 'parent-Id',
  resource: {
    id: 'child-Id'
  }
}, function(err, response) {
  console.log(err, response);
});
```

That API call does not accept media, so you'll need to upload the file using `drive.files.insert` and then move it to whatever folder you'd like using `drive.children.insert`. Or you can use your final suggested answer to do it in one call, but you mentioned you'd prefer to not use that method.

**Comment by SleepyBandit** [comment]
thanks, that makes it a lot clearer. The error message was not helping a lot in deciphering what was going on. I will just use the other method to do it in one swoop.  Appreciate the clarification.

**Comment by ryanseys** [comment]
No problem!
