### ISSUE TITLE
API key with Storage API returns null

### ISSUE THREAD

**Issue by savants** [google/google-api-nodejs-client#372]
Hello Ryan,

I was trying to follow your example for google cloud storage media upload at 

https://github.com/google/google-api-nodejs-client/blob/master/examples/mediaupload.js

I am trying to do upload from server to server as I dont want API key yo be exposed in client programming. However I am always getting null response back. Here is my code for pulling the list of buckets from Project.

var google = require('googleapis');
var async = require('async');

const gApiKey = API_KEY;
var gStorage = google.storage({ version: 'v1', auth: gApiKey });

const gApiProject = PROJECT_NAME;

exports.getBucketList= function(req, res, next) {

    var servResponse = new Object();
    servResponse.transaction = "getBucketList";

    var params = { project: gApiProject  };

    async.series(
        [
            function(callback) {

                gStorage.buckets.list(params , function (err, response) {

                    console.log('Bucket response', response);
                    servResponse.response = response;

                    callback();

                });
            }
        ],

        function done (error, results) {

            return res.send(JSON.stringify(servResponse));
        }

    );

Is there something needs to be done differently?

**Comment by ryanseys** [comment]
Try using a JWT to authenticate and not a API Key. API keys are very old and only work for specific APIs, likely not a shiny new API like Drive. 

Here's an example using JWT: https://github.com/google/google-api-nodejs-client/blob/master/examples/jwt.js

and heres more docs on it: https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens

**Comment by ryanseys** [comment]
Did this work for you?

**Comment by Joebob12** [comment]
Hmm I'm trying to understand the idea behind scope is there any more details on it @ryanseys? Currently i'm trying to authorize for the prediction api if it matters. Is there a list of the googleapis.com I would need to use some where?

**Comment by ryanseys** [comment]
Yeah the scope for that is `https://www.googleapis.com/auth/prediction`  you can find that available here: https://cloud.google.com/prediction/docs/developer-guide?hl=en

**Comment by JustinBeckwith** [comment]
Greetings folks!  There's a great NPM module for using Cloud Storage:
https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-storage

It should be a lot easier to use.  If this doesn't work for you for some reason, please feel free to re-open this issue!

**Comment by JustinBeckwith** [comment]
There's also support for using the prediction API:
https://github.com/GoogleCloudPlatform/gcloud-node#google-prediction-api
