### ISSUE TITLE
Question about backward compatibility and versioning

### ISSUE THREAD

**Issue by h2non** [google/google-api-nodejs-client#376]
In the readme I read:
```
This library is in Alpha. We will make an effort to support the library, but we reserve the right to make incompatible changes when necessary.
```

Oh, I can understand, it's fine, taking into account it's an alpha version, but from the API consumer point of view, I should be concerned about interface inconsistency across multiple `patch` versions? 
I mean, you're following, at least in a lazy way, the semantic versioning conventions in the library?

I honestly think that this package has too much responsibility and this make a bit difficult versioning it and orchestrate properly all the roadmap and therefore API features

Thanks

**Comment by ryanseys** [comment]
Fear not, we will be following semver as closely as possible. If we introduce breaking changes, we will bump minor version. Bug fixes and api regenerations will be patch bumps. A major bump is not in our immediate sights and shouldn't be necessary unless all the APIs drastically change overnight.

**Comment by h2non** [comment]
Thanks, I guess my fear disappears with your explanation. That's all. Closing
