### ISSUE TITLE
Browsable documentation for the API

### ISSUE THREAD

**Issue by h2non** [google/google-api-nodejs-client#377]
I'm looking for an easy way to navigate thought the API instead of reviewing code.

I'm sure this is already in mind, but taking into account all the code was commented following the JSdoc syntax, what about using an automatic documentation generation tool and make it available as Github page.

I really like [jsduck](https://github.com/senchalabs/jsduck) from Sencha guys

**Comment by ryanseys** [comment]
Yes this was a plan all along but never got around to finishing them and hosting them. Docs are generate-able from `npm run generate-docs` using JSDoc

**Comment by rainabba** [comment]
Tried this and got, "missing script: generate-docs"

Tried "npm install generate-docs" and it's not in the npm registry.

**Comment by JustinBeckwith** [comment]
Good news!  This was added today:

http://google.github.io/google-api-nodejs-client/2.1.7/index.html
