### ISSUE TITLE
Possible to insert a spreadsheet with multiple worksheeats?

### ISSUE THREAD

**Issue by reggi** [google/google-api-nodejs-client#378]
> Possible to insert a spreadsheet with multiple worksheeats?

I found [this documentation](https://developers.google.com/google-apps/spreadsheets/#working_with_worksheets) but there's no node support.

Sorry this is more of a question, not an issue :/

**Comment by ryanseys** [comment]
No sorry, that API is unsupported. For supported APIs, see the README here: 

https://github.com/google/google-api-nodejs-client#supported-apis

**Comment by reggi** [comment]
Thanks @ryanseys!!!!

**Comment by mrcybermac** [comment]
Are there plans to support the spreadsheet api?
