### ISSUE TITLE
Could not find the method .execute() within drive.files.get(id)

### ISSUE THREAD

**Issue by jimng** [google/google-api-nodejs-client#387]

**Comment by ryanseys** [comment]
Hi, you'll need to read the new documentation on how to migrate your code to 1.x. See the README and code examples on how to use the 1.x (or recently released 2.x) code. We no longer use `.execute()`.

Here's the migration guide which may also help: https://github.com/google/google-api-nodejs-client/blob/master/MIGRATING.md

**Comment by jimng** [comment]
Problem fixed. Thanks for your help. I should close the issue now.
