### ISSUE TITLE
auth has no method getApplicationDefault doesn't

### ISSUE THREAD

**Issue by maxs15** [google/google-api-nodejs-client#389]
An example defaultauth has been added 16 days ago by @jasonall, but the method  auth.getApplicationDefault doesn't exist in the current version 2.0.0  ?

Thanks for help

**Comment by jasonall** [comment]
This method is present in the Node module google-auth-library-nodejs, which is now linked into this library. You can find it here: https://github.com/google/google-auth-library-nodejs

**Comment by jasonall** [comment]
Actually, you are correct. This was a mistake. I sent another PR which fixes this: https://github.com/google/google-api-nodejs-client/pull/390

**Comment by maxs15** [comment]
Thanks for the fix :+1:
