### ISSUE TITLE
Errors on grunt build using google-api-nodejs-client with webpack

### ISSUE THREAD

**Issue by dmk12** [google/google-api-nodejs-client#403]
I'm using https://www.npmjs.com/package/googleapis in a ReactJS Webpack app. `npm install googleapis --save` installed it ok, added `"googleapis": "^2.0.2"` to my package.json, but when I run `grunt build` I get the following warnings (followed by lots of errors which I'll post upon request, as it is a lot of text):

    WARNING in ./~/googleapis/apis/index.js
    Critical dependencies:
    41:23-44 the request of a dependency is an expression
    @ ./~/googleapis/apis/index.js 41:23-44

    WARNING in ./~/googleapis/~/request/~/hawk/~/hoek/lib/index.js
    Critical dependencies:
    403:34-60 the request of a dependency is an expression
    @ ./~/googleapis/~/request/~/hawk/~/hoek/lib/index.js 403:34-60

Code that requires googleapis in my React component:

    var gapi = require('googleapis');

*Note: Any other code from the component can be provided on request, but I don't believe it's relevant to this issue.*

My `package.json` dependencies:

    "dependencies": {
    "aws-sdk": "^2.0.21",
    "chalk": "^0.5.0",
    "crypto-js": "^3.1.2-5",
    "cryptojs": "^2.5.3",
    "envify": "^1.2.1",
    "fluxxor": "1.5.1",
    "googleapis": "^2.0.2",
    "imports-loader": "^0.6.3",
    "jquery": "~2.1.1",
    "moment": "^2.8.3",
    "react": "0.11.1",
    "react-bootstrap": "0.12.0",
    "react-router": "0.5.2",
    "react-router-bootstrap": "0.5.0"
    },
    "devDependencies": {
    "connect-livereload": "^0.4.0",
    "css-loader": "^0.7.0",
    "es6-promise": "^1.0.0",
    "esrever": "^0.1.0",
    "grunt": "^0.4.5",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-less": "~0.11.4",
    "grunt-contrib-uglify": "^0.7.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-git": "^0.2.14",
    "grunt-gitinfo": "^0.1.6",
    "grunt-karma": "^0.8.3",
    "grunt-lesslint": "^1.1.13",
    "grunt-rsync": "^0.6.1",
    "grunt-ssh": "^0.11.2",
    "grunt-webpack": "^1.0.8",
    "jssha": "^1.5.0",
    "jsx-loader": "^0.10.2",
    "karma": "^0.12.17",
    "karma-chrome-launcher": "^0.1.7",
    "karma-coverage": "^0.2.7",
    "karma-jasmine": "^0.1.5",
    "karma-js-coverage": "^0.4.0",
    "karma-osx-reporter": "^0.1.0",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.2",
    "karma-webpack": "^1.2.1",
    "load-grunt-tasks": "^0.6.0",
    "style-loader": "^0.6.4",
    "time-grunt": "^1.0.0",
    "webpack": "^1.4.15"
    }

npm version 2.5.1

node version v0.12.1

Thanks in advance for any help!

**Comment by Alaneor** [comment]
The offending line is:

```js
var Endpoint = require(endpointPath);
```

I think it complains about not stating our dependency explicitly (as a string), but rather as a variable that needs to be evaluated first (an expression).

From architectural perspective, this is beneficial to keep the codebase flexible and will likely not be modified to avoid the warning you are getting. I think you will need to figure a way how to make your Grunt task ignore this warning or otherwise make it work...

**Comment by dmk12** [comment]
Thanks @Alaneor. One of the errors I'm getting, any thoughts on that? It seems to be missing the `fs` module, which seems to be a native nodeJS module and should be available.
    ERROR in ./~/googleapis/~/request/~/hawk/~/hoek/lib/index.js
    Module not found: Error: Cannot resolve module 'fs' in /Users/dev/wwb-web-   app/node_modules/googleapis/node_modules/request/node_modules/hawk/node_modules/hoek/lib
     @ ./~/googleapis/~/request/~/hawk/~/hoek/lib/index.js 3:9-22

**Comment by Alaneor** [comment]
Can't tell without knowing what Grunt plugin is causing it... But I have a terrible suspicion it's Browserify.

I cannot imagine how you could possibly package the `fs` module for browser.

**Comment by FriesFlorian** [comment]
@dmk12 Any chance you found a solution?

**Comment by dmk12** [comment]
@FriesFlorian No, sorry. I attributed it to the fact that the npm script is alpha, so things just don't work... :/ Ended up adding a link to googleapi to my index.html the old fashioned way.

**Comment by tdeheurles** [comment]
hi, 
It seems that this error is still present.
Does someone found a workaround in order to googleapi working with node ?

I'd like to implement some test but I block on that issue for now ...

**Comment by john-osullivan** [comment]
My team and I are using webpack (which is also using babel) as part of a combined setup of React+Meteor, and also getting this error.  Kind of a bummer, this is the only package which is throwing this sort of error on us.  We're getting both the `the request of a dependency is an expression` error and the `Cannot resolve module 'fs'` one.

@dmk12 , did loading googleapi from a script tag ever cause any issues?  Are you able to perform any operations from the server using the APIs?  We want our server-side code to interact with them, but this error is stopping us dead in our tracks.

**Comment by dmk12** [comment]
@john-osullivan No, I had no issues using a script tag whatsoever, our server API (Django/Python) is interacting with Google API just fine, mostly used for registering/login in users, so I'd say you're safe using a script tag :)

**Comment by pushtheworldllc** [comment]
Any update on this error? Still persisting over here in my Electron app with web pack :/

**Comment by cweems** [comment]
Just noting that I also encountered this issue. Ended up using a script tag instead.

**Comment by jmdobry** [comment]
google-api-__nodejs__-client is not meant to be used in a browser—it won't work. `googleapis` (google-api-nodejs-client) will work in Node.js. Excluding `googleapis` from any server-side bundle (just let Node's module system load it for you) is the best option.

To access Google APIs from a browser, please use the [Google API Client Library for JavaScript](https://developers.google.com/api-client-library/javascript/) (`gapi`).

**Comment by arufian** [comment]
+1 @jmdobry 
case closed.

by the way, in case of `fs` you can ignore it by add this codes (though not related with this issue) 
```js
node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```
