### ISSUE TITLE
Errors not clear enough

### ISSUE THREAD

**Issue by VikramTiwari** [google/google-api-nodejs-client#404]
Tried creating a table in bigquery and gave the parameters projectId and datasetId to `bq.tables.insert`

gives following error

```
{ [Error: Required parameter is missing] code: 400 } null
```

I know that i need to give various resources which correspond to the table i wanna make, but the error is not comprehensible enough. Same case with [documentation](https://cloud.google.com/bigquery/docs/reference/v2/tables/insert).

The documentation must contain details about the keys that will be used and the minimum required key-values parameters to make it work.

**Comment by Daaru00** [comment]
same problem, errors are too general and can be caused by a variety of things.

**Comment by josephg** [comment]
Yep, I just ran into the same problem. Its a developer experience issue. The response from google's REST API contains a bunch of useful information that the error object never passes to the callback. Consider what gets passed into the callback:

```javascript
{ [Error: invalid_request] code: 400 } 
```

vs what the API actually returns:

```javascript
{ error: 'invalid_request',
  error_description: 'Missing required parameter: refresh_token' }
```

**Comment by carrotalan** [comment]
+1 for this

**Comment by JustinBeckwith** [comment]
Good call!  We're going to be improving things here, and we're tracking the user input validation over in #528.  Let's use that issue instead of this one :)
