### ISSUE TITLE
Is there any example on generateAuthUrl with default access_type?

### ISSUE THREAD

**Issue by needforspeed** [google/google-api-nodejs-client#405]
I see the non offline example from https://github.com/google/google-api-nodejs-client/blob/master/examples/oauth2.js 

I'm wondering if there is a online example?

Thanks in advance.

**Comment by JustinBeckwith** [comment]
Greetings!  The options there are `online` and `offline`.  You can learn more in this doc:
https://developers.google.com/identity/protocols/OAuth2WebServer

Hope this helps!
