### ISSUE TITLE
Incorrectly URL encoding of parameters.

### ISSUE THREAD

**Issue by SamProtas** [google/google-api-nodejs-client#409]
My google custom search engine "cx" parameter has a "%" sign in it.  When using the node api-client to make a request I found the cx parameter was url encoded prior to sending the request, invalidating the request.

The "%" in my cs parameter was replaced with "%25".

I used console.log(req.uri.href) to inspect the request for debugging to determine this.

**Comment by ryanseys** [comment]
Hmm, what should it be? Just not encoded at all?

**Comment by SamProtas** [comment]
Upon further inspection I believe I copied the cx parameter from the url bar. The cx parameter originally contained a ":" (colon) which was url encoded to %3A. When copying the encoded cx parameter directly to a request or url bar this parameter still worked.

When using the google node module it assumed the raw cx parameter and further encoded what it saw. I believe this is the intended function.

**Comment by ryanseys** [comment]
Yeah we try to do the heavy lifting like encoding for you. That being said,
the API can be tricky so it's always good to watch out for these small
differences. Thanks for filing anyway! Let me know if anything else doesn't
make sense :)

**Comment by SamProtas** [comment]
Hey @JustinBeckwith, was this assigned to me for some particular reason? I have no memory of this issue, but it sounds like it was user error (my error) and requires no followup.
