### ISSUE TITLE
[TypeError: Object #<Object> has no method 'request']

### ISSUE THREAD

**Issue by james-dowell** [google/google-api-nodejs-client#410]
When using the JWTClient for the youtube api, I get the following error.. 

***[TypeError: Object #<Object> has no method 'request']***

I have traced it to the apirequest.js file line 189 (I think)..

My simple code is shown below:
----
````
var google = require('googleapis');

var jwtClient = new google.auth.JWT(
    'xxxx@developer.gserviceaccount.com',
    './key.pem',
     null,
    ['https://www.googleapis.com/auth/youtube']
);


jwtClient.authorize(function(err, tokens) {
    if (err) {
        console.log(err);
        return;
    }

    google.youtube('v3').search.list({  auth: tokens, q: 'cats', part: 'snippet' }, function (res) {
        console.log(res);
    });

});
````

I'm not sure if this is my code or if this is an actual issue with the library but any help would be greatly appreciated.

Thanks,
James

**Comment by ryanseys** [comment]
Yeah you don't give the tokens to the auth parameter, you give the entire
jwtClient object.

**Comment by james-dowell** [comment]
Ahh great thanks!
