### ISSUE TITLE
Support for new comment system

### ISSUE THREAD

**Issue by madshargreave** [google/google-api-nodejs-client#415]
Hey

I just noticed that the new youtube comment system has been released, as can be seen here

https://developers.google.com/youtube/v3/docs/commentThreads/
https://developers.google.com/youtube/v3/docs/comments

When will the node client support this?

Much appreciated

**Comment by Alex0007** [comment]
Simply regenerate apis
```
git clone ...
npm i
npm run generate-apis
```

**Comment by JustinBeckwith** [comment]
This should be taken care of with the latest release.  Thanks!

https://github.com/google/google-api-nodejs-client/blob/master/apis/youtube/v3.js#L613
