### ISSUE TITLE
JWT Client throws PEM_read_bio:no start line

### ISSUE THREAD

**Issue by manleyjster** [google/google-api-nodejs-client#418]
I'm trying to authenticate to the Fusion Tables API using the JWT client. I generated a .p12 file from `developers.google.com`, and followed the instructions [here](https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens). Whenever I try to authenticate, I get the following: `[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line]`.

I've trimmed the code down to a minimal example:
```javascript
#!/usr/bin/env node

var cwd = process.cwd(),
	google = require('googleapis');

var jwtClient = new google.auth.JWT(
	'email@developer.gserviceaccount.com',
	null,
	cwd + '/key.pem',
	['https://www.googleapis.com/auth/fusiontables'],
	'myemail@gmail.com'
);

jwtClient.authorize(function(authErr) {
	if (authErr) { throw authErr; }
});
```

I've checked - the path above is correct, and the contents of the .pem file are:
```
Bag Attributes
    friendlyName: privatekey
    localKeyID: redacted
Key Attributes: <No Attributes>
-----BEGIN PRIVATE KEY-----
redacted
-----END PRIVATE KEY-----
```

I thought this issue might have to do with an encoding issue, and I looked through some of the auth-token dependencies of this library - but adding `{ encoding: 'utf8' }` to calls to `fs.readFile` didn't fix the issue.

Any idea what might be causing this?

**Comment by manleyjster** [comment]
Resolved; I was misusing the .pem arguments.

It would be nice to make clearer in the documentation that the second argument is a path to a .pem file, that the third argument is the body of a .pem file, and that the two should not be used concurrently.

**Comment by iwarner** [comment]
For completeness - its easier to use the JSON that can also be downloaded

```
// Key
const key = require('../resources/JSON.json');

// Google JWT Authentication
const jwtClient = new google.auth.JWT(
  key.client_email,
  null,
  key.private_key,
  [scope1],
  null);
```
