### ISSUE TITLE
how to delete folder which contain somes file

### ISSUE THREAD

**Issue by nvcken** [google/google-api-nodejs-client#422]
I get error not found code 404
data.object = "FOLDER_NAME" ( I also tried data.object = "FOLDER_NAME" + "/" ) But it not work

if I delete all file in folder, then delete folder with data.object = "FOLDER_NAME" + "/" then it wok

```
 var params = {
    bucket : data.bucket,
    object : data.object,
  }
  gcStorage.objects.delete(params, function(err, data){
    if(err) cb(err);
    else {
      cb(null,data)
    }
  })
```

**Comment by JustinBeckwith** [comment]
Greetings!  The `gcloud` npm module provides a much better API for working with Google Cloud Storage.  We recommend you use that module.  If you're still having trouble, let us know!
https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-storage
