### ISSUE TITLE
Streaming not working with OAuth2

### ISSUE THREAD

**Issue by nsabovic** [google/google-api-nodejs-client#423]
Recently, something broke the streaming. I used to be able to do storage("v1").object.get(...).pipe(somewhere). Now, looking at [JWT.OAuth2Client.request](https://github.com/google/google-auth-library-nodejs/blob/697baf0da5b9737acf4754b120ab6b3589e05aa0/lib/auth/oauth2client.js#L339) in [google-auth-library](https://github.com/google/google-auth-library-nodejs), it returns [JWT.OAuth2Client.getRequestMetadata](https://github.com/google/google-auth-library-nodejs/blob/697baf0da5b9737acf4754b120ab6b3589e05aa0/lib/auth/oauth2client.js#L267), but that function returns nothing. It used to return the [request](https://www.npmjs.com/package/request) object.

**Comment by tcosentino** [comment]
Related: https://github.com/google/google-api-nodejs-client/issues/501

**Comment by JustinBeckwith** [comment]
Greetings!  This is no longer a problem.  With the change to axios, the stream is provided on a `res.data` object inside of the response callback.  Let us know if you're still running into issues!
