### ISSUE TITLE
[2.x regression] Error code no longer passed through in response

### ISSUE THREAD

**Issue by bradvogel** [google/google-api-nodejs-client#424]
I'm using v2.0.3 of this library in the following way:

```js
      client.users.drafts.update({
        userId: 'me',
        id: gmailDraftId,
        resource: {
          message: {
            raw: require('base64-url').encode(job.data.emailDraft)
          }
        }
      }, function(err, res, req) {
          // Detect 404 errors
         if (err.code === 404) console.log('does not exist');
      }));
```

In v1.x of this library, `err.code` was populated and correctly set to `404` when the draft didn't exist. However, since I upgraded to 2.x, `err.code` is now undefined. However, the response from the api hasn't changed; `req.body` is still: `{ error: { errors: [Object], code: 404, message: 'Not Found' } } }`.

Did something break in 2.x causing the error code to not get passed through from the response?

**Comment by bradvogel** [comment]
pint @ryanseys

**Comment by ryanseys** [comment]
Maybe. The big change in 2.x is all the auth logic moved to https://github.com/google/google-auth-library-nodejs Sorry I don't know much more about this change.

**Comment by jmike** [comment]
+1 this is a major issue for me

**Comment by JustinBeckwith** [comment]
Greetings!  I just tried this out with `node samples/drive/download.js NOTREAL`.  It returns an Error with `code` set to 404, and the `err.response.status` is 404.  Looks to be fixed!
