### ISSUE TITLE
gmail mail attachment thumbnails how to get ?

### ISSUE THREAD

**Issue by djholly123** [google/google-api-nodejs-client#428]
hi 

I am trying to get thumbnails so I can display in my app for an email ... is this possible?

example pdf doc attachment gives this <img src
=https://mail.google.com/mail/u/0/?ui=2&ik=05aee686e2&view=snatt&th=14cff8d12dcd0d4d&attid=0.9&disp=thd&zw&stw=150&sth=120

example jpg attachment img src =
https://mail.google.com/mail/u/0/?ui=2&ik=05aee686e2&view=fimg&th=14cff8d12dcd0d4d&attid=0.3&disp=thd&attbid=ANGjdJ8VfwWdQ6PbqStl8M2n84P-MLmnAoHOeNBxt8bp3t4KEA7DcIo1B0L18tDHgITVQOBgP-SUtM_ALeNHrOmc1BM4ZrXJ4Vzer-qilikHgkya6fO-KN0Gt9WKvqo&sz=w180-h120-p-nu&ats=1432557471200&rm=14cff8d12dcd0d4d&zw

so so different thumb src = for image / docs ?
and cant make any sense of the attbid= as this is different from the attachment id got from gmail.users.messages.get ?

any help appreciated

**Comment by JustinBeckwith** [comment]
Sadly, I don't believe this is possible.  You would have to just download the attachment from here:
https://developers.google.com/gmail/api/v1/reference/users/messages/attachments/get

And generate a thumbnail from that. Apologies!

**Comment by abhishekiOS** [comment]
How to get thumnail of attachment? Is any any API? I need to implement in Angular.
