### ISSUE TITLE
Prediction request end up with "invalid data" errors

### ISSUE THREAD

**Issue by ilanle** [google/google-api-nodejs-client#430]
**Hi,
Here is a simplified request using the library (this is after coffee compilation)**

 parameters = {
      auth: jwtClient,
      project: googleProjectID,
      id: 'interest_classifier',
      input: {
        csvInstance: ["country united states", "/location/location"]
      }
    };
    return prediction.trainedmodels.predict(parameters, function(err, response) {
      if (err) {
        logger.info(null, "prediction err ", err);
      }
      logger.info(null, "response from predict ", response);
      return callback(null, response);
    });

**And the response :**  

14:21:20 info   prediction err  { [Error: Input data invalid.]
  code: 400,
  errors:
   [ { domain: 'global',
       reason: 'invalidValue',
       message: 'Input data invalid.' } ] }

**Comment by ilanle** [comment]
Forgot to clarify:

The training data was csv with 3 columns, (1 value and 2 features)
When I run a similar request using the online simulator, runs fine.
It is only from my node server that I get these failures.
Could this be an encoding issue or something of the sort?

**Comment by ilanle** [comment]
And in case my authentication method is relevant:


var   jwtClient = new google.auth.JWT('*****@developer.gserviceaccount.com', 'keys/key.pem', null, ['https://www.googleapis.com/auth/prediction']);

  jwtClient.authorize(function(err, tokens) {
    logger.info(null, "authorizing");
    if (err) {
      logger.info(null, "error ", err);
    } else {
      return logger.info(null, "authenticated ", tokens);
    }
  });

**Comment by ilanle** [comment]
OK,
So I dug in a bit more, because clearly the solution is NOT going to come from Google (clearly no-one even looks at these open issues).
The reason this was not working for me is that the actual input data is part of the request body.
Now I looked into how the parameters are parsed and used by the library, and it turns out the payload needs to be nested inside a parameter called "resource"

,
So the request parameters need to look like this:
parameters = {
auth: jwtClient,
project: googleProjectID,
id: 'interest_classifier',
resource:{
input: {
csvInstance: ["country united states", "/location/location"]
}
}
};


This is totally undocumented, and really disappointing 
 closing, hope this helps others

**Comment by ryanseys** [comment]
I've tried my best to make it as clear as possible on how to specify a resource (the body of the request) so I'm sorry you continue to have trouble understanding. I've added [this section](https://github.com/google/google-api-nodejs-client#specifying-request-body) to the README to hopefully add more clarity.

**Comment by ilanle** [comment]
thank you
