### ISSUE TITLE
Drive files.list retrieve only 1 file

### ISSUE THREAD

**Issue by Nighthawk14** [google/google-api-nodejs-client#431]
Hi,

I'm trying to use the google drive api, but when I call
```js
var drive = google.drive('v2');
drive.files.list({auth: jwtClient}, function(err, files) {
    console.log(err);
    console.log(files);
});
```

The err is `null`
The files contains a `fileList` object which contain only 1 `file` item. I tried with 3 different google accounts, all 3 with a lot of files into the drive. I tried also in the api explorer (online) and this one give me the right list, not only 1 object.

ps : I'm using the `google.auth.JWT` authentication with scope as :
```
['https://www.googleapis.com/auth/drive']
```

Thanks :)

**Comment by ilanle** [comment]
So why dis you close?

**Comment by Nighthawk14** [comment]
Yep sorry, closed fast I didn't have time to say why.

So, As far as I saw, you have to impersonate a user to get the drive files of this user, this is what I guessed :

```js
var jwtClient = new google.auth.JWT(
  email: 'my-service-account@developer.gserviceaccount.com',
  keyFile: 'my-service-account-key.pem',
  null,
  ['https://www.googleapis.com/auth/drive']);
```
This code gives you the files for the user `my-service-account@developer.gserviceaccount.com`, so this user have only 1 file in the drive ( new drive )

```js
var jwtClient = new google.auth.JWT(
  email: 'my-service-account@developer.gserviceaccount.com',
  keyFile: 'my-service-account-key.pem',
  null,
  ['https://www.googleapis.com/auth/drive'],
  'email_address@mycompany.com');
```
This code gives you the files for the user `email_address@mycompany.com`, so this user have the right files.

I had to invite the impersonate user in my api console project + allow the project to get the files from the drive in my admin console (GoogleApps for business).

Hope it will help :).
