### ISSUE TITLE
Upload videos to multiple Youtube channels

### ISSUE THREAD

**Issue by h2non** [google/google-api-nodejs-client#434]
Given the same Google account which is associated to a Youtube with multiple channels, I would like to upload videos to multiple channels on the same account.

Currently, after reviewing the [API documentation](https://developers.google.com/youtube/v3/docs/videos/insert), I'm defining the field `onBehalfOfContentOwnerChannel` with the channel ID, but it seems like requires defining the `onBehalfOfContentOwner` field as well, so the questions are: 
- How can I obtain that value? 
- Which kind of value it is actually? 
- Is there another way to upload videos into a specific channel without defining the owner value?

**Comment by przemyslawpluta** [comment]
Same here ...

**Comment by przemyslawpluta** [comment]
@h2non still have an issue with this?

**Comment by h2non** [comment]
i didn't tried it again, to be honest. I've solved this with a workaround creating multiple Google accounts and assigning them to each specific channel, therefore I've to handle different OAuth credentials per each account. That worked for me.

**Comment by JustinBeckwith** [comment]
Greetings folks!  There's probably very little we can do with this one in the npm module.  For issues related to the underlying API, I suggest posting on one of the YouTube API specific forums:

- http://stackoverflow.com/questions/ask?tags=youtube-api
- https://code.google.com/p/gdata-issues/issues/entry?template=YouTube%20(Defect%20Report)
- https://github.com/youtube/api-samples

Hope this helps!
