### ISSUE TITLE
Google Cloud Datastore API

### ISSUE THREAD

**Issue by adamvresky** [google/google-api-nodejs-client#439]
Hi guys,
I'm trying to use Google Cloud Datastore API, but I cannot authenticate with service account using JWT.
I'm successfully requesting Storage API, but no luck with Datastore.

Do you have any idea why?

Thanks.

Adam

**Comment by akohout** [comment]
What does it mean you can not authenticate? Any errors?

**Comment by JustinBeckwith** [comment]
Greetings!  We've got a new NPM module that makes programming against Datastore easier.  Can you give this a try?  If it isn't working, feel free to reopen!

https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-datastore
