### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by davidhq** [google/google-api-nodejs-client#440]
I have problems using this lib like this from some `.jsx` file (it's a React app):

```
var Google = require('googleapis')
```
It works ok from `node` console, but in the browser I get:

`Uncaught TypeError: Cannot read property 'version' of undefined`
Full stacktrace: https://gist.github.com/davidhq/08c65de6498ef4dec56e

Sometimes I get something about module ./aes cannot be found.. it's random :/

Any hints?

**Comment by bojidar-bg** [comment]
@davidhq ~ BTW, I think that this library is made for use on the server, and not on the client...

**Comment by davidhq** [comment]
Ok thank you for confirmation.. I kind of noticed it's not possible to use on the frontend (do you know if it will never be possible?)..

I'm now using JS GAPI client... it's ok....
