### ISSUE TITLE
calendar.events.list multiple extendedProperty queries

### ISSUE THREAD

**Issue by afloyd** [google/google-api-nodejs-client#441]
With the current implementation, it's not possible to query multiple `privateExtendedProperty` fields... Per https://developers.google.com/google-apps/calendar/v3/reference/events/list, each additional query for another field should be added to the query string. 

However, due to the nature of JavaScript object it's not possible to supply the `list` method of the Calendar v3 implementation the privateExtendedProperty multiple times in a single object with a string value.

This currently works for a single property:
```
calendar.events.list({
	calendarId: 'xyz@group.calendar.google.com',
	privateExtendedProperty: 'userId=55'
}, function(err, data) {
	if (err) return console.error(err);
	console.log(data);
});
```

However, you cannot specify `privateExtendedProperty` multiple times such as:
```
calendar.events.list({
	calendarId: 'xyz@group.calendar.google.com',
	privateExtendedProperty: 'first=john',
	privateExtendedProperty: 'last=doe' // duplicate property, will just overwrite previous one
}, function(err, data) {
	if (err) return console.error(err);
	console.log(data);
});
```

Proposed solution (somewhere around here: https://github.com/google/google-api-nodejs-client/blob/master/lib/apirequest.js#L176)... If `privateExtendedProperty` or `sharedExtendedProperty` is an array then split out the contained strings to be appended to `request`'s `qs` property so it's works per the Calendar API specs. If not an Array and just a String then do nothing as it works as currently coded for single sharedExtendedProperty or privateExtendedProperty query.
```
calendar.events.list({
	calendarId: 'xyz@group.calendar.google.com',
	privateExtendedProperty: ['first=john', 'last=doe'],
	sharedExtendedProperty: ['donutType=chocolate', 'filling=strawberry']
}, function(err, data) {
	if (err) return console.error(err);
	console.log(data);
});
```

**Comment by reubenlara** [comment]
do you know how to retrieve that extended property?

**Comment by afloyd** [comment]
@reubenlara 
This should work:
```
var searchOpts = {
		calendarId: 'yourCalendarId',
		q: 'your query (if desired)',
		fields: 'items(creator/email,recurringEventId,recurrence,attendees,summary,start,extendedProperties,end,transparency),summary'
	};

require('googleapis').calendar('v3').events.list(searchOpts, function(err, data) {
	console.log('data:', data);
});
```

You specify it in the "fields" property... There's a bunch more in there than what you need but you can adjust it to suit your needs. Check under the "Try it" section here for a list of all possible fields to return:  https://developers.google.com/google-apps/calendar/v3/reference/events/list

**Comment by afloyd** [comment]
Well not sure if/when anything was changed affecting this, but looks like it's now working!

Can query multiple private extended properties via:
```
calendar.events.list({
    calendarId: 'xyz@group.calendar.google.com',
    privateExtendedProperty: ['first=john', 'last=doe']
}, function(err, data) {
    if (err) return console.error(err);
    console.log(data);
});
```

Or a single one with:
```
calendar.events.list({
    calendarId: 'xyz@group.calendar.google.com',
    privateExtendedProperty: 'first=john'
}, function(err, data) {
    if (err) return console.error(err);
    console.log(data);
});
```

PERFECT!! :+1:
