### ISSUE TITLE
revokeCredentials not returning a result in callback

### ISSUE THREAD

**Issue by JaKXz** [google/google-api-nodejs-client#445]
According to the [test suite](https://github.com/google/google-api-nodejs-client/blob/master/test/test.auth.js#L215) the callback function passed to `revokeCredentials` gets a result object if the operation was successful which should contain a `success` property. However, when I  use this snippet:

```js
oauth2client.revokeCredentials(function (error, result) {
  if (error || !result.success) {
    console.error('Failed to revoke credentials!');
    console.error(error || result);
  } else {
    //...
  }
});
```
I get: 
```
{ [TypeError: Cannot read property 'success' of undefined] __NR_transaction: null }
```
Am I missing something?

**Comment by JaKXz** [comment]
@ryanseys have things changed since [July of 2014](https://github.com/google/google-api-nodejs-client/blame/master/test/test.auth.js#L215)? I even ran the tests locally and they pass:

```
OAuth2 client
    ✓ should return err no access or refresh token is set before making a request
    ✓ should not throw any exceptions if only refresh token is set
    ✓ should set access token type to Bearer if none is set
    1) should refresh if access token is expired
    ✓ should make request if access token not expired
    2) should refresh if have refresh token but no access token
    revokeCredentials()
      ✓ should revoke credentials if access token present
      ✓ should clear credentials and return error if no access token to revoke
    getToken()
      ✓ should return expiry_date
```

which is also odd because I'm using `refreshAccessToken` as documented in the test suite and it seems to be working fine even though the tests are failing...

**Comment by JaKXz** [comment]
I also have a tangentially related question: if you have the refresh token, do you have to have a valid access token to call `revokeCredentials`? It seems like overkill to me to have to call `refreshAccessToken` before calling `revokeCredentials` just to be sure, when you're just revoking all the tokens anyway...

**Comment by JaKXz** [comment]
@ryanseys thanks for fixing the tests in `v2.0.6`! I'll try upgrading and testing again but I didn't see anything in the changes that affects this issue... any thoughts?

**Comment by ryanseys** [comment]
Try filing this issue against https://github.com/google/google-auth-library-nodejs which is what this library uses for all authentication matters.
