### ISSUE TITLE
Cannot rate the Google developers articles

### ISSUE THREAD

**Issue by IonicaBizau** [google/google-api-nodejs-client#453]
I'm getting a [404 page](https://developers.google.com/discovery/null) when trying to vote the articles ([example](https://developers.google.com/discovery/libraries)).

![image](https://cloud.githubusercontent.com/assets/2864371/8620297/53b32328-2727-11e5-9647-716684ed5e3c.png)

Even this is off-topic here, I still think it's an important issue to be solved. :smile: 

PS. In the future, where to report such issues?

**Comment by IonicaBizau** [comment]
Hmmm, this was fixed, but still the question remains: *PS. In the future, where to report such issues?*

**Comment by JustinBeckwith** [comment]
Appears to be working now.  In the future - this is a great place!
