### ISSUE TITLE
Can there be at-least one example from logging api.

### ISSUE THREAD

**Issue by VikramTiwari** [google/google-api-nodejs-client#455]
The process of connecting to the apis is pretty straight forward, but for some apis which are pretty new and whose functions haven't yet properly propagated in the masses should have some examples.

**Comment by ericuldall** [comment]
I'm also having issues writing entries via the logging api. Trying to generate json payload per the docs here: https://cloud.google.com/logging/docs/api/ref/rest/v1beta3/projects.logs.entries/write

**Comment by jmdobry** [comment]
@ericuldall For Cloud Logging, instead of using google-api-nodejs-client, you might try using the more idiomatic [gcloud-node](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.28.0/logging) library.

**Comment by ericuldall** [comment]
Thanks for the reploy @jmdobry 

Since we're writing logs from Kubernetes I've learned we can just output some structured JSON to suit our needs.

```
console.log(JSON.stringify(
    {
        "message": "my error here!",
        "severity": "ERROR"
    }
));
```

This gets parsed well enough and negates us having to connect via oAuth. Thought this would be useful for others working with Kubernetes.

**Comment by jmdobry** [comment]
To close out this issue, one of the better options would be to use [gcloud-node](https://googlecloudplatform.github.io/gcloud-node/#/docs/logging) which supports the Cloud Logging API quite well, and has a [number of examples](https://googlecloudplatform.github.io/gcloud-node/#/docs/logging).
