### ISSUE TITLE
Stream attempt to Drive with invalid OAuth2 token can result in lost data

### ISSUE THREAD

**Issue by ikb42** [google/google-api-nodejs-client#456]
Hi
Following a drive.files.insert with a media.body that is a stream, if the insert fails immediately (for instance due to token expired), it seems that the stream is left partly consumed / read.

Is this the case and if so is it avoidable?

**Comment by JustinBeckwith** [comment]
Greetings!  Since our move to axios, this issue has been resolved.  Check out this sample, and let us know if you have any problems!
