### ISSUE TITLE
How to download item from bucket in google cloud storage

### ISSUE THREAD

**Issue by vekexasia** [google/google-api-nodejs-client#462]
Hello there, i'm stuck.

The docs are suggesting to use cloudstorage.objects.get({bucket: 'mybucket', object:'objectname'})

Indeed, it works but it does return the metadata and not the "Buffer" containing the file content. Documentation examples are not providing a valid example for nodejs apis and googling the problem doesn't seem to help much :(.

Thanks.

**Comment by ryanseys** [comment]
Take a look at https://github.com/GoogleCloudPlatform/gcloud-node which is a more idiomatic way of handling Google Cloud Storage upload requests.
