### ISSUE TITLE
Google Play support?

### ISSUE THREAD

**Issue by IonicaBizau** [google/google-api-nodejs-client#466]
Is Google Play API supported? From the quick look I did, I didn't see it.

**Comment by jmdobry** [comment]
Yes, the `androidpublisher`, `games`, `gamesConfiguration`, `gamesManagement`, `playmoviespartner`, and `androidenterprise` APIs are supported.

**Comment by IonicaBizau** [comment]
@jmdobry Thanks! :+1:

**Comment by jmdobry** [comment]
Yep!
