### ISSUE TITLE
Memory leak report

### ISSUE THREAD

**Issue by jakeorr** [google/google-api-nodejs-client#470]
I have been seeing a memory leak reported when both `googleapis` and `gcloud` are included in the same app. The code below reproduced the error for me:

``` javascript
'use strict';

var memwatch = require('memwatch');
memwatch.on('leak', console.log);

require('gcloud');
require('googleapis');
```

`node` version: 0.10.26

I have since updated to node v4.0.0 along with an update to [`memwatch-next`](https://www.npmjs.com/package/memwatch-next) which seems to have gotten rid of the leak for me. I originally posted [an issue](https://github.com/GoogleCloudPlatform/gcloud-node/issues/873#issuecomment-142102511) about this in the `gcloud-node` repo and @stephenplusplus over there asked me to open an issue over here in case you guys wanted to have a look into this.

**Comment by jmdobry** [comment]
Need to do a code review.

**Comment by JustinBeckwith** [comment]
It looks like this issue seems to have resolved itself when 6 and 8 went LTS :) . Please do let me know if you're still running into issues!
