### ISSUE TITLE
[auth] low error margin on expiry_date => isTokenExpired false negatives

### ISSUE THREAD

**Issue by hzuo** [google/google-api-nodejs-client#478]
My app saves refresh tokens in long-term storage and caches the transient access tokens. I make calls to to the google drive api, polling the changes endpoint in ~1 minute intervals.

Every once in a while (~24 hours), I get a 401 Invalid Credentials error. The refresh token is definitely fine - it hasn't expired or been revoked, e.g. using the same refresh token a minute later (on the next poll cycle), it again continues to work again, despite the auth failure in the previous poll cycle.

Because it occurs pretty randomly, I think this issue originates from the following lines in the auth client library:

``` javascript
tokens.expiry_date = ((new Date()).getTime() + (tokens.expires_in * 1000));
```

``` javascript
var isTokenExpired = expiryDate ? expiryDate <= (new Date()).getTime() : false;
```

If there's any significant network latency in the remote calls, then the true expiry date will be earlier than the computed expiry_date, and isTokenExpired may be set to false even when it should really be true. This would result in an API call with the expired access token, leading to a 401 Invalid Credentials error.

In my specific case, it would also makes sense in that on the next poll cycle, we would have passed the computed expiry_date, and the refresh token is then used to get a new access token, and the system continues to work fine.

Let me know if I'm totally off base, and thanks for this great client library!

**Comment by jmdobry** [comment]
How significant of latency? Are you thinking a few hundred milliseconds or several seconds? Perhaps `(new Date()).getTime()` should be computed _before_ the `tokens` are received, to take into account the request latency?

**Comment by JustinBeckwith** [comment]
We added an expiration margin, and we made it configurable here:
https://github.com/google/google-auth-library-nodejs/commit/7e9a3903c14340bc20ec4935138e6fb0dd8d1f8a

You should be good to go now!
