### ISSUE TITLE
Is there API for contacts?

### ISSUE THREAD

**Issue by stefek99** [google/google-api-nodejs-client#480]
I've just had a quick look here: https://github.com/google/google-api-nodejs-client/tree/master/apis

```CMD + F``` searching for ```contacts```

https://developers.google.com/google-apps/contacts/v3/?hl=en

Before I write my own / use existing wrappers I would like to know if I'm missing something, if contacts API is available out-of-the-box.

Thanks

**Comment by vpontis** [comment]
I am also looking into this. Right now I think I am going to get the OAuth2 token with this library and then use that with the contacts JS api to pull contacts. 

It would be great if there was built-in contacts support though! :smile:

**Comment by stefek99** [comment]
@vpontis ```contacts JS api``` - https://developers.google.com/google-apps/contacts/v3/

> Retrieving all contacts
> To retrieve all of a user's contacts, send an authorized GET request to the following URL:
> https://www.google.com/m8/feeds/contacts/{userEmail}/full

Would be nice to know if the ```google-api-nodejs-client``` offers some shorthand methods...

**Comment by bradvogel** [comment]
https://github.com/google/google-api-nodejs-client/issues/254

**Comment by stefek99** [comment]
Thanks, fair comment!

**Comment by koreanilkumar** [comment]
https://myaccount.google.com/contacts

Save contact info when you interact with people

Is there any API to get the contacts for this in NodeJS?
