### ISSUE TITLE
Add Support For Authenticated URL Discovery

### ISSUE THREAD

**Issue by waprin** [google/google-api-nodejs-client#487]
I want to generate an API client using a Discovery URL that's only available once you're authenticated as a trusted tester. The Python api clients can do this

I think there just needs to be an option to authenticate the DefaultTransporter in lib/generator.js before making the call. 

I can do a PR for this, just want to make sure there's not already way to do this and the PR will get accepted.

**Comment by jmdobry** [comment]
Let's work together on this.

**Comment by waprin** [comment]
SGTM, happy to put it on a Q2 OKR. I think step 1 is to catch up with all the various API client teams and make sure whatever we're working on fits into their plans.

**Comment by JustinBeckwith** [comment]
@waprin @jmdobry do we still need this?  I'm happy to take it on if folks are still asking for it.  Can you point me towards an example of a private API?

**Comment by JustinBeckwith** [comment]
If you love a bug, let it go.  If it loves you, it will come back.  If we really need this, let me know and I'll re-open the issue :)
