### ISSUE TITLE
Full Support For Discovery Doc APIs

### ISSUE THREAD

**Issue by waprin** [google/google-api-nodejs-client#489]
@jdobry has a https://github.com/google/google-api-nodejs-client/pull/488 
to generate the API from a discovery doc, but in order to use that you have to edit apis/index.js in order for it to work.

For EAP use cases we want to be able to distribute discovery docs and let people use that to access APIs without having to distribute a patched library or ask the end-user to do so. Again, this is all for feature parity with the Python client.

I can look into submitting a PR but would like a go-ahead from a repo owner that this will get accepted.

**Comment by jmdobry** [comment]
I will look into expanding #488 to also update apis/index.js

**Comment by jmdobry** [comment]
Fixed by #488 and #550, with an even better solution coming in #555
