### ISSUE TITLE
Add `mobileReady` API

### ISSUE THREAD

**Issue by joeyhoer** [google/google-api-nodejs-client#491]
I didn't see this discussed in any other issues.

The [Google Mobile Friendly test](https://www.google.com/webmasters/tools/mobile-friendly/) uses version `v3beta1` of`pagespeedonline`.

Access to the mobile friendly data is available at: https://www.googleapis.com/pagespeedonline/v3beta1/mobileReady.

**Comment by jmdobry** [comment]
Right now google-api-nodejs-client is generated from the production Google API discovery index, which currently does not include the pagespeedonline v3beta1 API. I don't know why the pagespeedonline v3beta1 API isn't listed in that index, as the index contains beta versions of other APIs.

To add v3beta1 to google-nodejs-api-client, we're looking into expanding the API surface for which google-nodejs-api-client is generated. Stay tuned.

**Comment by jmdobry** [comment]
This issue should be fixable by #534.

**Comment by jmdobry** [comment]
Actually, @joeyhoer do you know of a discovery doc for `pagespeedonline` `v3beta1`? Because without one neither #534 nor #555 will be able to make this library support that API.
