### ISSUE TITLE
google.drive.files.update() fail with Google Apps Script Bound to Google Sheets

### ISSUE THREAD

**Issue by zixia** [google/google-api-nodejs-client#495]
I have a Scripts Bound to Google Sheets. when I edit it, the url is like: https://script.google.com/a/mydomain.com/macros/d/Md-MytdOSdIJ9XDzO7J5kDJpRT9d30hqB/edit .

I use node-google-apps-script( https://github.com/danthareja/node-google-apps-script ) to export files from it. it could be exported by id Md-MytdOSdIJ9XDzO7J5kDJpRT9d30hqB successful.

But when I try to import back, I got a error: 

```shell
Pushing back up to Google Drive...
An error occured while running upload command: null
Upload failed.
```

it seems like that google.drive.files.update()  does not support bounded scripts.

another issue here: https://github.com/danthareja/node-google-apps-script/issues/24

**Comment by zixia** [comment]
another issue here: https://github.com/danthareja/node-google-apps-script/issues/24

**Comment by jmdobry** [comment]
For now at least, closing per @cjs-cynic-net's [comment](https://github.com/danthareja/node-google-apps-script/issues/24#issuecomment-174246384) as it appears the deficiency is in the v2 Google Drive API, not google-api-nodejs-client. Perhaps the v3 API works better? gapps would need to try it.
