### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by Bigous** [google/google-api-nodejs-client#503]
Could you include the d.ts file in this client distribution?

**Comment by isman-usoh** [comment]
+1

**Comment by panKt** [comment]
+1 :+1:

**Comment by procrastinatos** [comment]
+1

**Comment by christhomas** [comment]
yes absolutely! this project really needs a typescript definition file....

**Comment by procrastinatos** [comment]
I took a stab at generating Typescript definitions based on the endpoint data from Google's discovery API. Disclaimer: I'm fairly new to all things Node & Typescript. Caveat emptor. Anyhow, typings available in the dist folder.

**Comment by Bigous** [comment]
It seams that the new SALSA technology, typescript will be able to recognize things without .d.ts - [there is a pull request enable this things](https://github.com/Microsoft/TypeScript/pull/7075).

**Comment by VamshiKrishnaAlladi** [comment]
+1

**Comment by arondesign** [comment]
+1

**Comment by n-sviridenko** [comment]
+1

**Comment by danieloprado** [comment]
+1

**Comment by masimplo** [comment]
Any news on this? Typings would greatly improve our experience working with this library.

**Comment by abruneau** [comment]
+1

**Comment by abruneau** [comment]
Since Typescript 2.1 you can import Untyped modules 
So you can do 
`import * as google from "googleapis";`

But for that, we need to update the `package.json` file and change main to `"main": "./lib/googleapis.js",`

**Comment by JustinBeckwith** [comment]
I'm starting to work on this one.  This has to be done over several PRs, but the plan is:
- [ ] Perform a basic update the files to `*.ts` and wire up the compiler (#731)
- [ ] Fix syntax to move towards classes and es6 style imports
- [ ] Introduce tslint with relaxed configuration
- [ ] Add `noImplicitAny` to the `tsconfig.json` and apply required types
- [ ] Include the `.d.ts` file along with the npm module

Feedback on the approach welcomed.

**Comment by gDelgado14** [comment]
hey @JustinBeckwith any update on this? You also don't need a `.d.ts` file since the code is written in typescript. The typedefs should be baked into the code itself. Otherwise the simple fix would have been to leave all of the code as it was and simply include a `.d.ts.` file to describe the structure of the package to the ts compiler. 

[Axios](https://github.com/axios/axios/blob/master/index.d.ts) is a good example of this approach.

**Comment by gDelgado14** [comment]
To add to the above comment: Despite the `.ts` file extensions, my compiler doesn't pick up any type information from this repo. Hence I'm forced to write my own `googleapis.d.ts` file in my project. Is there some configuration I need to do on my `tsconfig` in order to start inferring types from a typescript-based module?

**Comment by martywins** [comment]
Any update on this?

**Comment by JustinBeckwith** [comment]
Apologies for the delay here folks.  We did a lot of work to get things moved over to typescript, but I just haven't gone the last mile to get the generated d.ts included in the package.  There's a PR over in #785 to cover this :)

**Comment by bjrnt** [comment]
@JustinBeckwith Looks like #785 been merged. Would be amazing to get a new version with this and the `types` field in `package.json` set! :)

**Comment by 0x80** [comment]
@JustinBeckwith any news on this?

**Comment by vaskevich** [comment]
BUMP. Any news?

**Comment by JustinBeckwith** [comment]
Yes!  We do ship a `d.ts` today.  It's not terribly useful, because we don't have type information for the majority of the APIs.  Most of the infrastructure is in place, but there's a lot of work left to generate better TypeScript for the libs.

**Comment by sebbean** [comment]
current year!

**Comment by supermacro** [comment]
fwiw, you can patch the dep as well. Hopefully this helps someone out there. 

- https://pnpm.io/cli/patch
- https://bun.sh/docs/install/patch
- https://yarnpkg.com/cli/patch
