### ISSUE TITLE
Is getToken Return Data an Array?

### ISSUE THREAD

**Issue by DavidTPate** [google/google-api-nodejs-client#506]
Looking at the ReadMe it states:

> However, note that return data of getToken has become an array.

However the [Migration Guide](https://github.com/google/google-api-nodejs-client/blob/master/MIGRATING.md) doesn't state that and looking at the [tests](https://github.com/google/google-api-nodejs-client/blob/0358c8f466a828cee0d7df3773bb5e0ad1506627/test/test.auth.js#L238-L244) it is not an array but an object just like it was in `v1.x`.

**Comment by JustinBeckwith** [comment]
Greetings!  It returns an object.  You can see a sample here:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/oauth2.js
