### ISSUE TITLE
youtubePartner.references.insert returns "Request Entity Too Large"

### ISSUE THREAD

**Issue by AboulEinein** [google/google-api-nodejs-client#508]
I'm trying to add a `Reference` video to an `Asset`, but the request returns "Request Entity Too Large" and I'm not sure if I'm doing something wrong. I'd really appreciate any help.

Here's my sample code:

    fs.readFile(FILE_PATH, function(err, data) {
        if (!err) {
            ytpapi.references.insert({
                auth: oauth2Client,
                onBehalfOfContentOwner: contentOwner,
                resource: {
                    assetId: ASSET_ID,
                    contentType: 'video',
                    media: {
                        mimeType: 'video/mp4',
                        body: data.Body
                    }
                }
            }, function (err, data) {

                if (err) {
                    console.log(err);
                }

                console.log('Success');
            });
        }
    });

**Comment by AboulEinein** [comment]
I found the problem, I mistakenly put the media object within the resource object. The correct way is:

    resource: {
        assetId: ASSET_ID,
        contentType: 'video',
    },
    media: {
        mimeType: 'video/mp4',
        body: data.Body
    }

**Comment by SunilAgrawal** [comment]
@AboulEinein  I don't see youtubePartner as part of Google API. Where did you find it?

**Comment by AboulEinein** [comment]
You'll need to generate it: https://github.com/google/google-api-nodejs-client/issues/365
