### ISSUE TITLE
Service accounts & JWTs/OAuth2.0 Flow 

### ISSUE THREAD

**Issue by thelostspore** [google/google-api-nodejs-client#510]
[Google's documentation](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#authorizingrequests) for making authorized API calls with a service account using JWTs describes three steps => (1) Create JWT, (2) Request an access token, (3) Use token to call Google API. 

In this library, the [JWT example](https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens) does not seem to follow the pattern described in the documentation - why pass the whole `jwtClient` as part of the API call (even if it contains a reference to the token) as opposed to the access token itself? 

e.g. 

``` js
var key = require('path/to/key.json');
var jwtClient = new google.auth.JWT(key.client_email, null, key.private_key, [scope1, scope2], null);

jwtClient.authorize(function(err, tokens) {
  if (err) {
    console.log(err);
    return;
  }

  // Pass tokens to make an authorized request
  drive.files.list({ auth: tokens }, cb);
});
```

This is just a thought/suggestion to make usage of the library a bit more intuitive, based on the Google documentation.

**Comment by JustinBeckwith** [comment]
The purpose of that class is to make handling service <-> service workflows waaaaay easier.  With the google-auth-library, this is what using JWT looks like:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/jwt.js

This automatically handles:
- Acquiring the access token (and refresh token if available)
- Storing the expiry date
- Refreshing the token automatically if needed
- Attaching the right headers to the request. 

Let us know if you have any other questions!
