### ISSUE TITLE
Problem with create a new tag (GTM api)

### ISSUE THREAD

**Issue by wempoopl** [google/google-api-nodejs-client#515]
Hello everybody,

I was tried to create a new tag by GTM api like that:

```
var params = {
    "accountId" : xxx,
    "containerId" : xxx
    "name": "Sample Universal Analytics Tag",
    "type": "ua",
    "parameter": [
         {
              "type": "template",
              "value": "UA-123456-1",
              "key": "trackingId"
          }
     ]
}

gtm.accounts.containers.tags.create(params, (err, data) => {
    if (err) {
        console.log('[Error]  ', err);
        return;
    }
});
```

but every time i've got 500 error message: backendError ( I checked other api methods like remove specific tag by id and it worked). Any ideas?

**Comment by wempoopl** [comment]
I sent the body parameter in resource field and now all works correctly.

**Comment by raghu64** [comment]
Hi wempoopl,

I'm new to google API and trying to create a new tag, but i was getting 500 Backend Error message.

Can you provide some example how you fixed this issue.

Thanks
