### ISSUE TITLE
androidpublisher.purchases.products.get: response 500 (Problem with Google Play Developer API)

### ISSUE THREAD

**Issue by sosloow** [google/google-api-nodejs-client#521]
I've been trying to get server-to-server validation of in-app purchases to work. I set up a service account in google console, linked the project in google play console, gave the correct access rights to the service accounts.

Along this steps I was getting meaningful responses from the API (e.g. "400 project wasn't linked") but after I set up the access, I started to get `{"message": { "code": 500 }}` .

Here's how I'm using the method: 

```javascript

const google = require('googleapis');
const publisher = google.androidpublisher('v2');

const jwtClient = new google.auth.JWT(
  key.client_email,
  null,
  key.private_key,
  ['https://www.googleapis.com/auth/androidpublisher'],
  null);

google.options(auth: jwtClient);

authClient.authorize((err, tokens) => {
  if (err) {
    return console.log(err);
  }

  androidpublisher.purchases.products.get({
    packageName: packageName,
    productId: productId,
    token: purchaseToken
  }, (err, response) => {
    if (err) {
      console.log(err)
  });
});

```

**Comment by jmdobry** [comment]
So that `console.log(err)` just prints `{"message": { "code": 500 }}`? Does `response` contain any information or is it `undefined` when there is an error?

**Comment by sosloow** [comment]
Well, yes, the actual `console.log` is `{ [Error: null] code: 500 }` - the text above is this error object being parsed to json. `response` argument is `null` too.

**Comment by jmdobry** [comment]
Can you try hitting the endpoint through the API Explorer? https://developers.google.com/apis-explorer/#search/androidpublisher/androidpublisher/v2/androidpublisher.purchases.products.get

**Comment by sosloow** [comment]
I can't get through this error there: "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console." Can I somehow pass credentials related to the Google Developers console project that was linked in the Google Play Developers console?

**Comment by jmdobry** [comment]
> has not been linked in the Google Play Developer Console

This seems to indicate you can link the projects. [This](https://developers.google.com/android-publisher/getting_started#linking_your_api_project) may be what you need to do that.

You could also try using `curl` to hit the endpoint, using the access_token provided to your jwtClient:

```shell
curl https://www.googleapis.com/androidpublisher/v2/applications/{packageName}/purchases/products/{productId}/tokens/{token}?access_token={access_token}
```

**Comment by sosloow** [comment]
Yes, the same `500` and `null`.

I get the different message, if non-existing `packageName`, but I can pass both valid and invalid `productId`, and API returns 500 anyway. By the way, you can see I'm not passing an actual `token` with request, just `123`.

![500](https://cloud.githubusercontent.com/assets/1392262/13522211/094bb81e-e210-11e5-9cfa-07ed9bd978dd.png)

**Comment by jmdobry** [comment]
Don't you need an actual token?

**Comment by sosloow** [comment]
Well, I guess. But I think, it should return a meaningful message anyway, something like "400 invalid purchase token".

We will test this API with the actual receipt data today, and I will see if it's going to work.

**Comment by sosloow** [comment]
Yes, with a correct token API returned 200.

But I still think, 400 response with a message would be more appropriate to invalid request.

**Comment by jmdobry** [comment]
I agree with you, though that's an issue with the API itself, not this client library.

I sent this bug to the androidpublisher team.
