### ISSUE TITLE
Validate user input according to discovery doc schema

### ISSUE THREAD

**Issue by jmdobry** [google/google-api-nodejs-client#528]
**Background**: To make a request the user may provide parameters and/or a resource. Some parameters are required in that they are path parameters, and don't go into the querystring. If a user misspelled a parameter key, or forgets to nest request body data under the `resource` parameter, then google-api-nodejs-client doesn't help. It doesn't throw or otherwise notify the user. The API itself may return an error if requirements were not met, but it may also result in unexpected and confusing behavior.

This issue is a proposal to add schema validation to the user's request input, as described by each API's discovery doc. Validate key names, make sure the user didn't forget a required parameter, misspell a parameter key or put it in the wrong place.

A number of issues have been opened that seem to be rooted in the current lack of validation, so this feature should make this library more user friendly.

**Comment by JustinBeckwith** [comment]
So good news / bad news.  The good news is that... the library is already doing this sorta.  For parameters, the discovery doc format lets you know which fields are required.  We parse that, and check to make sure all required parameters have a value before making the request.  And we give a descriptive error.

Sadly, as far as I know, we can do no such thing for the request body in the case of a POST/PUT.  The discovery schema will tell you when there's a potential request body, and tell you the potential fields.  However, it will *not* tell you if the request body is required or not, and it doesn't tell you if individual fields in the body object are required or not 😦 

I think we've done all we can do here with the data available to us.  If you can think of another way to get this information....  I'd love to add more validation.
