### ISSUE TITLE
Use a sources.json file to find Discovery docs

### ISSUE THREAD

**Issue by jmdobry** [google/google-api-nodejs-client#534]
This will allow us to add APIs that are public, but don't necessarily show up in the single Discovery API service that google-api-nodejs-client uses now.

A `sources.json` file would point to the currently used Discovery API, in addition to other Discovery docs that may be available.

**Comment by jonparrott** [comment]
No idea. All of the other clients operate on the discovery service as far as I know.

**Comment by JustinBeckwith** [comment]
If you love a bug, let it go.  If it loves you, it will come back.
