### ISSUE TITLE
Update documentation to include information about migrating from 2.x to 3.x

### ISSUE THREAD

**Issue by Eruant** [google/google-api-nodejs-client#538]
Currently the 3.0.0 and 3.1.0 documentation has a reference to [upgrading to version 2.x](http://google.github.io/google-api-nodejs-client/3.1.0/index.html#migrating-to-version-2x-of-this-library)

I would expect to see information regarding upgrading to 3.x.

Thanks

**Comment by jmdobry** [comment]
There isn't anything to know except the breaking changes listed in the [changelog](https://github.com/google/google-api-nodejs-client/blob/master/CHANGELOG.md#300---14-march-2016). Google has removed some APIs from the discovery service, so they're removed from 3.0.0.

But I can update migrating.md
