### ISSUE TITLE
How to Validate email adress while sending an email (gmail api)# not an issue

### ISSUE THREAD

**Issue by Chethandsagar** [google/google-api-nodejs-client#539]
For example user may enter invalid email address in 'to'  while sending a mail how to validate these kind of errors. 

is there any sample snippet for this .

Thanks in advance!

**Comment by jmdobry** [comment]
The API doesn't validate for you. Here's a topic for validating email addresses yourself: http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address
