### ISSUE TITLE
Should update docs arround the messages.modify

### ISSUE THREAD

**Issue by chartie4r** [google/google-api-nodejs-client#541]
In the documentation, there's no way to know that we need to add the addLabelsIds and the removeLabelsIds in a resource object.

https://developers.google.com/gmail/api/v1/reference/users/messages/modify#examples

**Comment by jmdobry** [comment]
The best documentation for any given API is the json-schema discovery document for that API: Here is the one you're looking for: https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest

In that document you'll find that indeed it is documented that `messages.modify` takes a `ModifyMessageRequest` resource, which has two properties: `addLabelIds` and `removeLabelIds`.

If you'd still like to raise an issue with the gmail examples, it's best you do it [here](https://code.google.com/a/google.com/p/apps-api-issues/issues/entry?labels=Type-Defect,API-Gmail), as this issue tracker is just for the Node.js client library.
