### ISSUE TITLE
Implement way to update thumbnail in Drive API v3

### ISSUE THREAD

**Issue by HR** [google/google-api-nodejs-client#546]
While the official Drive API v3 doc documents [thumbnails and how to set them](https://developers.google.com/drive/v3/web/file), I can find no implementation of this in the client (no contentHints.thumbnail param exists). The params to the methods are also not well (what properties can the [params.resource](https://github.com/google/google-api-nodejs-client/blob/master/apis/drive/v3.js#L611) have? other than name and mimeType) documented and follows a different structure from the official doc.

**Comment by jmdobry** [comment]
You'll not find anything in the source code related to `contentHints.thumbnail`, as `contentHints` is one of the available properties of the `File` resource that many of the v3 Drive API methods accept. You can read the full json-schema discovery document for the v3 Drive API here: https://www.googleapis.com/discovery/v1/apis/drive/v3/rest

In that, you'll find the `contentHints` property, which has a `thumbnail` property. So similar to how you updated the v3 Drive API documentation in the README to pass a `name` property, you can also pass a `contentHints` property.

**Comment by HR** [comment]
Thanks. This should've been made clearer in the docs here.

**Comment by jmdobry** [comment]
If you'd like to contribute a `contentHints.thumbnail` example to the [`samples/`](https://github.com/google/google-api-nodejs-client/tree/master/samples) folder, that would be wonderful. The samples are really the only "extra" documentation we can add to the client, as the client itself is generated from the discovery docs, which are managed by the API owners.

Though even better than adding a sample here would be to go to the [Drive REST API support page](https://developers.google.com/drive/v3/web/support), and ask them to add a `contentHints.thumbnail` sample to https://developers.google.com/drive/v3/reference/files/update (which does actually mention `contentHints.thumbnail`).
