### ISSUE TITLE
Does Node.js have to have copy and paste authentication?

### ISSUE THREAD

**Issue by sicksbyproxy** [google/google-api-nodejs-client#548]
Javascript quickstarts are just click authentications while the node.js quickstart requires you to copy and paste. It's not too user friendly. 

Has anyone found a work-around for this? The authentication paragraph of the guidelines weren't very clear for me so it'd be a huge help to see someone's sample code.

FYI I'm working with the calendar api quickstart.js
[https://developers.google.com/google-apps/calendar/quickstart/nodejs](url)

<your detailed question and code samples go here>

Thanks!

**Comment by jmdobry** [comment]
Can you be more specific as to what you're copying and pasting? How can this library change to improve your experience? If this is an issue with the Google Calendar API documentation, your best option to help them improve it is to send them feedback with the Send Feedback button at the top right of the page.

**Comment by jmdobry** [comment]
In the Node.js sample, there's nothing to click, as it is just a process running on a server.
