### ISSUE TITLE
Analytics - support for v4

### ISSUE THREAD

**Issue by faubertin** [google/google-api-nodejs-client#549]
Analytics v4 adds some nice new features (https://developers.google.com/analytics/devguides/reporting/core/v4/). It would be great if google-api-nodejs-client would support it.

Thanks

**Comment by jmdobry** [comment]
Support for `analyticsreporting` `v4` is available as of google-api-nodejs-client [5.0.0](https://github.com/google/google-api-nodejs-client/releases/tag/5.0.0).

**Comment by Akhoy** [comment]
I'm on google-api-nodejs-client v9 but when I try to use analytics reporting v4, it still doesn't work. Even the sample here uses v3. Anyway I could make this work?
[Sample](https://github.com/google/google-api-nodejs-client/blob/master/samples/analytics/analytics.js)

**Comment by jmdobry** [comment]
> it still doesn't work

@Akhoy Can you be more specific? What exactly are you trying to do? What error are you encountering? Do you have code I can use to reproduce your error?

**Comment by Akhoy** [comment]
@jmdobry I'm trying to use something like this: 
`let google = require('googleapis');
let analytics = google.analytics('v3');` 
as shown in the samples but with v4. When I try to use
`let analytics = google.analytics('v4');` it doesn't work. Is this the correct way?

**Comment by jmdobry** [comment]
@Akhoy There isn't any `analytics` `v4` API. There _is_ an `analyticsreporting` `v4` API: `let analyticsreporting = google.analyticsreporting('v4');`

**Comment by juanitofly** [comment]
@jmdobry I'm getting this error 
`{
  "code": 400,
  "errors": [
    {
      "message": "Invalid JSON payload received. Unknown name \"reportRequests\": Cannot bind query parameter. 'reportRequests' is a message type. Parameters can only be bound to primitive types.",
      "domain": "global",
      "reason": "badRequest"
    }
  ]
}`

I'm using
`analyticsreporting.reports.batchGet(gaObject, callback);`

It's that right?

**Comment by karthik-mediamath** [comment]
Am using the node sdk and am able to successfully get the response. Is there any helper to transform the result to csv file or any other consumable format?

**Comment by ace-n** [comment]
@karthik-mediamath I'm not sure the API natively provides this functionality - but does [this](https://www.google.com/search?q=node+json+to+csv+site%3Anpmjs.com) help?
