### ISSUE TITLE
Domain Shared Contacts Support

### ISSUE THREAD

**Issue by raz3r** [google/google-api-nodejs-client#552]
I'd like to retrieve and modify our Google Apps domain shared contacts but I can't seem to find the methods in the Directory API. Am I missing something? Thank you.

**Comment by jmdobry** [comment]
Which API specifically are you trying to use? Can you link to its documentation?

**Comment by raz3r** [comment]
[Domain Shared Contacts](https://developers.google.com/admin-sdk/domain-shared-contacts/)

**Comment by jmdobry** [comment]
Ah, this is an older API that is not supported by google-api-nodejs-client. Unfortunately, you'll have to formulate HTTP requests yourself according to the documentation you linked to in order to interact with this API.

**Comment by raz3r** [comment]
The HTTP request itself is not an issue, authentication is the issue since normally I would use JWT. In Java there's still a library for Shared Contacts that allows to easily use Service Accounts and I was hoping to find something similar in NodeJS. I understand that it is an "old" API but Shared Contacts are not old at all since many companies regularly use them :( Any hint on where shall I look at?

**Comment by raz3r** [comment]
I managed to get it work using JWT, for anyone wondering how I'm probably going to open a repository :)

**Comment by jmdobry** [comment]
Sounds good!

**Comment by kevinob11** [comment]
@raz3r did you end up opening a repo for this? I'd love to see how you did it.

**Comment by ad-m** [comment]
@raz3r , for archival purpose here is example:

```javascript
const {JWT} = require('google-auth-library');
const axios = require('axios');

const Organization = 'example.com';

const main = async () => {
    const jwt_token = new JWT({
        email: 'vacationreplymanager@vacationreplymanager.iam.gserviceaccount.com',
        keyFile: 'keys/vacationreplymanager-7dbf49809e60.json',
        subject: 'admin@example.com',
        scopes: [
            'https://www.google.com/m8/feeds/contacts/'
        ]
    });
    const {access_token, token_type} = await authClient.authorize();
    const getHeader = () => ({
        Authorization: `${token_type} ${access_token}`,
        'GData-Version': 3.0
    });

        const url = `https://www.google.com/m8/feeds/contacts/${Organization}/full`;
    await axios.get(url, {
        headers: await getHeader()
    }).then(response => {
        console.log(response.data)
    });
}
```
