### ISSUE TITLE
Any rest API'S or node modules available for Google Forms

### ISSUE THREAD

**Issue by varunpal7** [google/google-api-nodejs-client#553]
I am trying to search for rest API'S or node modules for google forms , but i am not getting any google api's  ,neither i am able to find any node module for Google Forms.Please let me know if you have any information on the above concern.

Thanks,
Varun

**Comment by jmdobry** [comment]
Currently you must use [App Scripts](https://developers.google.com/apps-script/). That's all I know of.

**Comment by varunpal7** [comment]
Ya i know about the App Scripts, but it will take long time to get used to it.So is there any API's or node modules for google form that would make my work easy and fast.
