### ISSUE TITLE
5.2.0 is messed up - missing dependencies, missing files

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [google/google-api-nodejs-client#560]
After installing googleapis@5.2.0 as a dependency with npm and requiring it in my code:

 - Dependency "swig" is missing (so I installed it manually)
 - Dependency "js-beautify" is missing (I installed it manually)
 - The attempt to open file "./templates/api-endpoint.js" fails

That's as far as I went, then reverted to 5.1.0 which works just fine.

**Comment by mik115** [comment]
Also for me is the same!

**Comment by massimiliano-delia** [comment]
+1, I'm experiencing the same issue.

**Comment by ypanyukov** [comment]
the same!

**Comment by achehlov** [comment]
the same! Heloooooo

**Comment by pixeleet** [comment]
Yeah, it's broken. But why? Who did miss the fact that 2 dependencies are missing and 1 is just not there?

**Comment by achehlov** [comment]
dolboyobi iz googla

**Comment by captainbuzzlightyear** [comment]
+1, can confirm

**Comment by jmdobry** [comment]
Fix is in the works.
