### ISSUE TITLE
Google Drive: Access token on download

### ISSUE THREAD

**Issue by Aspie96** [google/google-api-nodejs-client#563]
Hi,
I used this script to download a file from Google Drive:

``` javascript
var stream = fs.createWriteStream("demo.txt");
drive.files.get({
    fileId: myId,
    alt: "media"
}).on("end", function() {
    console.log("Finished");
}).on("error", function(err) {
    console.log(err);
}).pipe(stream);
```

The first time I run it, in "demo.txt", instead of getting the content of the file I am downloading, I get my private access token (which, of course, is not a good thing).
I would like to understand what I am doing wrong.

Thank you very much in advance!

**Comment by Adrion** [comment]
Hope [this helps ](https://github.com/google/google-api-nodejs-client/issues/501#issuecomment-221263744)
#501

**Comment by savalaraymond** [comment]
p, td { line-height: 1.3; }
    p { padding-bottom: 1em; }
    a { color: #3697b3; font-weight: bold; text-decoration: none; }
    a:hover { color: #000; text-decoration: underline; }
    a:active { color: #000; text-decoration: underline; }
  




  
   
     Evernote helps you remember everything and get organized effortlessly. Download Evernote.

**Comment by ace-n** [comment]
@Aspie96 Is this still an issue for you? If not, mind if I close this?

**Comment by Aspie96** [comment]
It very much is still an issue (not just for me).

I am actually no longer using Google Drive as a backend for this reason.

@jmdobry actually opened a new issue: #625 for this, so you can close mine if you wish.

**Comment by ace-n** [comment]
Will do - thanks for the quick responses!
