### ISSUE TITLE
CalendarApi events.insert not working

### ISSUE THREAD

**Issue by awb99** [google/google-api-nodejs-client#565]
Google calendar.evetns.insert does not work:
```
calendar.events.insert (
        {
            start: { dateTime: "2016-05-03T18:03:58+02:00" },
            end: { dateTime: "2016-05-03T18:03:58+02:00" },
            calendarId: "uq6d9is81bgl0jbeuamt27br9c@group.calendar.google.com",
            summary: "test Summary"
        }, printResult );
```

This returns:
```
 { [Error: Missing end time.]
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'required',
       message: 'Missing end time.' } ] }
```

I tested it via curl, and via curl it works:
```
curl -X POST -d @data/calendarAdd.json https://www.googleapis.com/calendar/v3/calendars/myemail%40gmail.com/events?access_token=<my token>  --header "Content-Type:application/json"
```

Strangely enough the quickadd does work
```
 calendar.events.quickAdd ( {calendarId: "uq6d9is81bgl0jbeuamt27br9c@group.calendar.google.com", text: "20160501 test" }, printResult );
```

I guess that perhaps "end" is a reserved word?

I have removed the token that I did use.

**Comment by awb99** [comment]
I solved it. 
I think this should be highlighted un the readme..
```
  calendar.events.insert (
        {
            calendarId: "uq6d9is81bgl0jbeuamt27br9c@group.calendar.google.com",
            resource : {
              start: { dateTime: "2016-05-03T18:03:58+02:00" },
              end: { dateTime: "2016-05-03T18:03:58+02:00" },
              summary: "ivan schrecklich"
            }
        }, printResult );
```

**Comment by segreb** [comment]
Probably, the reason of this error not wrong time. Probably, Calendar API can't recognize you json. Header of http-request MUST contain "Content-Type: application/json". See here: https://stackoverflow.com/questions/37535563/missing-end-time-with-google-calendar-and-racket-google-package?rq=1

**Comment by dumkanki** [comment]
End time is provided again giving error
 var updatedata = {
            "calendarId": data.googleCalendarId,
            "resource": {
                "end": {
                    "dateTime": data.endTime,
                    "timeZone": 'Asia/Dhaka'
                },
                "start": {
                    "dateTime": data.startTime,
                    "timeZone": 'Asia/Dhaka'
                },
                "sendNotifications": true,
                "summary": data.description,
                "description": data.description,
                "location": data.location,
                "attendees": [{
                    "email": data.email,
                    "displayName": data.name,
                    "responseStatus": "needsAction",
                    "resource": false,
                    "optional": false,
                    "organizer": false,
                }]
            },
        }
        return function (dispatch) {
            return axios
                .post(`https://www.googleapis.com/calendar/v3/calendars/${data.googleCalendarId}/events?key=${data.apiKey}`, { updatedata })
                .then(res => {
                    console.log("nnnnnnnnnnnnnnn", res)
                    return res;        
                })
                .catch(err => {
                    toastr.error("Something went wrong, Please try again");
                });
        }
can someone help me to find solution
