### ISSUE TITLE
Add support for google cloud print 

### ISSUE THREAD

**Issue by gkorland** [google/google-api-nodejs-client#568]
Add support for google cloud print for a server side print.

**Comment by jmdobry** [comment]
This client library cannot support the Google Cloud Print API, because the Cloud Print API does not follow the same format as the APIs supported by this library. This library can only support APIs that follow the format of the APIs found [here](https://www.googleapis.com/discovery/v1/apis).

**Comment by gkorland** [comment]
@jmdobry do you have a suggestion where should it fit?

**Comment by jmdobry** [comment]
As far as I know, there isn't any Node.js client library that supports the Cloud Print API. Your options are:

* Formulate the http request manually using something like [request](https://www.npmjs.com/package/request)
* Write the client library yourself
