### ISSUE TITLE
doc bug

### ISSUE THREAD

**Issue by windmaple** [google/google-api-nodejs-client#570]
Spotted a doc bug on this page:
[(http://google.github.io/google-api-nodejs-client/5.2.0/adexchangeseller__.html)]

For <static> adexchangeseller.accounts.reports.generate(params, callback), there is no way 'metric' is string. It should be an array. You could specify a bunch of metrics to generate the report. I tried '                    metric: ['AD_REQUESTS', 'AD_REQUESTS_COVERAGE',
                        'COST_PER_CLICK', 'AD_REQUESTS_RPM', 'EARNINGS'],' 

and it worked. If you look at python doc, you know it's array as well.

'dimension' should be the same case. There might be others as well.

**Comment by jmdobry** [comment]
You'll need to report this on the [API reference page](https://developers.google.com/ad-exchange/seller-rest/reference/v2.0/accounts/reports/generate#parameters) (click "Send Feedback"), as this client library has no control over the parameter descriptions provided by the API itself.

**Comment by ace-n** [comment]
(Closing this, since it's stale and presumably was reported elsewhere . @windmaple, feel free to reopen if this is still an issue for you.)
