### ISSUE TITLE
Stream comments

### ISSUE THREAD

**Issue by IonicaBizau** [google/google-api-nodejs-client#574]
Is there any API to stream the live comments?

Thanks!

/cc https://github.com/IonicaBizau/youtube-api/issues/43

**Comment by JustinBeckwith** [comment]
Greetings!  There's no streaming variant of this API, but the standard API seems to support polling features that make this kind of usage easier:
https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list

Hope this helps!

**Comment by IonicaBizau** [comment]
Thanks,  @JustinBeckwith! :+1:
