### ISSUE TITLE
Can we  use App scripts code   to create a google from and post response in google spreadsheet.

### ISSUE THREAD

**Issue by varunpal7** [google/google-api-nodejs-client#576]
Can we use the app scripts code to create google forms and post the response from google form into google spreadsheet.Is there any rest API's exposed to do so or any sample app script code ?

**Comment by jmdobry** [comment]
* Create a form via App Scripts: https://developers.google.com/apps-script/reference/forms/form-app#createtitle
* Programmatically respond to a form: https://developers.google.com/apps-script/reference/forms/form-response#withitemresponseresponse and https://developers.google.com/apps-script/reference/forms/form-response#submit

For example

```js
// Open a form by ID and create a new spreadsheet.
 var form = FormApp.openById('1234567890abcdefghijklmnopqrstuvwxyz');
 var ss = SpreadsheetApp.create('Spreadsheet Name');

 // Update form properties via chaining.
 form.setTitle('Form Name')
     .setDescription('Description of form')
     .setConfirmationMessage('Thanks for responding!')
     .setAllowResponseEdits(true)
     .setAcceptingResponses(false);

 // Update the form's response destination.
 form.setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId());
```

Responses to a form are posted to the form's destination spreadsheet.

**Comment by saumyasinghal747** [comment]
How can I do this using the Node.js client?
