### ISSUE TITLE
Add YouTube upload examples

### ISSUE THREAD

**Issue by bradorego** [google/google-api-nodejs-client#577]
Nothing too fancy here, but I'm trying to use the YouTube API and I'm basically brute-forcing my way to success. I've got playlist creation down so far, and I can upload a video, but I haven't figured out how to set information about the video (e.g. title, privacy, etc) and it's really frustrating. This would be a lot easier if there were examples to work off of.

**Comment by stephenwithav** [comment]
@bradorego I'm about to tread down this same path.  Did you ever have any success?

**Comment by bradorego** [comment]
I had to dig through some old code (as I'm no longer working on this project) but I think this might be helpful?

`var uploadVideo = function (file, title, description) {
  var d = $q.defer();
  youtube.videos.insert({
    part: 'snippet,status',
    resource: {
      snippet: {
        title: title,
        description: description
      },
      status: {
        privacyStatus: "unlisted"
      }
    },
    media: {
      mimeType: file.mimetype,
      body: fs.readFileSync(file.path)
    }
  }, function (err, result, response) {
    if (err) {
      console.error(err);
      return d.reject(err);
    }
    del.sync([file.path]); /// clean up file after upload success
    d.resolve(result);
  }); /// end video upload
  return d.promise;
};`

**Comment by stephenwithav** [comment]
Thank you, sir!  That'll save me a good bit of time reading through the API re: `part`. :)

**Comment by jmdobry** [comment]
Sorry there's no explicit example. I just looked, this library currently supports 4,227 API calls across 155 different Google APIs 😮 

Luckily, the API reference documentation is complete for the Youtube API. Here's the relevant bit that details the properties available on the `resource` object shown in the example above: https://developers.google.com/youtube/v3/docs/videos#resource
