### ISSUE TITLE
For Google forms how to use app scripts outside the google form script editor

### ISSUE THREAD

**Issue by apasrini** [google/google-api-nodejs-client#578]
Trying out google form app scripts. Wanted to know if there is a way where we can try this app scripts outside the code editor. ?

How we get the forms without using activeForm method.

Is there a way to get the form id with the name of the form ?

<your detailed question and code samples go here>

Thanks!

**Comment by jmdobry** [comment]
This library/repository has no relation to google form app scripts. You're better off asking this question through the [App Script Support channels](https://developers.google.com/apps-script/support)
