### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by ehsandotnet** [google/google-api-nodejs-client#580]
Hi

As you know google provides a facility for clients of API to be informed when a user changes something in his calendar so client can update/sync itself with the server of calendar.
https://developers.google.com/google-apps/calendar/v3/push
I just want to know if you expose anything on your library for using push notifications?

**Comment by jmdobry** [comment]
Yes, here are the API docs for this library for the calendar v3 API: http://google.github.io/google-api-nodejs-client/latest/calendar.html

> Each watchable Google Calendar API resource has an associated watch method at a URI of the following form:
>
> ```
> https://www.googleapis.com/apiName/apiVersion/resourcePath/watch
> ```
> To set up a notification channel for messages about changes to a particular resource, send a POST request to the watch method for the resource.

> Each notification channel is associated both with a particular user and a particular resource (or set of resources). A watch request will not be successful unless the current user owns or has permission to access this resource.

For example:

```js
var channel = {
 id: 'channel-id',
 type: 'channel-type',
 address: 'channel-address'
}
calendar.events.watch({
  auth: authClient,
  calendarId: 'my-calendar-id',
  resource: channel
}, function (...) {...})
```

**Comment by vramana** [comment]
@jmdobry The docs [here](https://github.com/google/google-api-nodejs-client/blob/6ee07c93a938e3d1efb23b8fd3ab8de77b946186/apis/calendar/v3.js#L1277) seem to not reflect that at all. Am I missing something?

**Comment by tarun14691** [comment]
@vramana : If you can be specific about your issue. I can help. 

I just completed work on PUSH API.  The above example code by @jmdobry is for Node js / Javascript client.
And yes its not present in the documents.

**Comment by vramana** [comment]
I found my answer. The documentation seems to be just lacking. Fixing that will be great.
