### ISSUE TITLE
Unable to get response from monitoring.projects.timeSeries.list google api 

### ISSUE THREAD

**Issue by sbsomya** [google/google-api-nodejs-client#582]
Hi used the below code to get the timeseries data 

`
monitoring.projects.timeSeries.list({name : projectName, resource : {}, auth : jwtClient}, function (err2, data) {
        if(err2){
            console.log(err2);
        }else{
           console.log(data);
        }
    });
`

Getting invalid data a html saying Your client has issued a malformed or illegal request.

**Comment by jmdobry** [comment]
Your request is missing some required parameters. You need to provide `interval.endtime` (something like `2016-05-17T14:42:35.883Z`) and possibly a `filter`. You can experiment right here: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#try-it

**Comment by sbsomya** [comment]
Even after providing those parameters then also same error is coming

**Comment by sbsomya** [comment]
If i send resource as key then it was failing

How to send the query string in the get request

**Comment by neoadventist** [comment]
@sbsomya what if you tried (new Date()).toTimeString() or something like that?

**Comment by ericuldall** [comment]
The reason you got that error is because interval.endTime does not denote a json object. That is the exact value of the get parameter being sent. So in order to create a valid json params object for this library you need to do the following:

```
var params = {
    name: "projects/" + project,
    filter: filter,
    "interval.startTime": "2017-04-12T00:00:00.000Z",
    "interval.endTime": "2017-04-13T00:00:00.000Z",
    auth: authClient
};
```

I hope this helps anyone else coming across this stale issue.

**Comment by ace-n** [comment]
(Marking this as closed due to staleness, feel free to reopen if this is no longer the case. Thanks!)

**Comment by liambaloh** [comment]
I came across this thread when working with an alpha api without proper support in clients so wanted to write the encoding solution which worked in response to the error. When an API asks for an object in the query parameters, each individual value of a base type needs to be fully written out in the url being called.

In the case of `interval` this means the URL call will look something like:
`https://playdeveloperreporting.googleapis.com/v1alpha1/apps/APP_NAME_HERE/errorIssues:search?pageSize=1000&interval.startTime.year=2022&interval.startTime.month=10&interval.startTime.day=01&interval.startTime.hours=00&interval.startTime.minutes=00&interval.startTime.seconds=00&interval.startTime.nanos=0&interval.endTime.year=2022&interval.endTime.month=10&interval.endTime.day=31&interval.endTime.hours=00&interval.endTime.minutes=00&interval.endTime.seconds=00&interval.endTime.nanos=0`

The underlying data structure is:
```
interval{
  startTime{
    year, month, day, hours, minutes, seconds, nanos: Integer
  },
  endTime{
    year, month, day, hours, minutes, seconds, nanos: Integer
  }
}
```
