### ISSUE TITLE
Can't retrieve the play store reviews for my app

### ISSUE THREAD

**Issue by djandreski** [google/google-api-nodejs-client#589]
I am trying to get the reviews for my app from the playstore using the new reviews api from the android publisher service.
The app key is _me.jadi_ (https://play.google.com/store/apps/details?id=me.jadi) as you can see it have reviews posted for it.

Here is the code I'm using:
```javascript
var google = require('googleapis');
var secrets = require('./secrets.json');
var androidpublisher = google.androidpublisher('v2');

var authClient = new google.auth.JWT(
	secrets.client_email, null, secrets.private_key, 
	['https://www.googleapis.com/auth/androidpublisher'], null);

authClient.authorize(function (err, tokens) {
  if (err) {
    return console.log(err);
  }
  androidpublisher.reviews.list({ auth: authClient, packageName: 'me.jadi' }, function (err, resp) {
    if (err) {
      return console.log(err);
    }
  });
});
```
It doesn't contain any errors for the auth nor for the actual service request. But the result is always an empty object.
So I'm trying to identify the problem, 

- is there something wrong with the code
- do I need to opt-in specifically somewhere to use the API
- does the API have any limitations, like geographic (the service is allowed only for the US devs)
- or maybe the service have some bugs because it is still in beta

**Comment by djandreski** [comment]
I found the answer my self, and I'll post it here for future reference.

The problem with my specific case was that I didn't have reviews posted or modified in the last week. 
And the API documentation clearly states that it will keep history of the reviews in the last seven days.

Once I get a new review I tried the code and the review was successfully retrieved.

I'am closing this issue.

**Comment by saxx** [comment]
@djandreski Thank you for your own answer to your question - I had the exact same problem and it really saved me from from getting crazy ;-) 

I cannot find the in the API docs where it mentions the last seven days, but I'll take your word for it. Did you ever find a way to retrieve all reviews from the API (regardless of their date)?

**Comment by djandreski** [comment]
@saxx Take a look at this page https://developers.google.com/android-publisher/reply-to-reviews
There is this note there, maybe you'll find it helpful
![image](https://cloud.githubusercontent.com/assets/1291286/18380595/5affcdd8-7678-11e6-8460-3a365dbe1119.png)
