### ISSUE TITLE
CloudStorageTools::getImageServingUrl for Node.js

### ISSUE THREAD

**Issue by Vani-gurnani** [google/google-api-nodejs-client#592]
Hello,

GCS has an awesome feature ImageServingUrl with passing Google Cloud Storage URL gs://bucket/filename.jpg and size. Currently this API is available in PHP and other SDK's but not in Node.js.

Just for getting this URL we are forced to create PHP instances. It would be great if this API can be available directly in Node.js SDK.

**Comment by jmdobry** [comment]
Unfortunately, the PHP library you're referencing is not comparable to this library. The `getImageServingUrl` method you reference is a feature of the App Engine Standard Environment PHP SDK, for which there is no Node.js offering (Node.js is only available in App Engine Flexible Environment).

google-api-nodejs-client is an auto-generated client library and only supports the methods and APIs available in the [Google API Discovery docs](GET https://www.googleapis.com/discovery/v1/apis). The best option for accessing Google Cloud Storage APIs in Node.js is to use the idiomatic [gcloud-node](https://googlecloudplatform.github.io/gcloud-node/#/docs/storage) library.
