### ISSUE TITLE
Regarding the GMB OAuth2

### ISSUE THREAD

**Issue by prashant7july** [google/google-api-nodejs-client#595]
Hi,

As per the sample code in google-api-nodejs-client/samples/oauth2.js

I am using the code for Google My Business and run and enter the random code in "Enter the code here:" but I am still getting the error. Why? How am I able to get that Code?

Visit the url:  https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.business.manage&response_type=code&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXX&redirect_uri=http%3A%2F%2Fnfx.dev.canbrand.in%3A1338%2F

Enter the code here:876876
876876
An error occured [Error: No access or refresh token is set.]

Quick response is very appreciable.
Thanks In advance

**Comment by ace-n** [comment]
Hi @prashant7july and @JesseCogolloAdvice - is this still an issue for either of you? If not, mind if I close this?

**Comment by JesseCogolloAdvice** [comment]
Works for me.

**Comment by JustinBeckwith** [comment]
If this is still an issue, please let us know!
