### ISSUE TITLE
Add Google Play Developper Console API

### ISSUE THREAD

**Issue by commit-master** [google/google-api-nodejs-client#603]
Hello,

Is it possible to integrate the Google Play Developper Console API ? I know there are a few unofficial one out here, but most of them are out-dated, or impossible to adapt. It would be great if we could retrieve and pull out our Applications stats (like downloads, installs, crashes, sales etc.)

If you cannot make this happen, then maybe you could address with materials/resources that could help me achieve this

 #Thanks!

**Comment by jmdobry** [comment]
Could you be more specific as to what API referring to? Unless the API has a discovery doc (like [these](https://www.googleapis.com/discovery/v1/apis)) then this library can't support it.
