### ISSUE TITLE
Security vulnerability in tough-cookie through request

### ISSUE THREAD

**Issue by holm** [google/google-api-nodejs-client#608]
`tough-cookie` has a ReDOS vulnerability that is fixed in 2.3.0. This repo depends on `request`, which has recently been updated to require the fixed version. See https://nodesecurity.io/advisories/130.

It would be great if this could be updated to support 2.74.0 of `request` and released.

Note that `google-auth-library` also requires `request`, so this will need be updated also, and the updated version used here also.

**Comment by holm** [comment]
Issue for `google-auth-library` filed at https://github.com/google/google-auth-library-nodejs/issues/90

**Comment by jmdobry** [comment]
Thanks for pointing this out.
