### ISSUE TITLE
Support for Google Photo uploads

### ISSUE THREAD

**Issue by lowagner** [google/google-api-nodejs-client#610]
would be really nice.  saw the closed picasa support request (https://github.com/google/google-api-nodejs-client/issues/292), but thought that Google Photos would be supported long term.

can't find it in the developer APIs, but here's hoping.

**Comment by jmdobry** [comment]
There's no Google Photos API at this time.

**Comment by batuypn** [comment]
There is now. Any plans for it?

**Comment by mrodrig** [comment]
+1 for adding Google Photos.
