### ISSUE TITLE
Failed to export a file using drive API

### ISSUE THREAD

**Issue by enobufs** [google/google-api-nodejs-client#618]
I am using:
* googleapis@12.3.0
* node@4.3.2

I was trying to download a spreadsheet using Drive API v3 like this:
```js
drive.files.export({
    fileId: <some-valid-file-id>
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
}, (err, buf) => {
    if (err) {
        console.log('Error:', err);
        return;
    }

    console.log('Received %d bytes', buf.length);
    fs.writeFileSync('./out.xlsx', buf);
});
```

Resulting file was corrupted. Same situation with 'application/pdf' - I could not open them.
After some investigation, I noticed that node-request module downloads data as string (decoded as utf8) by default unless you specify encoding option set to `null`. (what I am downloading here are binary files!)

```
// cited from - https://github.com/request/request
encoding - Encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.)
```

By adding a line in drive.files.export() function like below, I was able to download the file successfully:
```js
// ./apis/drive/v3.js
    export: function (params, callback) {
      var parameters = {
        options: {
          url: 'https://www.googleapis.com/drive/v3/files/{fileId}/export',
          method: 'GET',
          encoding: null // <===== added line
        },
        params: params,
        requiredParams: ['fileId', 'mimeType'],
        pathParams: ['fileId'],
        context: self
      };
```

I am aware this file is generated with swig, and probably other methods (like drive.files.get with "alt" set to "media" for binary data) are suffering from the same problem, I do not have sufficient knowledge to propose most effective solution to this. I hope some one could come up with a good idea to this problem.

**Comment by jmdobry** [comment]
Does this sample not work for you?

https://developers.google.com/drive/v3/web/manage-downloads#downloading_google_documents

**Comment by enobufs** [comment]
@jmdobry Nope.  I am seeing exactly the same situation reported as #501 - I get the token object, too. I think the write stream is broken somewhere. So, I switch to use the callback, the I came across the default encoding problem of node-request.

**Comment by enobufs** [comment]
I think the best way is to provide an option to switch the response body type to `Buffer` for backward compatibility. (Buffer should have been the first choice to my eye tho because if you need to a string with utf8 or whatever, you can do so by Buffer#.toString(<encoding>).

In the next major release, we should drop the original behavior (using utf8/String by default) along with this option, do everything with Buffer, IMO.

**Comment by jmdobry** [comment]
I just updated my PR with a second `export.js` sample which shows how to download a Google Doc as a PDF: https://github.com/google/google-api-nodejs-client/pull/617/files#diff-5c746a979c55ea3aefba1a68027030ba

I just ran the sample locally and was able to download a Google Doc as a PDF to my local computer. You can fiddle with the sample (change the mimeType) to have it download your spreadsheet.

**Comment by enobufs** [comment]
I tried export.js and it works!

I guess the encoding issue only arises when you use callback on export() method...

I swapped the part of example.js with the following. Download data is corrupted.
```js
    drive.files.export({
      fileId: fileId,
      mimeType: 'application/pdf'
    }, function (err, res) {
        if (err) {
            console.log('Error:', err);
            return;
        }

        console.log('Received %d bytes', res.length);
        console.log('Type of res:', typeof res);
        fs.writeFileSync('./' + metadata.name + '.pdf', res);
        process.exit();
    });
```
In some cases, doing some further processing with downloaded data on memory might be desired, in which case, callback style might be more natural than the use of stream. I'd actually like to export file to xlsx file then use npm xlsx tool to parse the data on memory...

**Comment by jmdobry** [comment]
> In some cases, doing some further processing with downloaded data on memory might be desired

You can certainly do that. You don't have to pipe the request stream to a file, you can collect the data yourself:

```
npm install --save concat-stream
```

```js
var concat = require('concat-stream');
var concatStream = concat(gotFile);

drive.files.export({
  fileId: fileId,
  mimeType: 'application/pdf'
}).on('error', handleError).pipe(concatStream);

function gotFile (buffer) {
  // "buffer" contains the downloaded binary data
  // Do with it what you will
}

function handleError (err) {
  console.log(err);
}
```

**Comment by enobufs** [comment]
Yes. I was just trying to say some people, like myself, would try to use callback (second arg in export), which doesn't seem to work. I guess there needs to be a document explaining this limitation and direct them to use pipe.

Thanks a lot for your revised example!

**Comment by enobufs** [comment]
@jmdobry The request stream in my code still returns the token, then I realized that access token was expired. My expectation is that if it is expired, the API will transparently refresh the access token by using refresh token. I guess what we are seeing in the request stream is the refreshed credentials.

Try to add this line before calling `auth.setCredentials(tokens);` to your export.js example:
```js
tokens.expiry_date = Date.now() - 1;
```

**Comment by jmdobry** [comment]
For what it's worth, the [example in the official documentation](https://developers.google.com/drive/v3/web/manage-downloads#downloading_google_documents) uses `.pipe()`.

I haven't tried this, but maybe this would work:

```js
drive.files.export({
  fileId: fileId,
  mimeType: 'application/pdf',
  encoding: null
}, function (err, file, response) {
  console.log(file); // "file" should be a buffer
  
  console.log(response.body); // "response.body" should also be a buffer
});
```

**Comment by jmdobry** [comment]
Do you have an example I could debug to reproduce the problem you're seeing?

**Comment by enobufs** [comment]
[export_1.js](https://gist.github.com/enobufs/3b668ea77dce1d1acef36eb99ccd7a11#file-export_1-js)
* This sample is using callback on export() method.
* The callback returns `res` which is a string containg incorrectly encoded binary data as utf8.

[export_2.js](https://gist.github.com/enobufs/3b668ea77dce1d1acef36eb99ccd7a11#file-export_2-js)
* This sample forces to expire tokens by setting expiry_data to past time.
* The output data in the file contains tokens instead of a pdf file.

**Comment by jmdobry** [comment]
In [export_1.js](https://gist.github.com/enobufs/3b668ea77dce1d1acef36eb99ccd7a11#file-export_1-js), does it work if you do:

```js
drive.files.export({
  fileId: fileId,
  mimeType: 'application/pdf',
  encoding: null
}, function (err, res) {
 // ...
});
```

**Comment by enobufs** [comment]
Unfortunately, no.  The `encoding: null` does not get to the options for node-request module... we need to modify apis/drive/v3.js or ./lib/apirequest.js to insert the parameter.

**Comment by jmdobry** [comment]
What about this:

```js
drive.files.export({
  fileId: fileId,
  mimeType: 'application/pdf',
  options: {
    encoding: null
  }
}, function (err, res) {
 // ...
});
```

**Comment by enobufs** [comment]
Nope.. :(  Returned `res` is still a string and data is still corrupted.

**Comment by enobufs** [comment]
I created a branch on my forked repo: https://github.com/enobufs/google-api-nodejs-client/tree/feature/allow-export-binary

I am going to use this to get my work done for now.

**Comment by jmdobry** [comment]
@enobufs I'm think #623 ought to be able to solve this for you (allow you to pass `encoding: null`).

**Comment by jmdobry** [comment]
I released 12.4.0, give it a try:

```js
drive.files.export({
  fileId: 'asxKJod9s79', // A Google Doc
  mimeType: 'application/pdf'
}, {
  encoding: null // Make sure we get the binary data
}, function (err, buffer) {
  // Nice, the buffer is actually a Buffer!
});
```

**Comment by DavidIdentica** [comment]
Hi , I am having the same problem
I am using:
    googleapis@110.0.0
    node@16.13.0
I have tested with and whithout the callback. and sending the "encoding:null" inside parameters , and in Options. 
When the service response , it responses an Object, and the data seems to be in the "data" field. But if I try to save it, the resulted file is always corrupted. 

Here is what Im trying:
`
        let jsonDownlaodFile = {
            fileId: fileId,
            mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            encoding: null   // <= If I debug inside v3.js , this seems to work. 
        }

        return drive.files.export ( jsonDownlaodFile, {encoding: null} , (err,buf) => {
            if (err) {
                console.log('Error:', err);
                return;
            }

            fs.writeFileSync('./out.xlsx', buf.data);
        })
`

This is what it looks inside the buffer. 
![imagen](https://user-images.githubusercontent.com/70664748/209405353-4a56c793-3c7f-40b7-8ec7-497a6bfd8866.png)


And this is the file result as an xlsx. 


![ExcelScreen](https://user-images.githubusercontent.com/70664748/209405523-db7aacd6-f38c-4fad-8a37-1c2ced910300.jpeg)

What am I missing ? 
I hope somebody could help me with this. 
Thank you so much in advance.

**Comment by PMobile78** [comment]
@DavidIdentica You should use `responseType: 'stream'`.
Look to https://github.com/googleapis/google-api-nodejs-client

const res = await drive.files.export({
  fileId: 'asxKJod9s79', // A Google Doc
  mimeType: 'application/pdf'
}, {
  // Make sure we get the binary data
  responseType: 'stream'
});

**Comment by DavidIdentica** [comment]
@PMobile78 
Thank you so much. 
That did work for me. 
Just in case somebody need it, Im leaving the code bellow to save the file. 

`
        const jsonDownlaodFile = {
            fileId: fileId, // FILE IDENTIFIER
            mimeType: type ,// application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        }

        const jsonOptions = { 
            responseType: 'stream'
        }

        const res = await drive.files.export( jsonDownlaodFile, jsonOptions );
        //    └-> The result is an Object that contains a data attribute 
        //        this attribute is a PassThrough stream object, that ca be 
        //        saved in the local storage as shown bellow :
        let streamToSave = fs.createWriteStream(fileName);
        res.data.pipe(streamToSave) // The "data" object of "res" is the one that can be Piped

        
        streamToSave.on ('finish',function () { 
            console.log ("Proccess FInished"); 
            streamToSave.close(); 
        });
        streamToSave.on ('close', function () {
            console.log('Stream closed');
            const obj = xlsx_node.parse(fileName);
        });
        streamToSave.on ('error', function (error) { 
            console.log('ErrorStream:' , error) 
        });

`

Thank you again for the support.
