### ISSUE TITLE
directory.orgunits.get params.orgUnitPath not encoded

### ISSUE THREAD

**Issue by wilau2** [google/google-api-nodejs-client#620]
I am using 12.3.0
directory.orgunits.get params.orgUnitPath does not seems to be encoded.
i tried to pass existing orgUnitPath : /Tennis Québec, this was the error :
`
 Error: Org unit not found
`
If we have to encode param before calling api and that it is the expected behavior can we update documentation ? 

Thanks!

**Comment by lukesneeringer** [comment]
@wilau2,
You can encode your URIs with `encodeUriComponent`. I agree that the docs should call this out (or it should just be done).

**Comment by JustinBeckwith** [comment]
Greetings!  We started to encodeURIComponent for path parameters over in #1087.  This should just work now.  Let me know if you run into any issues!
