### ISSUE TITLE
Tokeninfo method returns an error

### ISSUE THREAD

**Issue by simon-tannai** [google/google-api-nodejs-client#626]
Hello,

I try to use tokeninfo method of google api oauth 2. 
I wrote this code:

```
let GetTokenInfo = (googleapi, accessToken) => {
  const OAUTH = googleapi.oauth2('v2');

  return new Promise((resolve, reject) => {
      OAUTH.tokeninfo({access_token: accessToken}, (err, response) => {
        if( err ) {
          reject(err);
        }
        else {
          resolve(response);
        }
      });
  });
};
```

When I send my access token, token info method returns an error:

> No access or refresh token is set

But when I call the URL with the same token in my web browser, I get a good result:
https://www.googleapis.com/oauth2/v2/tokeninfo?access_token=myAccessToken

```
{
 "issued_to": "53933608...",
 "audience": "53933608...",
 "user_id": "11317344...",
 "scope": "https://www.googleapis.com/auth/plus.me https://mail.google.com/ https://www.googleapis.com/auth/drive https://www.google.com/m8/feeds/ https://www.googleapis.com/auth/admin.directory.user",
 "expires_in": 2324,
 "access_type": "offline"
}
```

Some solution ?

**Comment by jmdobry** [comment]
Your code looks like it should work. How are you making the request in the browser? Are you making a GET or POST request?

**Comment by jmdobry** [comment]
Any update?

**Comment by lukesneeringer** [comment]
Hi @simon-tannai,
It has been awhile since we have heard from you on this, so we are assuming your problem is solved, or you moved on. If you are still having this issue, please feel free to reopen.
