### ISSUE TITLE
Cannot stop watching a channel

### ISSUE THREAD

**Issue by jifeon** [google/google-api-nodejs-client#627]
googleapi version: 12.4.0
api version: 3
#### Steps to reproduce
1. Start watching a drive file
   
   ``` js
   drive.files.watch({
     fileId,
     resource: {
       id: 'my-chanel',
       type: 'web_hook',
       address: 'https://example.com/api/gsheets'
     }
   }, (err, result) => {
   ...
   });
   ```
   
   It works good, I get info about channel and start receiving notfnications about changes.
2. Try to stop channel
   
   ``` js
   drive.channels.stop({
     resource: {
       id: 'my-channel',
       resourceId: 'given resource id goes here'
     }
   }, (err, result) => {
   ...
   });
   ```
#### Expected result

Some message about successful operation
#### Actual result

```
error:  Error: Channel 'my-channel' not found for project '636397034666'
    at Request._callback (/Users/jifeon/projects/plyo.web/node_modules/google-auth-library/lib/transporters.js:82:15)
    at Request.self.callback (/Users/jifeon/projects/plyo.web/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/jifeon/projects/plyo.web/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/jifeon/projects/plyo.web/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickDomainCallback (node.js:425:11)
```

and if I try to watch again, it says "Channel id is not unique"

**Comment by jmdobry** [comment]
You might be missing some required properties in your request body (see https://developers.google.com/drive/v3/reference/channels/stop#request-body).

`kind`, `id`, `resourceId`, `resourceUri`, `type` and `address` all appear to be required properties according to that table, but I'm not 100% positive. It may be that the API needs all of those properties to uniquely identify the channel to be stopped.

**Comment by jifeon** [comment]
@jmdobry thx for quick response

It was one first thoughts, so I tried all possible variants including:

```js
drive.channels.stop({
  resource: {
    id: 'my-channel',
    resourceId: 'given resource id',
    resourceUri: 'given resource uri',
    type: 'web_hook',
    address: 'address I used for subscription',
    kind: 'api#channel'
  }
}, (err, result) => {
...
});
```

The same effect. How can I help to reproduce the problem on your side?

**Comment by jmdobry** [comment]
Can you try to stop a channel using the [API Explorer](https://developers.google.com/apis-explorer/#p/drive/v3/drive.channels.stop) and make sure it works there?

**Comment by jifeon** [comment]
Srry for delay. Checked - the same effect there:

![image](https://cloud.githubusercontent.com/assets/384223/18348383/bd43a348-75d3-11e6-9105-81897ca60bba.png)

**Comment by jmdobry** [comment]
Again, I think it needs more than just `id` and `resourceId` to work, i.e. `kind`, `resourceUri`, `type` and `address`

**Comment by jifeon** [comment]
I'm following docs https://developers.google.com/drive/v3/web/push#stopping-notifications

**Comment by jessetane** [comment]
FWIW I'm trying to use the calendar api and can't figure this one out either. I've tried quite a few variations on params and the only response I'm able to get back looks like:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Required"
   }
  ],
  "code": 400,
  "message": "Required"
 }
}
```

**Comment by jessetane** [comment]
Nvm got this to work by passing `id` AND the `resourceId` which is included in the response at creation time.

Still, would be nice to have a better error message.

**Comment by jessetane** [comment]
Also, it's a little weird to not be able to stop channels with the params you used to create them - if you somehow forget to extract the resourceId from the response are you just stuck getting events until you hit the expiration time?

**Comment by jmdobry** [comment]
Glad you got it working.

I may be wrong, but I believe you control the `resourceId`, so you should have it available.

**Comment by TLMcode** [comment]
@jessetane I'm also trying to get the event watch to stop but I didn't store my resourceId. Is there any other way to stop it? What happens if I destroy the entire calendar?

**Comment by SymmetricDesigns** [comment]
Was getting the useless "Required" error above too.  I had forgotten to put the "id" and "resourceId" inside a "resource" object.  This structure is very poorly documented:
`var params = {
  "auth": {  },
  "resource": {
    "id": "...",
    "resourceId": "..."
  }
}`

**Comment by ArseniiPetrovich** [comment]
Yep, having the same problem here. Does anybody have a solution on this? How should we get resourceId if not stored?

**Comment by User1m** [comment]
@SymmetricDesigns that was my "gotcha" too. Agree with the poor documentation sentiments

**Comment by Elyx0** [comment]
Putting it here as a gotcha, the stop event can take a bit of time to propagate, don't assume it's you right away. 🧐

**Comment by RedskyThirty** [comment]
I just found the mistake! Do you get this error at the second call? If yes, so read the doc ;-)
=> If successful, this method returns an **empty response body.**
If you receive an empty response, check the http_code. It should be 204.

**Comment by Pho3nixHun** [comment]
I hit the same wall today and what I found is the `resourceId` returned by the watch method is not the same as I sent. 

The documentation says:

> Watch response
> If the watch request successfully creates a notification channel, it returns an HTTP 200 OK status code.
> 
> The message body of the watch response provides information about the notification channel you just created, as shown in the example below.
> 
> {
> "kind": "api#channel",
>   "id": "01234567-89ab-cdef-0123456789ab"", // ID you specified for this channel.
>   "resourceId": "o3hgv1538sdjfh", // ID of the watched resource.
>   "resourceUri": "https://www.googleapis.com/drive/v3/files/o3hgv1538sdjfh", // Version-specific ID of the watched resource.
>   "token": "target=myApp-myFilesChannelDest", // Present only if one was provided.
>   "expiration": 1426325213000, // Actual expiration time as Unix timestamp (in ms), if applicable.
> }
> 
> In addition to the properties you sent as part of your request, the returned information also includes the resourceId and resourceUri to identify the resource being watched on this notification channel.

Since you are using the same name for those properties and not mentioning anywhere that these are not the same, it is not a miracle that some people gets confused. 
Please fix it in the documentation. I assume the returned `resourceId` is related to the channel itself, and not to the watched resource.

**Comment by Pho3nixHun** [comment]
So to be more precise here, I supplied an ID of a spreadsheet to the watch function, which the service turned into of an ID of the file representing the spreadsheet. So the above documentation is OK as far as you note somewhere that the service will translate the spreadsheet (or any other) id to file id.

ps.: Strange that the drive api accepts spreadsheet `id`s, but the spreadsheet api does not accept file `id`s.

**Comment by isaacbowen** [comment]
@Pho3nixHun I am deeeeply grateful for your comment there. Thank you for solving my headache. :D

**Comment by simonkotwicz** [comment]
The fact that you need the resourceId (which seems to be only returned in the watch request response) to stop events for a particular channel makes channels/events harder to work with.

**Comment by alannesta** [comment]
> I hit the same wall today and what I found is the `resourceId` returned by the watch method is not the same as I sent.
> 
> The documentation says:
> 
> > Watch response
> > If the watch request successfully creates a notification channel, it returns an HTTP 200 OK status code.
> > The message body of the watch response provides information about the notification channel you just created, as shown in the example below.
> > {
> > "kind": "api#channel",
> > "id": "01234567-89ab-cdef-0123456789ab"", // ID you specified for this channel.
> > "resourceId": "o3hgv1538sdjfh", // **ID of the watched resource.** _<- This must be the mistake_
> > "resourceUri": "https://www.googleapis.com/drive/v3/files/o3hgv1538sdjfh", // Version-specific ID of the watched resource.
> > "token": "target=myApp-myFilesChannelDest", // Present only if one was provided.
> > "expiration": 1426325213000, // Actual expiration time as Unix timestamp (in ms), if applicable.
> > }
> > In addition to the properties you sent as part of your request, the returned information also includes the resourceId and resourceUri to identify the resource being watched on this notification channel.
> 
> Since you are using the same name for those properties and not mentioning anywhere that these are not the same, it is not a miracle that some people gets confused. Please **repopen** and fix it in the documentation. I assume the returned `resourceId` is related to the channel itself, and not to the watched resource.

Thanks for the observation!!

**Comment by RishiSargar** [comment]
To set up a webhook, you need to pass the ID and receive the ResourceID in response. 

If you randomly generated the ID and don't have it when you need to stop the channel, don't worry. When a notification is received on your webhook URL, all the details will be in the headers, not the payload. 

By printing the header, you can find the random ID you set for the channel, as well as the ResourceID and other details. The header contains several values, including the channel ID, token, expiration date, ResourceID, URI, resource state, and message number. You can use the ID and ResourceID from the header to stop the channel.
