### ISSUE TITLE
Support for Distance Matrix API

### ISSUE THREAD

**Issue by davidfurlong** [google/google-api-nodejs-client#629]
Hey there,

I'm looking to use the Google [Maps Distance Matrix API](https://developers.google.com/maps/documentation/distance-matrix/), and noticed that it and Google Maps APIs in general were missing from [API Explorer](https://developers.google.com/apis-explorer/#p/). Does that mean that they aren't supported here? 

Thanks!

**Comment by jmdobry** [comment]
This library only supports APIs found here: https://www.googleapis.com/discovery/v1/apis
