### ISSUE TITLE
docs: extend GCE example

### ISSUE THREAD

**Issue by dch** [google/google-api-nodejs-client#63]
The step from Google API explorer to a working example using this api client is a big one. 

Could you extend the example to show creating/deleting firewall & vm? This would clarify most use cases!

**Comment by jmdobry** [comment]
To access the Compute Engine API, you should do so from the [Google Cloud Client Library for Node.js](https://googlecloudplatform.github.io/google-cloud-node/#/docs/compute/0.2.0/compute).

**Comment by stvnwrgs** [comment]
@jmdobry the Google Client Library only supports like 50% of the resources that are available. Some more useful examples would be great. Like for example deleting resources.
