### ISSUE TITLE
call refreshAccessToken and return 401 invalid_grants

### ISSUE THREAD

**Issue by flytofuture** [google/google-api-nodejs-client#632]
Hi,

I have two projects deployed to gcloud, one is for development and another one is for UAT.And the two projects have same source code, just client id and client secret are different. 

I store the refresh token in the database, and will check the access token is expired or not each time. If the access token is expired, than I use the refresh token stored in the database to refresh access token. But the two projects have different results.

The DEV runs great. But UAT return 400: invalid_grants if no user login the website for a long time(4-8 hours).

I do not known where there are some limits that multiple projects have the access to the same user`s google drive or refresh token would be invalid if no user use it for a long time.

Here is my code:
```js
// @params (refreshToken) stored in database
function Auth (refreshToken) {
  this.refreshToken = refreshToken
}

Auth.auth = new googleAuth()
Auth.oauth2Client = new Auth.auth.OAuth2(client_id, client_secret, redirectUris)

Auth.prototype.Oauth2Client = function (cb) {
  if (!Auth.oauth2Client.credentials || !Auth.oauth2Client.credentials.refresh_token) {
    Auth.oauth2Client.setCredentials({
      refresh_token: this.refreshToken
    })
  }

  var expireDate = Auth.oauth2Client.credentials.expiry_date
  var currentTime = (new Date()).getTime()

  if (!expireDate || expireDate <= currentTime) {
    Auth.oauth2Client.refreshAccessToken(function (err, tokens) {
      if (err) {
        cb(err, null)
      }
      if (tokens) {
        Auth.oauth2Client.setCredentials(tokens)
        cb(null, Auth.oauth2Client)
      }
    })
  } else {
    cb(null, Auth.oauth2Client)
  }
}
```
Thank you.

**Comment by jmdobry** [comment]
I'm not sure what the issue could be. Are you still experiencing this issue?

**Comment by flytofuture** [comment]
This issue has been solved.

**Comment by dg92** [comment]
@flytofuture @jmdobry I am not able to refresh token. It gives me invalid_grant error. Please Help

**Comment by gocreating** [comment]
Same problem....
