### ISSUE TITLE
Google sheet API v4: last update date of spreadsheet

### ISSUE THREAD

**Issue by cguedes** [google/google-api-nodejs-client#635]
In the v3 we were able to use the [getInfo](https://developers.google.com/google-apps/spreadsheets/worksheets#retrieve_information_about_worksheets) operation to access the `updated` response field to know the last update date for the spreadsheet.

How can we get this kind of information with [v4](https://developers.google.com/sheets/reference/rest/v4/spreadsheets/get)?

Since this new version is more HTTP I've looked to the HTTP Response, but found nothing there!

![image](https://cloud.githubusercontent.com/assets/174127/18717772/fd0c92e2-8018-11e6-94cc-fb8e1014484d.png)

CC @mderazon

**Comment by jmdobry** [comment]
I think you want to use https://developers.google.com/drive/v3/reference/files/get and look at the `modifiedTime` property of the response.

**Comment by cguedes** [comment]
Ok. Make some sense to get that info from Drive API. I will read the docs.

**Comment by cguedes** [comment]
I've used the API https://developers.google.com/drive/v3/reference/files/get with success. Tnks for all the help.

Note: We can use the same id for the spreadsheetId and fileId.

**Comment by finoptimal-dev** [comment]
Is it possible to get the update stamp of a specific grid (or range, for that matter)?

**Comment by TheeranMahadev** [comment]
How can i get the modified changes from the Api. No where i can see the Api . could you please help me

**Comment by finoptimal-dev** [comment]
I agree that this would be useful; I don't believe it's available at this time.
