### ISSUE TITLE
Token "expiry_date" format

### ISSUE THREAD

**Issue by teckays** [google/google-api-nodejs-client#636]
Where can I find the format of the value returned for `expiry_date` parameter when getting user's token. I'm trying to store it in a PG database and the value returned is not accepted as a timestamp value.

**Comment by jmdobry** [comment]
Can you show a snippet of your code that shows where you're trying to access `expiry_data`?

**Comment by jmdobry** [comment]
A `number`, representing the number of milliseconds since Unix Epoch.

You can see it being used in [this test](https://github.com/google/google-api-nodejs-client/blob/master/test/test.auth.js), which ought to help you understand it's type/value.
