### ISSUE TITLE
How to use Fitness Google API.

### ISSUE THREAD

**Issue by trunganh07** [google/google-api-nodejs-client#638]
Here is my code:

```js
getLogData: function(tokenType,_tokens,logType, callback)
	{
		var dataSourceId = this.getPath(logType) || "derived:com.google.heart_rate.bpm";
		var OAuth2 = this.oauth2Client();
			OAuth2.setCredentials({
			   access_token : _tokens,
			   refresh_token: _tokens			  
			});
		var fitness = google.fitness('v1');
		fitness.users.dataSources.datasets.get({ 'userId': 'me', 'dataSourceId': dataSourceId, 'datasetId': dt.getTimeDaily()}, function(err, response) 
		{
		    console.log("ABC: ");
		    console.log(JSON.stringify(err, null, 2));
			if(err) callback(err, null);
			callback(null, response);
		}); 
	}
```

Request to server error:

```
{
  "code": 401,
  "errors": [
    {
      "domain": "global",
      "reason": "required",
      "message": "Login Required",
      "locationType": "header",
      "location": "Authorization"
    }
  ]
}
```

Thanks!

**Comment by jmdobry** [comment]
I think you want this:

```js
OAuth2.setCredentials(_tokens);
```

instead of this:

```js
OAuth2.setCredentials({
  access_token : _tokens,
  refresh_token: _tokens             
});
```

**Comment by c0d3blooded** [comment]
I'm getting this error as well even with the right arguments.

`var oauth2Client = new OAuth2(
	googleClientId,
	googleClientSecret,
	googleRedirect
);
// Retrieve tokens via token exchange explained above or set them:
oauth2Client.setCredentials({
	access_token: token.access,
	refresh_token: token.refresh,
	expiry_date: token.expires
});					
console.log("token: ",  token.access);
console.log("token: ",  token.refresh);
console.log("expires: ", token.expires);
var fitness = google.fitness('v1');
var second = 1000;
var day = second * 60 * 60 * 24;
//data request for calories and steps by time
var aggregate_time = {
	'startTimeMillis': fitData.start,
	'endTimeMillis': fitData.end,
	'aggregateBy': [{
		'dataSourceId': calorieDataSource,
		'dataTypeName': 'com.google.calories.expended'
	},{
		'dataSourceId': stepsDataSource,
		'dataTypeName': 'com.google.step_count.delta'
	}],
	'bucketByTime': {
		'durationMillis': day,
		'period': {
			'type': 'day',
			'value': 1,
			'timeZoneId': fitData.zone
		}
	}
};					

//get aggregate data by time
fitness.users.dataset.aggregate({ 'userId': 'me', 'resource': aggregate_time}, 
function(err, response) {
	//aggregate data loaded
	if (!err){
		console.log('result:', response.body);
	} 
	//error loading the fitness data
	else {
		console.log('err:', JSON.stringify(err));	
	}
	resolve();		
}); 				
`
