### ISSUE TITLE
The chromewebstore api is not included

### ISSUE THREAD

**Issue by robblovell** [google/google-api-nodejs-client#639]
The chrome web store api (chromewebstore) has not been included in the javascript client here. 

I would add the chromewebstore api if I had an example of what is at a discovery url. In the contributing section, there are no discovery url's that exist already, and finding one in the code is a bit of a hunt.  

Can the documentation in the contribution section be edited to include an example of what is behind the discovery url so that it is easier to get started contributing?

**Comment by robblovell** [comment]
One note, calling the API directly via rest results in "Internal Server Error".  This code seems like it should work, but doesn't (coffeescript):

```
google = require('googleapis')
request = require 'superagent'

key = require('../../certificates/[Your certificate file here].json')
scopes = ['https://www.googleapis.com/auth/chromewebstore.readonly']
jwtClient = new google.auth.JWT(key.client_email, null, key.private_key, scopes, null)

app_id = "[Your application id here]"

jwtClient.authorize((error, result) ->
    if (error)
        console.log(error)
        return

    console.log("Success: "+JSON.stringify(result,null,3))
    headers = {
        'Authorization': "Bearer #{result.access_token}"
        'x-goog-api-version': "2"
        'Content-Length': "0"
    }
    request.get("https://www.googleapis.com/chromewebstore/v1.1/items/#{app_id}?projection=DRAFT")
    .set(headers)
    .end((error, result) ->
        console.log("Web store response: "+error) if error? # Internal Server Error here...
        console.log("Web store result: "+result) if result?
        return
    )
```

Authentication works, but the result of the get call is an internal server error.

This also results in an "Internal Server Error":

curl \
-H "Authorization: Bearer $TOKEN"  \
-H "x-goog-api-version: 2" \
-H "Content-Length: 0" \
-H "Expect:" \
-X GET \
-v \
https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID?projection=draft

**Comment by jmdobry** [comment]
The Chrome Webstore API has not published their discovery doc to the Google APIs discovery service. If that changes, then the chrome webstore will appear in this library. Until then, you'll have to manually formulate requests according to the available Chrome Webstore API documentation. Sorry about that 😕 

Can you post the actual error that you're seeing?

**Comment by jmdobry** [comment]
It seems the discovery doc for the Chrome Webstore API has appeared in the Google discovery service: https://www.googleapis.com/discovery/v1/apis/chromewebstore/v1.1/rest

At this moment, you could use it like this:

```js
var google = require('googleapis');

/**
 * This assumes that you've set the following environment variables:
 *
 * - GCLOUD_PROJECT - Your Google Project ID, e.g. my-awesome-project-123
 * - GOOGLE_APPLICATION_CREDENTIALS - The path to your Service Account key file, e.g. /path/to/keyfile.json
 *
 * You don't have worry about these env vars if running on GAE Flex or a GCE
 * instance created with the proper scopes.
 */
function auth (callback) {
  google.auth.getApplicationDefault(function (err, authClient) {
    if (err) {
      callback(err);
      return;
    }

    if (authClient.createScopedRequired && authClient.createScopedRequired()) {
      authClient = authClient.createScoped([
        'https://www.googleapis.com/auth/chromewebstore.readonly'
      ]);
    }
    callback(null, authClient);
  });
}

var discoveryURL = 'https://www.googleapis.com/discovery/v1/apis/chromewebstore/v1.1/rest';

google.discoverAPI(discoveryURL, function (err, chromewebstore) {
  if (err) {
    throw err;
  }

  auth(function (err, authClient) {
    if (err) {
      throw err;
    }

    chromewebstore.items.get({
      auth: authClient,
      itemId: 1234,
      project: 'DRAFT'
    }, function (err, item) {
      if (err) {
        throw err;
      }

      console.log(item);
    });
  });
});
```

Once I regenerate this library then you'll be able to use it this:

```js
var google = require('googleapis');
var chromewebstore = google.chromewebstore('v1.1');
```

**Comment by r-obert** [comment]
`require('googleapis').chromewebstore` returns undefined and same for `.webstore`. 
looks like it has been removed? 😞
