### ISSUE TITLE
Sheets API batchGet ranges parameter

### ISSUE THREAD

**Issue by zBuffer** [google/google-api-nodejs-client#644]
The 'ranges' parameter in batchGet should accept an array of strings? Otherwise it's impossible to specify multiple ranges for batchGet to work.

Have tried JSON encoding my array to a string, joining my array with a comma, all gave me 400 malformed request.

**Comment by jmdobry** [comment]
Does this work?

```js
ranges: encodeURIComponent(['A1:B2', 'C1:D2'].join(,))
```

**Comment by zBuffer** [comment]
Well technically it shouldn't because the actual REST API spec should
accept only something like ranges=A1:B2&ranges=C1:D2... and not
ranges=A1%XXB2%XXC1%XXD2

The wrapper API is fundamentally incorrect to begin with by not accepting
an array of strings (and translating them to multiple ranges=xxx& when
encoding the URI)

Anyhow I will test this once I get my hands on my IDE. Thanks!

**Comment by jmdobry** [comment]
Also, can you paste here the final URL you see generated by this library when you make the request?

**Comment by zBuffer** [comment]
It didn't work, still getting bad request error. I'm not sure how to output
the final URL generated by this library.

**Comment by jmdobry** [comment]
Something like this:

```js
sheets.spreadsheets.values.batchGet({
  // your options
}, function (err, data, response) {
  console.log(response.req.res.request.url);
});
```

The third argument passed to the callback contains the full Express.js response object. You can inspect it to find the full request url.

**Comment by zBuffer** [comment]
Sorry for the late reply. Here's a snippet without using the
encodeURIComponent

  path:
'/v4/spreadsheets/1J3ZbANk4Oa2R3wiQElMNiKb3QAuWUV9A53DaIbbb77g/values:ba
tchGet?ranges=%27Order%20Tracking%20%282016%20Q4%29%27%21A195%3AAF195%2C%27Order
%20Tracking%20%282016%20Q4%29%27%21A248%3AAF248%2C%27Order%20Tracking%20%282016%
20Q4%29%27%21A261%3AAF261%2C%27Order%20Tracking%20%282016%20Q4%29%27%21A267%3AAF
267%2C%27Order%20Tracking%20%282016%20Q4%29%27%21A271%3AAF271%2C%27Order%20Track
ing%20%282016%20Q4%29%27%21A282%3AAF282%2C%27Order%20Tracking%20%282016%20Q4%29%
27%21A292%3AAF292%2C%27Order%20Tracking%20%282016%20Q4%29%27%21A299%3AAF299%2C%2...

**Comment by lukesneeringer** [comment]
Hi @zBuffer,
The answer is that you do need to encode URIs. This is working as intended, as best as I can tell.

**Comment by zBuffer** [comment]
Hi Luke,

Not sure if you've double checked the outputs, it's not working even with
URI encoding - simply because the server expects it to be encoded
differently than how this library generates it.

**Comment by artisonian** [comment]
I've run into the same issue...as I set through the debugger, I can see the problem is API incompatibility between [axios](https://www.npmjs.com/package/axios) and [Request](https://www.npmjs.com/package/request). Because I'm using `auth` param, the HTTP transport is being delegated by `google-auth-library` (which uses Request). Thus, the `paramsSerializer` option is never used.

**Comment by marneborn** [comment]
I'm using auth as well (so request instead of axios).

The only way I could get batchGet to work is:
```
  return Promise.fromCallback(callback => {
    google.sheets('v4').spreadsheets.values.batchGet(
      {
        auth,
        spreadsheetId,
      },
      {
        useQuerystring: true,
        qs: { ranges },
      },
      callback
    );
  })
```
