### ISSUE TITLE
can I authenticate an android native client?

### ISSUE THREAD

**Issue by bogomips** [google/google-api-nodejs-client#652]
Hi, does this lib work with android native?
The screen on the console does not contains the client_secret so in the code I tried to remove it or set to undefined like var oauth2Client = new OAuth2('xxxxxxx-xxxxxxxxx.apps.googleusercontent.com',undefined); 
I keep getting anauthorized_client or invalid_request depending on how I set the REDIRECT_URL.
Any idea? 
Thanks

UPDATE:
In the end I used the web client with his id and secret.
The app is ionic2 but uses a native plugin, at this point i am just a little bit confused.
If someone would like to clarify the situation, It would be apreciated

**Comment by jmdobry** [comment]
This library only works in Node.js

**Comment by c0d3blooded** [comment]
Is there no way to use an Android client side code with this library as per:
https://developers.google.com/identity/sign-in/android/offline-access  ?

**Comment by jmdobry** [comment]
I don't see how, this is a Node.js library. You probably want to look at https://github.com/google/google-api-java-client
