### ISSUE TITLE
Insert column to spreadsheet: the docs have it wrong

### ISSUE THREAD

**Issue by qodesmith** [google/google-api-nodejs-client#663]
I believe the documentation on Google's site gives an incorrect example concerning inserting a column into a Google Spreadsheet. The URL in question is here: [https://developers.google.com/sheets/samples/rowcolumn](https://developers.google.com/sheets/samples/rowcolumn)

In the "**Insert an empty row or column**" section, the example uses `inheritBefore` when in fact it should be `inheritFromBefore`. The error message from the server was thankfully verbose enough to point this out.

**Comment by JustinBeckwith** [comment]
Thanks for reporting the bug!  Since this isn't an issue specific to this library, I've gone ahead and created an issue over here:
https://issuetracker.google.com/issues/77300253

Feel free to follow!
