### ISSUE TITLE
Large file uploads terminating with ECONNRESET

### ISSUE THREAD

**Issue by sbeckwithiii** [google/google-api-nodejs-client#666]
Howdy,

We are attempting to build out an internal Node.JS v6.x web application that may interface with our Google Drive on our Google Apps account, hosted on our Google Cloud account. Our Node.JS application only interacts with the Google APIs via this NPM.

We authenticate via a OAuth2 client ID that was created and is managed on the Google Cloud Console for our Google Cloud account (https://console.cloud.google.com/apis/credentials). Then our Google Apps account, e.g. "appsuser@mydomain.com", accepts and allows the Node.JS application. However, we've run into two issues. The first issue we'll skip in this ticket.

The second issue occurs whenever we try to upload files that take longer than 3 minutes (I believe 3 minutes exactly); our upload is terminated due to a "ECONNRESET" error:

```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TLSWrap.onread (net.js:564:26)
  cause: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1036:11)
       at TLSWrap.onread (net.js:564:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  isOperational: true,
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read' }
```

We pass a stream as the media payload:

```
  const uploadOptions = {
    resource: {
      name: 'test.file.blob',
      description: 'my description goes here',
      parents: [parentFolderID],
    },
    body: {},
    media: {
      body: fs.createReadStream(fileFullPath),
    },
    uploadType: 'multipart',
  };

GOOGLE_DRIVE.files.create(uploadOptions, function(err, data) {
  // ...
});
```

Why did a 10GB upload work fine in #105, ryanseys' comment https://github.com/google/google-api-nodejs-client/issues/105#issuecomment-49806756? Thoughts as to why our large upload is not working?

**Comment by sbeckwithiii** [comment]
I think the second issue is due to not setting the "Content-Length" header.
```
  const uploadOptions = {
    resource: {
      name: 'test.file.blob',
      description: 'my description goes here',
      parents: [parentFolderID],
    },
    body: {},
    media: {
      body: fs.createReadStream(fileFullPath),
    },
    uploadType: 'multipart',
    headers: {
      "Content-Length": fs.stat(fileFullPath).size,
    }
  };

GOOGLE_DRIVE.files.create(uploadOptions, function(err, data) {
  // ...
});
```

I do not have time today to finish testing this but so far the first upload after setting "Content-Length" has run for over 10 minutes, which is quite an improvement.

**Comment by sbeckwithiii** [comment]
Confirmed the issue persists even with content-length set in the headers.
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TLSWrap.onread (net.js:564:26)
  cause: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1036:11)
       at TLSWrap.onread (net.js:564:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  isOperational: true,
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read' }
```

Time varies between 47 seconds and 2 minutes.

**Comment by jmdobry** [comment]
Have you tried a [resumable upload](https://developers.google.com/drive/v3/web/manage-uploads#resumable) instead of a multipart upload?

**Comment by sbeckwithiii** [comment]
Thank you, @jmdobry, for your suggestion however the goal was to replicate https://github.com/google/google-api-nodejs-client/issues/105#issuecomment-49806756 whereby @ryanseys stated a 10gb upload was successful using drive.files.create(). The devs have plainly stated in https://github.com/google/google-api-nodejs-client/issues/105#issuecomment-54089601 they currently will not implement resumable uploads until they determine what such a feature would look like in this library.

I have since moved on from this issue by implemented resumable upload ourselves, passing the oauth tokens generated from the google-api-nodejs-client project into our requests, very much like what @anurag-itsolvs did in #530.
