### ISSUE TITLE
Google Cloud Natural Language

### ISSUE THREAD

**Issue by jcampbell05** [google/google-api-nodejs-client#667]
Is there support for Google Cloud Natural Language ?

**Comment by jmdobry** [comment]
If you want to access the Google Cloud Natural Language API from Node.js, you should use the [Official Cloud client library for the Google Cloud Natural Language API](https://googlecloudplatform.github.io/google-cloud-node/#/docs/language/latest/language)

And here are some samples: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/language
