### ISSUE TITLE
App Engine Search API

### ISSUE THREAD

**Issue by lostpebble** [google/google-api-nodejs-client#668]
I used the App Engine Search API extensively in the previous version of my application. Now that I'm moving over to NodeJS it would be awesome if there was a way I could use it directly from Node. For now, I'm running a whole other Java instance just so I can access it, which isn't very practical.

Is there any way for us to access this API from NodeJS?

For reference, just in case I'm at the wrong place, [this is the API I'm talking about.](https://cloud.google.com/appengine/docs/java/search/)

**Comment by jmdobry** [comment]
I do not believe the App Engine Standard Environment Search API is exposed in any way that this library could access it.

**Comment by lostpebble** [comment]
That's rather disappointing as I find its applications to be very powerful in certain circumstances. For now I'll just continue running some standard App Engine instances to make use of it and hopefully they create better endpoints for it soon.

**Comment by bbhoss** [comment]
Now that Node is available by the standard environment, how do we use this service?

**Comment by raphaelarias** [comment]
It would be great to have Nodejs support.
