### ISSUE TITLE
Google login test automation

### ISSUE THREAD

**Issue by festo** [google/google-api-nodejs-client#671]
We have an application where a user can login with Google or Facebook. The client (iOS and Android) requests an access token and sends it back to our server where [passport-google-token](https://github.com/robertdimarco/passport-google-token) fetches the user information. Everything works fins.

I would like to write some tests for the google token based authentication but I don't want to insert my (test user's) access token every times and actually the tests are running on a CLI machine so I'm not able to insert new tokens ...

For Facebook, I can create new test user with an app token and the Graph API sends back an access token by default. 
https://developers.facebook.com/docs/graph-api/reference/v2.8/app/accounts/test-users

Is there any similar feature for Google. I know I can do some magic with PhantomJS but that wouldn't be the nicest solution.

**Comment by jmdobry** [comment]
You might try https://developers.google.com/oauthplayground/

For reference: http://stackoverflow.com/questions/25657190/how-to-get-dummy-google-access-token-to-test-oauth-google-api

**Comment by andrevinsky** [comment]
Sorry for bringing this up again, @jmdobry. This looks like a prematurely closed question. It seems that the solution involving a playground doesn't allow a pure programmatic way to test tokens. (Again, as @festo rightly noted, Facebook has a test user facility for this. Would be nice if Google did something alike.)

**Comment by JustinBeckwith** [comment]
Greetings folks!  I posed this question internally, and they directed me towards this forum:
https://groups.google.com/forum/#!forum/google-federated-login-api

If a feature like this were available - we would absolutely support it in the client library!  Unless it exists in the underlying service, there ain't a lot we can do in here. 

I'm going to close this issue out for now.  I really would suggest following up on that forum, and letting us know how it goes!

**Comment by BradKwon** [comment]
I came to this post while I am finding a solution for unit testing Google sign-in. Unfortunately, the forum link that @JustinBeckwith mentioned above does not exist anymore. Maybe it was already concluded and there might be new updates on it somewhere else.

**Comment by lamba92** [comment]
News?

**Comment by SAchu47** [comment]
Any new updates arrived?

**Comment by KapitalEarth** [comment]
I success fully put ion food Code for dom. The Turkey may be available, too, if he can turn the key. 

DMC2 will get back to me via any means.

Looking good.

Kind regards,
Richard.

**Comment by KapitalEarth** [comment]
Attached.

**Comment by KapitalEarth** [comment]
Attached#2

**Comment by KapitalEarth** [comment]
Amendment with new alphabet suggestion for Alphabet.
Regards,
R.

**Comment by KapitalEarth** [comment]
Amendment now attached.
R.
