### ISSUE TITLE
Storing access token after automatic refresh

### ISSUE THREAD

**Issue by Alex-Mann** [google/google-api-nodejs-client#673]
What is the conventional way to be informed when the token is updated? I understand that the token is automatically refreshed when the current token becomes expired, but I have not read anywhere how to be informed or store a new token when the old one expires. I was going to use custom logic that I developed with:
```
oauth2Client.refreshAccessToken(function(err, tokens) {
  // your access_token is now refreshed and stored in oauth2Client
  // store these new tokens in a safe place (e.g. database)
});
```
But I have seen that this method has been deprecated. 

What is the proper way to store new tokens with the google API? Updating the documentation to address this would be helpful to many users.

Thanks in advance.

**Comment by k1ng440** [comment]
did you figure it out?

**Comment by nsainaney** [comment]
Took a look at:

google/google-auth-library-nodejs
google-auth-library-nodejs/lib/auth/oauth2client.js

You can retrieve the refreshed token here:

oauth2Client.credentials

So:

```
const that = this;
googleapi.....get({auth: that.oauth2Client}, function(err, response) {
...
    that.oauth2Client.credentials <---- contains the refreshed token
});
```
