### ISSUE TITLE
androidpublisher.edits.tracks.get error

### ISSUE THREAD

**Issue by nightbear1009** [google/google-api-nodejs-client#675]
i am using androidpublisher.edits.tracks.get to get my track versioncode in beta tracks
I follow the document in https://developers.google.com/android-publisher/api-ref/edits/tracks#resource

```js
self.googleClient.publisher.edits.tracks.get({
  editId: self.googleClient.edit.id,
  track: currentTrack
}, function (err, res) {
  if (err || !res) {
    console.log("getTrackInfo err " + err + " " + res);
    reject(err);
  } else {
    console.log("getTrackInfo " + JSON.stringify(res));
    resolve();
  }
});
```

the track param is "beta" but I get errors 
I use "Beta" as param and get correct result.

I think there is something wrong.

**Comment by jmdobry** [comment]
Weird, can you post the errors?

**Comment by rolandjitsu** [comment]
I also get an error if I want to get info about a `alpha` or `beta` track: `Track not found: no APK version codes in the specified track.`. Works for the `production` track though.

**Comment by lukesneeringer** [comment]
Hi @nightbear1009,
Without the error, there is not much we can do to help you. ;.;
Feel free to reopen with the error details if you wish.
