### ISSUE TITLE
Problem with Angular-cli

### ISSUE THREAD

**Issue by diiiiiego83** [google/google-api-nodejs-client#678]
Hi,
I'm having this problem when i try to import the googleapis package (i'm writing a project with angular-cli):
```
ERROR in ./~/google-auth-library/lib/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\ddev\Desktop\WORK\Angular2\oauth2\node_modules\google-auth-library\lib\auth'
 @ ./~/google-auth-library/lib/auth/googleauth.js 21:11-35
 @ ./~/googleapis/lib/googleapis.js
 @ ./src/app/google-auth-api.service.ts
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```
I can't find a solution to fix the issue.

Regards,
Diego

**Comment by cristiancavalli** [comment]
@diiiiiego83 interesting -- thanks for reporting this. May I ask what version of node you are using?

sample command:

```bash
> node --version
v6.3.1
```

`child_process` is a core node module so this seems like node installation issue

**Comment by hernanBeiza** [comment]
Hi! I am having problems too importing this to a Angular 2 Project using Webpack (No Angular-CLI)

./~/googleapis/lib/googleapis.js
Module not found: Error: Can't resolve 'fs' in
...
n ./~/google-auth-library/lib/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' 

My versions:
Node: 6.6.0
NPM: 3.10.7

**Comment by jmdobry** [comment]
This library is Node.js-only. It will never work in the browser.

If you're actually writing some Angular 2 code that will run on the server (e.g. server-side rendering), then your module bundler needs to mark `googleapis` as external dependency, and let Node.js resolve that dependency for you at runtime.

**Comment by skarensmoll** [comment]
Hi there!

Does someone know what we can use instead for angular 10 projects?

Thanks
