### ISSUE TITLE
Can't find method to create new worksheet within existing spreadsheet.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [google/google-api-nodejs-client#683]
There is method: 
```
sheets.spreadsheets.create
```
But as far as I got it right, it create new spreadsheet, not a worksheet within existing one. 
Is it possible at all in api v4?

**Comment by jmdobry** [comment]
I believe you're looking for https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#addsheetrequest

**Comment by AlexanderKozhevin** [comment]
Thanx, @jmdobry !
