### ISSUE TITLE
cant seem to get [spreadsheets.sheets.copyTo] to work..

### ISSUE THREAD

**Issue by hirokun2016** [google/google-api-nodejs-client#684]
Hi,
  I cant seem to get the spreadsheets.sheets.copyTo to work. I have followed everything in the documentation but it still wont work. I am able to successfully perform other commands such as batchUpdate or Create. Can anybody tell me what is wrong with my code or how to make this work? Here is a snippet of my code:

```js
    function copySheet(auth) {
    var sheets = google.sheets('v4');
    var spreadsheetID_foo = 'some spreadSheet ID';
    var spreadsheetID_test = 'another spreadSheet ID';
    sheets.spreadsheets.sheets.copyTo({
        auth: auth,
        spreadsheetId: spreadsheetID_test,
        sheetId: 0,
        resource: {destinationSpreadsheetId: spreadsheetID_foo}
    }, function(err,response){
        if(err) {
            console.log(err);
        }
        console.log('Data :', response);
    });
}
```

**Comment by jmdobry** [comment]
Any updates on this?

**Comment by lukesneeringer** [comment]
Hi @hirokun2016,
We noticed this ticket has been around for awhile with no answer. I am going to go ahead and close it, but feel free to reopen with more information if you wish.
