### ISSUE TITLE
Ability to add comments when editing/appending in a spreadsheet

### ISSUE THREAD

**Issue by chemdrew** [google/google-api-nodejs-client#687]
Would be nice to use the same sheets api to add comments by doing something like this

```
google.sheets.spreadsheets.values.append({
  resource: {
    values: [
      [
        { value: 'row cell text', comment: 'comment on cell' }
      ]
    ]
  }
})
```

where the values are changed from using a string input to an object input. This could also allow for manipulating other properties of the cell like color, etc.

I know this is a feature request for the google sheets api and also might be a pipe dream but I think this ux would open up a lot of possibilities

**Comment by jmdobry** [comment]
[Here is the form](https://code.google.com/a/google.com/p/apps-api-issues/issues/entry?labels=Type-Enhancement,API-Sheets) where you can request a new feature in the Google Sheets API.
