### ISSUE TITLE
possible to get google search results?

### ISSUE THREAD

**Issue by chovy** [google/google-api-nodejs-client#703]
I only see something for google customsearch which from my understand is a custom search for your site.

I'm looking to get results as if I search google.com for `javascript` for example. Interested in first 100 results from past 24 hours.

Is there an example I'm missing? or is it not possible with this api.

**Comment by ace-n** [comment]
Check out the [samples/customsearch](https://github.com/google/google-api-nodejs-client/tree/master/samples/customsearch) directory.

Also, some of the following links may be useful.
- Relevant [StackOverflow post](https://support.google.com/customsearch/answer/2631040?hl=en)
- [Google Custom Search](https://developers.google.com/custom-search/)
- [Using REST](https://developers.google.com/custom-search/json-api/v1/using_rest) with Google Custom Search

Let us know if you have any further questions!

**Comment by jmdobry** [comment]
Sorry, there's no API for Google Search results.
