### ISSUE TITLE
Error 400 (Bad Request) !!1

### ISSUE THREAD

**Issue by raghu64** [google/google-api-nodejs-client#714]
Hi, i am trying to get the list of available tags after creating new tag from google tag manager.

I'm able to create a new tag, but i was getting 400 error from the list response
I used below code to get the list
```javascript
tagmanager.accounts.containers.tags.list(params, function(err, resp){
console.log(resp);
});
```
Response for above api request is 

```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>

```
Its working fine after restarting the server. 

And again if i try to create a new tag and delete it after some time i was gettign the same error.

Thanks!

**Comment by ace-n** [comment]
Hi @raghu64,

Is this still an issue for you? If so, what is your value for `params`?

**Comment by raghu64** [comment]
Hi @ace-n ,

Ya i'm still getting that error. 

params contains accountId and containerId

```javascript
params = {
    accountId: "xxxxxxxxxx",
    containerId: "xxxxxxx"
}
```

**Comment by ace-n** [comment]
How soon are you listing the tags after creating a new one? (Perhaps you need to wait a few seconds between calls?)

**Comment by raghu64** [comment]
I tried that in two scenarios.
1. Wait for couple of seconds after creating tag and then try to list them. -- Mostly throwing error
2. Wait for few minutes and then try to list available tags. -- Sometimes throwing error

**Comment by ace-n** [comment]
@raghu64 How often does the error occur if you wait?

If it's not occurring terribly often or is no longer a problem for you, I'm inclined to close this issue.

**Comment by lukesneeringer** [comment]
I am going to go ahead and close this. Please feel free to reopen if it is still an issue.

**Comment by sixitt** [comment]
xochew cladkix apelcinov
