### ISSUE TITLE
Daily Limit for Unauthenticated User Exceeded 

### ISSUE THREAD

**Issue by Kyle2000** [google/google-api-nodejs-client#723]
So I am making a NodeJS Discord bot, and I'm using this API to extend shortened links. However, when I try to extend any link, it says the I need to signup. How do I signup, and where can I find my API key and use it?

Thanks!

**Comment by ace-n** [comment]
I'm guessing [this](https://developers.google.com/url-shortener/v1/getting_started#APIKey) is what you're looking for?

**Comment by lukesneeringer** [comment]
Hi @Kyle2000,
Thanks for asking. I am hoping the link that @ace-n provided works for you? If not, feel free to reopen this issue.
