### ISSUE TITLE
Problem on JWT Authentication

### ISSUE THREAD

**Issue by peterlaw108** [google/google-api-nodejs-client#724]
Hi,

  I am now trying to use the JWT to access the youtube analytics reports. But the errors is shown:
```
   "reason": "badRequest",
    "message": "Invalid query. Query did not conform to the expectations."
```

  But when i use OAuth2, it's show normal, Could you please help?

  The code is below:

```javascript
  jwtClient.authorize(function (err, tokens) {
  if (err) {
    console.log(err);
    return;
  }
  youtubeAnalytics.reports.query({
    'ids': 'channel==MINE',
    'start-date': '2017-01-01',
    'end-date': '2017-03-31',
    'metrics': 'shares',
    auth: jwtClient
  }, function(err, item) {
      console.log(err);
  });
});
```

Thanks!

**Comment by lukesneeringer** [comment]
Hi @peterlaw108,
Thanks for reporting. We will look into this.

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like service account based access does not work from this API :(

> The YouTube Analytics API does not support the service account flow.

https://developers.google.com/youtube/reporting/guides/authorization/server-side-web-apps

Apologies!  Looks like you need to use OAuth2 here.
