### ISSUE TITLE
Google translate premium via 'nmt' attribute?

### ISSUE THREAD

**Issue by choran** [google/google-api-nodejs-client#725]
Hi, 
I am trying to use this node package with the premium version of google translate but there does not seem to be an option to include the "model":"nmt" attribute in the call the translate.

I have received access to premium translate for my google API account and verified that it worked via a curl. But I cannot get it working with this SDK.

I can see from (this)[https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/translate/translate.js] sdk that it is available in the 'google-cloud/translate' version but it does not seem to be available in the 'googleapis' version. 
1/ Is there some way to access the premium google translate version via the node 'googleapi'?
2/ If not is there a plan to update this version to access it?
Thanks
Cathal

**Comment by ace-n** [comment]
Given that something is in `google-cloud/translate`, it probably won't be duplicated here.

It's worth noting that [Cloud Translate](cloud.google.com/translate) (which [premium translate](cloud.google.com/translate/docs/premium) is a part of and `google-cloud/translate` deals with) is a different product than [Google Translate](translate.google.com) (which is what this repo covers).

**Comment by ace-n** [comment]
(cc'ing @gguuss, as he is more familiar with the various Translate APIs.)

**Comment by jmdobry** [comment]
Currently, `googleapis` uses https://www.googleapis.com/discovery/v1/apis/translate/v2/rest while `@google-cloud/translate` uses https://translation.googleapis.com/$discovery/rest?version=v2. That later API is the one that supports the Premium model.

To use the newer API from the `googleapis` package, the following should work:

```js
const google = require('googleapis');
const discoveryDoc = 'https://translation.googleapis.com/$discovery/rest?version=v2';

google.auth.getApplicationDefault((err, authClient) => {
  if (err) {
    console.error('Failed to load application default credentials!', err);
    return;
  }

  if (authClient.createScopedRequired && authClient.createScopedRequired()) {
    // Scopes can be specified either as an array or as a single,
    // space-delimited string.
    authClient = authClient.createScoped([
      'https://www.googleapis.com/auth/cloud-platform'
    ]);
  }

  google.options({
    auth: authClient
  });

  google.discoverAPI(discoveryDoc, (err, translate) => {
    if (err) {
      console.error('Failed to load translate service!', err);
      return;
    }

    translate.translations.translate({
      resource: {
        model: 'nmt',
        target: 'ru',
        source: 'en',
        q: 'Good morning!'
      }
    }, (err, result) => {
      if (err) {
        console.error('Failed to translate!', err);
        return;
      }

      console.log(JSON.stringify(result, null, 2));
    });
  });
});
```
