### ISSUE TITLE
Blogger Upload image when insert new post

### ISSUE THREAD

**Issue by aalireza439** [google/google-api-nodejs-client#726]
I want to know how I can upload an image when I insert a new post.
Here code i use for insert new post : 

``` javascript
blogger.posts.insert({
  blogId: 'my-blog-id',
  resource: {
    title: 'Post title',
    content: 'Post Content',
  }
}, function(err,output){
	console.log(output)
});
```

**Comment by ace-n** [comment]
Does [this](https://github.com/google/google-api-nodejs-client/blob/master/apis/blogger/v3.js#L1448) help at all?

**Comment by aalireza439** [comment]
no, there is no Property for uploading an image, it seems to google doesn't allow upload image through API.
