### ISSUE TITLE
How do i get asynchronously a job query result with job id 

### ISSUE THREAD

**Issue by jmunozz** [google/google-api-nodejs-client#738]
Hello,
I can't figure out how to perform asynchronous call to API to retrieve results from a query job with just jobId.

I tried bigquery.jobs.getQueryResult(jobId) => bigquery.jobs does not exist
I tried bigquery.getQueryResult(jobId) => the function does not exist

My guess is I first need to get a job ressource then execute ressource.getQueryResult() but I can't find how to get this job resource.

Thanks

**Comment by jmdobry** [comment]
Duplicate of GoogleCloudPlatform/nodejs-docs-samples#374
