### ISSUE TITLE
Isomorphic Web Apps support

### ISSUE THREAD

**Issue by olivierpichon** [google/google-api-nodejs-client#745]
Hi there,

We are currently building an isomorphic Web App which was supposed to use a Google integration.

As stated in [previous closed issues](https://github.com/google/google-api-nodejs-client/issues/26), this library is not supposed to be used client side (e.g google drive is for example trying to call `fs`.)

The Google API Client Library for JavaScript cannot be used server side either (trying to call `document` etc).

Would you guys have any recommendations when trying to build an Isomorphic App (other than using two different libraries)?

Thx a lot!

**Comment by jmdobry** [comment]
You could write your own client for the Google API that you're accessing. You could use a library like [axios](https://github.com/mzabriskie/axios) for the http layer, which has both Node and Browser builds.

**Comment by olivierpichon** [comment]
Thanks a lot Jason!
