### ISSUE TITLE
Google Plus example?

### ISSUE THREAD

**Issue by chovy** [google/google-api-nodejs-client#747]
Is there an example for making a post on your public Google Plus feed using this module?

**Comment by AdityaAnand1** [comment]
@chovy Were you able to figure out how to do this?

**Comment by AdityaAnand1** [comment]
19 days later...I'm still trying to figure this out :(

**Comment by bantini** [comment]
This feature is available only to Google App customers through the Google+ Domain API

https://developers.google.com/+/domains/

**Comment by AdityaAnand1** [comment]
@bantini Thank you for replying. 

Ahh so this library can't be used for that? We have to use the API directly? I'm trying to figure out how the likes of buffer.com or hootsuite schedule posts to g+ profiles and pages.
