### ISSUE TITLE
passing username & password to get access token from redirected url.

### ISSUE THREAD

**Issue by BugDiver** [google/google-api-nodejs-client#749]
After authorisation, I get a URL using that I can generate ACCESS TOKEN. but I need to use a browser to do this. Is there a way to get the access token without any GUI interaction if not logged in? Can I make an HTTP request to get the access token passing my username and password?

Any help on this will be really helpful.

Thanks in Advance.

**Comment by JustinBeckwith** [comment]
Greetings!  It sounds like you're trying to use the OAuth2 workflow, but you probably want a JWT workflow.  OAuth2 requires generating an auth url, redirecting the user to that url in the browser, and obtaining an access token to let you do API calls on their behalf.

The JWT/Service workflow means generating a new set of service credentials, and performing action on behalf of a service account.  It sounds like that's what you want :) . You can see an example of it in action here:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/jwt.js

And a good explanation of what's happening here:
https://github.com/google/google-auth-library-nodejs#ways-to-authenticate

If you have any other questions - please let us know!
