### ISSUE TITLE
Socket Issue

### ISSUE THREAD

**Issue by yogeshtas** [google/google-api-nodejs-client#753]
s3BucketMgt=require("s3-nodejs-sample");
// exports.handler = function(event, context) {
var config=require("./config.js");
var bucketName="asset-mmp-excel1";
var fileName="sampleFile.txt";
var fileContents="This is demo created by Chandrakant Thakkar.";
console.log("In")
s3BucketMgt.createFile(bucketName,fileName,fileContents,config, function(data){
	console.log("In call")
 if(data.status==false){
  console.log("Error in File Creation:"+data.error);
 }else{
  console.log("File Created in Bucket.");
 }
});

// }

I am getting the issue
In
In call
Error in File Creation:NetworkingError: socket hang up

**Comment by yogeshtas** [comment]
please provide me solution

**Comment by yogeshtas** [comment]
is any one who can solve my problem....

**Comment by ace-n** [comment]
Hello @yogeshtas,

This is a repo for Google Cloud Platform samples, so we do not provide support for AWS (or Azure).

If you'd like to use the corresponding GCP product, take a look at [Google Cloud Storage](cloud.google.com/storage).

Alternatively, file an issue on the repo for the [s3-nodejs-sample](https://github.com/ChandrakantThakkarDigiCorp/s3-nodejs-sample) repo.
