### ISSUE TITLE
oAuth invalid_grant

### ISSUE THREAD

**Issue by ruid0** [google/google-api-nodejs-client#762]
Have an error while trying to authorize
```
Error: invalid_grant
    at Request._callback (/Users/noise/Sites/bandlab-desktop-client/app/node_modules/google-auth-library/lib/transporters.js:81:15)
    at Request.self.callback (/Users/noise/Sites/bandlab-desktop-client/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/noise/Sites/bandlab-desktop-client/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/noise/Sites/bandlab-desktop-client/app/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)

```

 ```
const rawCode = /(code=.+)/.exec(event.newURL) || null;
      const code = rawCode[0] ? rawCode[0].split('=')[1] : null;
      if (code) {
        oauth2Client.getToken(code, function(err, tokens) {
          if (err) {
            throw new Error(err);
          }

          oauth2Client.setCredentials(tokens);
        });
      }
```

When I'm trying to getToken I have this error.
But what is strange only for first time, if i'll try one more time with same google acc, everything is working. 

Thanks!

**Comment by james-robson** [comment]
Hi @ruid0 - did you ever resolve this issue? I'm facing exactly the same problem. I receive an `authorizationCode` but the first time I call `getToken` with said code I get an `invalid_grant` error.

Repeating the login process with the same user a second time returns a valid token and I can call `oauth2.userinfo.v2.me.get()` successfully. It is always the first attempt which returns an `invalid_grant` error. 

Any pointers would be much appreciated.

**Comment by james-robson** [comment]
Hi @ruid0 / @ace-n I think I've found the cause of this issue. Whilst debugging the issue I used the "Save as HAR" option in Chrome network inspector and diffed the initial failing `getToken` request against the second successful request. 

What I found is that for some reason the `authorizationCode` in the first request is URL encoded. The second character in the string is a forward slash and gets URL encoded to `%2F`. If I make a second request immediately after, the `authorizationCode` is _not_ URL encoded, hence it works fine.

Since I'm using Javascript I just called the [decodeURIComponent](https://www.w3schools.com/jsref/jsref_decodeuricomponent.asp) function on the `authorizationCode`. This seems to work as the function has no effect on an already decoded string.

Hope this helps someone!

**Comment by niftylettuce** [comment]
I believe this was introduced in a recent version of this package, as was #803.

**Comment by JustinBeckwith** [comment]
👋🏼 greetings folks!  We've made a ton of changes in the auth library over the last few months.  Can y'all confirm this is still an issue?

**Comment by JustinBeckwith** [comment]
If this is still an issue, please let us know!

**Comment by ajmwagar** [comment]
I am still getting this issue on specific Google Accounts

**Comment by ajmwagar** [comment]
Specifically an aliased domain on a personal g-suite account.

**Comment by JustinBeckwith** [comment]
@ajmwagar could you open a new bug and share:
- what version of the library you're using
- the code you're trying to use

Thanks!

**Comment by ajmwagar** [comment]
Will do, on mobile currently. I will when I get home.

**Comment by duesXMachine** [comment]
I ran `node watch.js` got the authorisation code and made a GET call `GET /oauthcallback?code={authorizationCode}` 
But still I am getting `Error: invalid_grant`.No matter how many times I do it.Same error.

**Comment by JustinBeckwith** [comment]
@dman777 this has nothing to do with TypeScript.  As I've mentioned above, please *please* open a new issue with:
- the version of nodejs you are using
- the code that reproduces the issue 

Thanks!
