### ISSUE TITLE
Google Drive API method files.get with alt: media parameter returning all special characters 

### ISSUE THREAD

**Issue by dallashuggins** [google/google-api-nodejs-client#766]
I am trying to get a specific image file's metadata so I can get the download url to input into a batch update request to create an image to input into a Google Slides presentation. I am using the files.get call which should return a lot of metadata. If I do the 'Try it Out' [here](https://developers.google.com/drive/v2/reference/files/get?) it returns the correct data, however when I input that same fileId into my code, it only returns the name, id, kind and mimeType. I suspected this was because I need to add alt: media, but when I do that I get a return with all special characters.

Here is my code snippet: 

```js
authClient.refreshAccessToken(function(err, tokens) {
  if (err) {
    console.log(err);
    return;
  }
  drive.files.get({
    fileId: fileId,
    auth: authClient, 
    alt: 'media'
  }, function(err, res) {
    if (err) {
      return console.log(err);
    }
    else {
      return console.log(res);
    }
  });
});
```

The return with **alt: 'media'** is a long list of special characters like this: `A�c|��*����u�f����J`. 

This is the return without **alt: 'media'**: 
```js
{ 
  kind: 'drive#file',
  id: 'Photo ID',
  name: 'Photo Name',
  mimeType: 'image/jpeg' 
}
```

**EDIT:** _The below question has been partially solved. see below comment._ 

Also, I am wondering what the image url in the request body of the createImage object for the batchUpdate method should be. [Here](https://developers.google.com/slides/reference/rest/v1/presentations/request#CreateImageRequest) it just says to use the image url and when I've tried adding the self link, web content link, download url, embed link, etc. and I keep getting this error: 

```js
{
  "error": {
    "code": 400,
    "message": "Invalid requests[0].createImage: There was a problem retrieving the specified image.",
    "status": "INVALID_ARGUMENT"
  }
}
```

Any advice would be greatly appreciated! 

Thanks!

**Comment by dallashuggins** [comment]
Regarding the second question about the image url, I confirmed the webContentLink from the metadata does give me a 200, **IF** the image is public to the web. I have seen multiple people online talk about adding an access token for this reason, but everyone is using OAuth and I do not have an access token for JWT being returned. Any ideas of how to use this functionality with JWT? 

Example of link: `https://drive.google.com/a/[subdomain]/uc?id=[image id]&export=download`

**Comment by ace-n** [comment]
cc @erickoledadevrel

**Comment by erickoledadevrel** [comment]
The Slides API `createImage` request only accepts an image URL, so you can't download the image using the Slides API and `alt=media` and pass it to the Slides API directly. As shown in [our samples](https://developers.google.com/slides/how-tos/add-image#example) the recommended approach is to get the URL from Drive, attach the OAuth token to the URL, and pass that to the Slides API. It sounds like you are doing the same approach. Even when using JWT-based OAuth flows, you still get an access token during the process.

**Comment by erickoledadevrel** [comment]
Update: Because Google Slides records the source URL for images, we no longer recommend using Drive API URLs with access tokens. We're working to add support to the Slides API to accept binary image content directly, but in the mean time we recommend uploading the image to public server, CDN, or Google Cloud Storage instead.

**Comment by dallashuggins** [comment]
Hey - I went another route when I was figuring this out, sorry I didn't close this. When I wasn't able to get the chart image address, I instead went the alternative route of using Google Sheets to create a new tab in a spreadsheet, add data and then create the chart to then send to the presentation.

**Comment by JustinBeckwith** [comment]
Thanks for the follow up :) . Great to hear that you're unblocked!

**Comment by lucidsushi** [comment]
> Update: Because Google Slides records the source URL for images, we no longer recommend using Drive API URLs with access tokens. We're working to add support to the Slides API to accept binary image content directly, but in the mean time we recommend uploading the image to public server, CDN, or Google Cloud Storage instead.

Would like to retrieve a secure url usable for Slides create image requests, this info is very concerning and not documented anywhere. Is it inevitable that drive access token urls are always publicly accessible? Aren't cloud storage bucket urls also public (and only expire after a while)

**Comment by erickoledadevrel** [comment]
Yes, there is a tension here since the URL needs to be accessible for the Slides API backend to access it, which either means it's publicly accessible for some period of time or the security token is captured in the URL and available in the presentation's metadata.
