### ISSUE TITLE
Sheets: Span multiple columns

### ISSUE THREAD

**Issue by RWOverdijk** [google/google-api-nodejs-client#768]
Hopefully a simple question... I want to have columns span across multiple columns in spreadsheets. I managed to write values to cells, which is cool, but I want them to take up more than one cell. Is this possible through the API?

**Comment by RWOverdijk** [comment]
https://developers.google.com/sheets/api/samples/formatting#merge_cells

**Comment by RWOverdijk** [comment]
wat?

**Comment by JustinBeckwith** [comment]
No worries, robot run amok 🤖  Feel free to ignore!
