### ISSUE TITLE
What's the expected behaviour when stopping a push notifications channel?

### ISSUE THREAD

**Issue by lewisblackwood** [google/google-api-nodejs-client#774]
We've built a handler for push notifications associated with Google Calendar.

Each channel for push notifications expires every 7 days. From the documentation [here][1]:

> Currently there is no automatic way to renew a notification channel.
> When a channel is close to its expiration, you must create a new one
> by calling the watch method. As always, you must use a unique value
> for the id property of the new channel. Note that there is likely to
> be an "overlap" period of time when the two notification channels for
> the same resource are active.

Ideally, I'd like to schedule a cron job to run every night which would:

 - stop an existing channel
 - immediately recreate the channel, with the same ID as before

Even if I were to create a new channel with a different ID, I'd still like some certainty that the previous channel has been stopped.

However, with the Node client it seems possible to make multiple successful requests to stop an existing channel, before receiving an error stating that the channel no longer exists:

    const options = {
      auth: OAuth2Client,
      calendarId: CALENDAR_ID,
      resource: {
        id: GOOGLE_ID,
        address: CALENDAR_ADDRESS
      }
    };
    
    const eventsWatch = Promise.promisify(calendar.events.watch)(options);
    
    eventsWatch
      .then(response => {
        console.log({ response });
      })
      .catch(err => {
        console.log({ err });
      });

This would successfully create the channel. If I then cancel the channel:

    const options = {
      auth: OAuth2Client,
      resource: {
        id: GOOGLE_ID,
        resourceId: RESOURCE_ID
      }
    };
    
    const eventsStop = Promise.promisify(calendar.channels.stop)(options);
    
    eventsStop
      .then(response => {
        console.log({ response });
      })
      .catch(err => {
        console.log({ err });
      });

The above would log `{ response: undefined }`, as the successful request does not return any response (see docs [here](https://developers.google.com/google-apps/calendar/v3/reference/channels/stop)).

However, I can then run the above a second time - and see `{ response: undefined }`. It's only by running the code for third time that I receive:

    { Error: Channel CHANNEL_ID not found for project PROJECT_ID }

**What is the expected behaviour here?**

Ideally, I'd like a function like the following to stop and restart a channel:

    async function refreshWatcher() {
      try {
        const stop = await Promise.promisify(calendar.channels.stop)(options);
        console.log({ stop });
    
        const start = await Promise.promisify(calendar.events.watch)(startOptions);
        console.log({ start });
      } catch (err) {
        console.log({ err });
      }
    }
    
    refreshWatcher();

However, this will throw an error on the above: 

```
{ stop: undefined }
{ err: { Error: Channel id CHANNEL_ID not unique } }
```

If I run the following:

```
async function refreshWatcher() {
  try {
    const stop = await Promise.promisify(calendar.channels.stop)(options);
    console.log({ stop });

    const stop2 = await Promise.promisify(calendar.channels.stop)(options);
    console.log({ stop2 });

    const start = await Promise.promisify(calendar.events.watch)(startOptions);
    console.log({ start });
  } catch (err) {
    console.log({ err });
  }
}
```
 
I'll log to the console:

```
{ stop: undefined }
{ stop2: undefined }
{ start: 
   { kind: 'api#channel',
     id: CHANNEL_ID,
     resourceId: RESOURCE_ID,
     resourceUri: RESOURCE_URI,
     expiration: '1500047025000' } }
```

Is this right? Why is it necessary to cancel the channel twice? Any suggestions would be much appreciated!

  [1]: https://developers.google.com/google-apps/calendar/v3/push

**Comment by ace-n** [comment]
cc @sqrrrl @erickoledadevrel

I'm not terribly familiar with this particular API, but does it help if you add a small delay (e.g. `await Promise.promisify(setTimeout)(1000)`) between `stop` and `start` calls? It's possible the API is taking some time to be consistent.

**Comment by sqrrrl** [comment]
I'd reverse the operations -- create the new channel first, then cancel the old one. This provides a more graceful cutover (no gap in the subscription) and can be done in a way where even if the old subscription isn't canceled you're not dealing with duplicate notifications and the old one can naturally expire. 

When you create the renewal, mark the new one as pending until you receive the sync message and continue to process messages on the old channel. When you get the sync message, mark the new as active and the old one as canceled. You can then go ahead and call stop on the old one or just let it expire naturally. Any messages that arrive with the old channel ID after the new one is activated can be discarded/ignored since you should also be getting duplicates on the new channel.

**Comment by lewisblackwood** [comment]
@ace-n thanks for the comment! I had tried a delay as you described, but it seems like a channel remains active until being stopped a second time.

@sqrrrl thanks for the detailed comment, it's really appreciated. I'll go with the approach you've suggested. I'd also missed that the optional `token` could be provided - that should be useful for reconciling the newly created channel.

Thanks to you both for the clarification 👍
