### ISSUE TITLE
README doesn’t describe how to detect when automatically refreshed access token should be stored

### ISSUE THREAD

**Issue by binki** [google/google-api-nodejs-client#783]
The README states:

> This client comes with an [OAuth2](https://developers.google.com/identity/protocols/OAuth2) client that allows you to retrieve an access token and refreshes the token and retry the request seamlessly if you also provide an`expiry_date` and the token is expired.

Then later there are examples of how to initially obtain the expiry date, access token, and refresh token. And [instructions to save these to the database](https://github.com/google/google-api-nodejs-client/tree/b4c694b8a96de90c4ea414c4df27ada449a698ab#retrieve-access-token).

However, it is my understanding that when the library automatically retries a request after the access token has expired and uses the refresh token to get a new access code, this new access code and expiry should be stored into the database. Shouldn’t the examples in the README describe how to subscribe to the “automatic refresh has happened” event (if there is one) so that future requests made by the application after it restarts (or by other processes sharing an access token through a database) can use the new access token instead of always needing to refresh on startup?

**Comment by suparnavg** [comment]
@binki did you manage to figure this out?

Also, I'm not sure if the docs still contain the process to save the tokens to a database.  Are there any other resources you could share that explain how to store / retrieve tokens to the database?

**Comment by courthead** [comment]
@suparnavg Storing the tokens in your database will differ depending on your database. However, they do talk about about to *retrieve* the initial tokens in the README in this section: https://github.com/google/google-api-nodejs-client#retrieve-access-token

Basically, when you call `oauth2Client.getToken` and pass in a valid authorization code, the callback function will be passed a `tokens` parameter that looks like this:

    {
      access_token: <string>,
      refresh_token: <string>,
      token_type: <string>, (in my case this was "Bearer")
      expiry_date: <integer> (represents Unix ms timestamp)
    }

You can store those in your database however you want.

**Comment by MarcL** [comment]
Thanks for the above comment @courthead (and great work with IndieHackers!)

I think the fact that the refreshed tokens are returned in `OAuth2Client.credentials` should be called out in the documentation as it's not clear. I've added that to my request flow and update the access token in my database if the `expiry_date` is different than the passed tokens. Thanks for pointing that out.

**Comment by JustinBeckwith** [comment]
This issue was moved to google/google-auth-library-nodejs#340
