### ISSUE TITLE
[Feature Request] Support Google Data Studio 

### ISSUE THREAD

**Issue by suchitpuri** [google/google-api-nodejs-client#786]
Hi Everyone, 

Do you guys have any plans to support Google Data Studio in the API ?

**Comment by JustinBeckwith** [comment]
There's currently no public HTTP API available sadly.  We can't do much here in the node.js client, so I'd suggest filing an issue in the Google Data Studio issue tracker:

https://issuetracker.google.com/issues/new?component=196095&template=0
