### ISSUE TITLE
generateAuthUrl state parameters issue

### ISSUE THREAD

**Issue by gustavomassa** [google/google-api-nodejs-client#794]
The function generateAuthUrl  is not accepting objects as state parameters, it only accepts strings/numbers. The doc example doesn't work:
```
var url = oauth2Client.generateAuthUrl({
  // 'online' (default) or 'offline' (gets refresh_token)
  access_type: 'offline',

  // If you only need one scope you can pass it as a string
  scope: scopes,

  // Optional property that passes state parameters to redirect URI
  // state: { foo: 'bar' } //does not work
     state: 'bar' //works
});
```
If you pass an object in the state, the callback will return just the code parameter. If you pass string/number, the callback will return the state and the code.

**Comment by paramaggarwal** [comment]
I am also seeing this behaviour - inconsistent with the docs.
