### ISSUE TITLE
API broken due to compilation issue

### ISSUE THREAD

**Issue by niftylettuce** [google/google-api-nodejs-client#803]
Since `import` is not built in, the `googleapi` package is currently broken.

You cannot `require('googleapis/lib/apirequest')` for instance as you could before (you'd have to do `.default` after.

Perhaps add something similar to <https://github.com/59naga/babel-plugin-add-module-exports> and publish new version?

**Comment by niftylettuce** [comment]
It appears v20 dropped support for this.  Can you add it back?  Node is not using `import` syntax yet.

**Comment by niftylettuce** [comment]
Also, it looks like this package does not use default exports, but this package does?

<https://github.com/google/google-auth-library-nodejs/commit/62e801c4b78594d7bb3f801a04e5adcc198df30e>

Very confusing to have two different styles by Google for very closely related API libraries.

**Comment by ofrobots** [comment]
I think this is due to how default exports work in TypeScript compiled code. A fix similar to https://github.com/google/google-auth-library-nodejs/commit/4f74dfafe86cdb2c5c36ffc29bdf0d1bafaff71b might be needed here.

**Comment by niftylettuce** [comment]
This is still an issue.  See <https://stackoverflow.com/a/40357573>.

Please fix this asap, thank you!

**Comment by ofrobots** [comment]
Fix being worked upon in #837.

**Comment by JustinBeckwith** [comment]
Greetings folks!  I believe we resolved this issue by completely getting rid of default exports in a recent release.  Please take a look, and open a new issue if you're still having problems!
