### ISSUE TITLE
OAUTH2

### ISSUE THREAD

**Issue by nagarajukalva** [google/google-api-nodejs-client#805]
Hi 

Am implementing the OAUTH2 with Spring in Angular2.

I was getting the Access token and refresh token which login into the application.

I implemented one timer to get update new access_token based on existing token which was also working fine.

The problem is with updated access_token while doing the HTTP service, getting the following exception

Failed to load resource: the server responded with a status of 403 (Forbidden)

Got struck up at this point.

Looking forward your responses.

Thanks
Naga

**Comment by bantini** [comment]
Can you share the code that you have used to implement this so far?

**Comment by bantini** [comment]
Thank you for filing this issue. However, we didn't see any follow up in over a week so we are closing it. Please feel free to re-open this issue with more information.
