### ISSUE TITLE
youtube.videos.insert Stuck Preparing upload.

### ISSUE THREAD

**Issue by ctaity** [google/google-api-nodejs-client#810]
My code, the upload is fine. If i do with fs.readFileSync('test.mp4') works ok. Can you helpme with the stream? Thanks.  The autorization is ok, i can do live streaming and other things with de account. 

let data = {
    part: 'id,snippet,status,contentDetails',
    uploadType:'resumable',
    notifySubscribers: false,
    resource: {
      snippet: {
        title: 'Capitulo Mp4',
        description: 'Client'
      },
      status: {
        privacyStatus: 'private'
      }
    },
    media: {
      body: fs.createReadStream('test.mp4') //fs.readFileSync('test.mp4') 
    }
  }

var req = youtube.videos.insert(data, (err, data) =>  {
  	console.log("Callback");
    if (err) console.error('Error:', err); 
    if (data) console.log(util.inspect(data, false, null));
    process.exit();
});

var id = setInterval( () => {
	var uploadedBytes = req.req.connection._bytesDispatched;
    console.log(uploadedBytes/1000000) 
}, 500);

The result is 

Error: { Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at TLSSocket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

**Comment by bantini** [comment]
@ctaity Does the link below solve your issue?

[https://github.com/google/google-api-nodejs-client/issues/712](https://github.com/google/google-api-nodejs-client/issues/712
)

**Comment by bantini** [comment]
Closing this issue now. But feel free to comment or reopen if it reappears.
