### ISSUE TITLE
JWT client callback function has no error and no tokens

### ISSUE THREAD

**Issue by 0xc00010ff** [google/google-api-nodejs-client#812]
The JWT authorization API callback does not return any tokens as suggested by the docs. Rather, it just updated the google.auth.JWT client object to have the access token _somewhere in there_.

My suggestion is either to send back a valid `tokens` parameter or remove it all together and publish the requirement to reach into the jwtClient and grab the bearer token. The `token` param in the docs and example is a big red herring. 

```javascript
var key = require('/path/to/key.json');
var jwtClient = new google.auth.JWT(
  key.client_email,
  null,
  key.private_key,
  ['https://www.googleapis.com/auth/plus.me', 'https://www.googleapis.com/auth/calendar'], // an array of auth scopes
  null
);

jwtClient.authorize(function (err, tokens) {

  console.log(err, tokens); // undefined, null
  console.log(jwtClient) // [object Object] with bearer token snarled in the object

  if (err) {
    console.log(err);
    return;
  }

  token = tokens[0]; // null!

  // Make a request to the Play Store to validate a receipt. Use the JWT token
  Request(`https://play.store.url/with/product/id?access_token=${token}`)
});
```

**Comment by bantini** [comment]
Moved it to the Node OAuth library.

**Comment by JustinBeckwith** [comment]
Greetings @0xc00010ff!  I am having a little trouble reproducing this bug.  What version of googleapis are you using?  The token that comes in the callback (for me) is an object, not an array.
