### ISSUE TITLE
falsely advertising node 0.10.x support

### ISSUE THREAD

**Issue by cyrfer** [google/google-api-nodejs-client#815]
package.json advertises support for Node v >= 0.10.

Unfortunately when I use Node 0.10.26, the chain of dependencies (hawk->boom) uses the `const` keyword and the code execution fails.

EDIT: I see a problem with your own code also, when I upgraded from package v16.x to v21.x,
```
<omitted>/node_modules/googleapis/lib/googleapis.js:14
const path = require("path");
^^^^^
```

What are the solutions to be able to use googleapis with Node 0.10.x ?

**Comment by bantini** [comment]
This library no longer supports node 0.10. Sorry for the confusion. I have updated package.json to reflect the changes.

We would also like to thank you for bringing it up.
