### ISSUE TITLE
NPM run clean does not work on non BSD based systems

### ISSUE THREAD

**Issue by isonet** [google/google-api-nodejs-client#830]
The NPM command clean:
`find . -name '*.js.map' -type f -delete && find -E . -regex '\\./(test|lib|apis|scripts)/.*.js$' -type f -delete`
does not work on non BSD systems due to the use of the -E argument.

The equivalent argument for GNU based systems would be -regextype posix-extended

Error log:

```
> find . -name '*.js.map' -type f -delete && find -E . -regex '\./(test|lib|apis|scripts)/.*.js$' -type f -delete

find: unknown predicate `-E'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! googleapis@22.3.0 clean: `find . -name '*.js.map' -type f -delete && find -E . -regex '\./(test|lib|apis|scripts)/.*.js$' -type f -delete`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the googleapis@22.3.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-10-21T22_03_34_211Z-debug.log
```

**Comment by bantini** [comment]
@isonet I am trying to replicate the issue. What is the OS where you faced this problem? Also, what is the Node and npm version that you are using?

**Comment by isonet** [comment]
I'm not at my PC right now, but node was version 6 LTS and NPM the latest version.
OS is kde-neon latest stable developer build.

This explains it pretty well I think: https://ubuntuforums.org/showthread.php?t=1603072

**Comment by isonet** [comment]
Node v6.11.4
NPM v5.5.1
