### ISSUE TITLE
getToken return error {code: 400}

### ISSUE THREAD

**Issue by NALWeb3** [google/google-api-nodejs-client#863]
getToken always return error json {code: 400} with no description and tokens always null. Please tell me what wrong with my config and why it happens.

```javascript
var config = require('../../../config');
var google = require('googleapis');
var OAuth2 = google.auth.OAuth2;

var CLIENT_ID = '[CLIENT_ID]';
var CLIENT_SECRET = '[CLIENT_SECRET]';
var REDIRECT_URL = 'http://localhost:3000/google-users/login';

function login(req, res, next) {

    var oauth2Client = new OAuth2(
        CLIENT_ID,
        CLIENT_SECRET,
        REDIRECT_URL
    );

    // request access token
    oauth2Client.getToken(req.body.code, function (err, tokens) {
        // set tokens to the client
        // TODO: tokens should be set by OAuth2 client.
        oauth2Client.setCredentials(tokens);
    });
}
```

Thanks!

**Comment by bantini** [comment]
@NALWeb3 Try using the template provided in this example:

https://developers.google.com/drive/v3/web/quickstart/nodejs

**Comment by bxboxer219** [comment]
@NALWeb3 I'm trying to fix a similar problem in my app.

I followed what @bantini said and added error messaging from that example:
```
        if(err) {
            console.log('Error while trying to retrieve access token', err);
            return;
        }
```

It led me to find that I'm getting an unauthorized_client error when trying to trade my authorization code for an access_token.

So far this thread has been pretty helpful:
https://stackoverflow.com/questions/13871982/unable-to-refresh-access-token-response-is-unauthorized-client

I'll post an update if I figure out more, hope this helps.

**Comment by JustinBeckwith** [comment]
Greetings!  We have a good end to end example of OAuth2 here:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/oauth2.js

Let us know if you're still running into any issues!

**Comment by srikanta72** [comment]
This [ttps://github.com/google/google-auth-library-nodejs/blob/master/examples/oauth2.js](https://github.com/google/google-auth-library-nodejs/blob/master/examples/oauth2.js) returns 404. I am still facing the same issue.
