### ISSUE TITLE
Enable `noImplicitAny` on the tsconfig

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-api-nodejs-client#880]
We currently have a ton of `any` types floating around after the TypeScript conversion.  We should get those cleaned up, and enable `noImplictAny` on the repo.

**Comment by iamclaytonray** [comment]
@JustinBeckwith - I can take care of this, along with #881 and #882 if it hasn't been already.

**Comment by JustinBeckwith** [comment]
That would be awesome!

**Comment by iamclaytonray** [comment]
Awesome, I'll start working on it in the next couple of days. Thanks 😄

**Comment by iamclaytonray** [comment]
Hey @JustinBeckwith 

Just wanted to let you know that I am working on this in my spare time. I kind of got slammed with work so unfortunately, I had to put this on the back-burner. Completely understand if someone else wants to take this, otherwise, I'll have a working PR eventually. Sorry 😞
