### ISSUE TITLE
How to get only pageviews number

### ISSUE THREAD

**Issue by Jurabekxd** [google/google-api-nodejs-client#890]
Hi,
I have a question whether I can get only the number of pageviews not actually a whole row like so:
Before was:
for example, if my request looks like this:
```javascript
    'auth': oauth2Client,
    'ids': 'View_ID Number',
    'start-date': 'yesterday',
    'end-date': 'yesterday',
    'metrics': 'ga:pageviews',
    'dimensions': 'ga:date',
```
```javascript
analytics.data.ga.get(gauth, function (err, gaData) {
    if (!err)
        console.log(gaData.rows);
    else
        console.log(err);
}) 
```
Im getting this
>  rows: [ [ '20171209', '79304' ] ] }

While i use request withouth 'dimensions'
Im getting this

> [['79304']]

But i Need only
> 79304

without the brackets
Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  If you're getting a double array back, you can get the number by doing this:

```js
const result = [['12345']];
const justTheNumber = Number(result[0][0]);
```

Hope this helps!
