### ISSUE TITLE
Incorrect documentation and/or implementation for `getApplicationDefault` for GAE

### ISSUE THREAD

**Issue by dschenkelman** [google/google-api-nodejs-client#909]
[This document](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-nodejs) appears to indicate that executing code like this:

```javascript
google.auth.getApplicationDefault(function(err, authClient){
    if (err) { return cb(err); }
    if (authClient.createScopedRequired && authClient.createScopedRequired()) {
      authClient = authClient.createScoped(['https://www.googleapis.com/auth/spreadsheets']);
    }

    sheets.spreadsheets.values.append({
```

Will work in Google App Engine. The same thing for this comment [here](https://github.com/google/google-api-nodejs-client/blob/548263fe8e64b9af27c9b21cc7a1179f8d0601dc/samples/defaultauth.js#L41):
> The createScopedRequired method returns true when running on GAE or a local developer.

The problem is that in [this file](https://github.com/google/google-auth-library-nodejs/blob/master/ts/lib/auth/googleauth.ts#L206) (at least until version 0.12.0) it:
1. Looks for the GOOGLE_APPLICATION_CREDENTIALS env var.
2. Checks for a conventional path
3. Defaults to the `ComputeClient`.

In GAE, the `ComputeClient` is used unless 1 or 2 are met. And the `ComputeClient` [always returns `false`](https://github.com/google/google-auth-library-nodejs/blob/master/ts/lib/auth/computeclient.ts#L59) for `createScopedRequired()`.

Even if you create credentials for the Compute Engine service account (instead of the App Engine one) this does not work because there is no way to associate scopes with the App Engine service.

I'm new to GCP, but the "full fix" seems to require an implementation that:
* Differentiates between GCE and GAE
* Uses the GAE service account default credentials
* Returns `true` for `createScopedRequired` and can actually obtain an access token for the provided scopes.

Let me know if I can provide more info/you have any questions.

Thanks!

**Comment by dschenkelman** [comment]
Did some more research.


I put together a small sample based on what the golang SDKs is doing:
- https://github.com/golang/appengine/blob/78199dcb0669fc381c22e919e1e97eba879e8f60/internal/remote_api/remote_api.proto
- https://github.com/golang/appengine/blob/78199dcb0669fc381c22e919e1e97eba879e8f60/internal/app_identity/app_identity_service.proto
```javascript
var express = require('express');
var request = require('request');

var app = express();
var RemoteApi = require('./messages/remote_api_pb');
var AppIdentitiyService = require('./messages/app_identity_service_pb');

const HOST = 'appengine.googleapis.internal';
const SERVICE = 'app_identity_service';
const METHOD = 'GetAccessToken';

function getApiUrl(){
    return `http://${HOST}:10001/rpc_http`;
}

app.post("/", function(req, res){
    var accessTokenRequest = new AppIdentitiyService.GetAccessTokenRequest();
    accessTokenRequest.setScopeList(['https://www.googleapis.com/auth/spreadsheets']);
    performRequest(req, SERVICE, METHOD, accessTokenRequest.serializeBinary(), 60, function(err, body){
        if (err) { return res.status(500).json(err); }
        return res.status(200).json(body);
    });
});

function performRequest(req, service, method, payload, timeout, done){
    var remoteReq = new RemoteApi.Request();
    remoteReq.setServiceName(service);
    remoteReq.setMethod(method);
    remoteReq.setRequest(payload);
    remoteReq.setRequestId(req.get('X-AppEngine-API-Ticket'));

    console.log('remoteReq', remoteReq);

    var body = remoteReq.serializeBinary();

    console.log('body', body.length, body);

    request.post({
        url: getApiUrl(),
        headers: {
            'X-Google-RPC-Service-Endpoint': 'app-engine-apis',
            'X-Google-RPC-Service-Method': '/VMRemoteAPI.CallRemoteAPI',
            'Content-Type': 'application/octet-stream',
            'X-Google-RPC-Service-Deadline': '' + timeout,
            'Content-Length': body.length
        },
        body: body,
        host: HOST
    }, function(err, response, body){
        console.log(err, response, body);
        done(err, response, body);
    });
}

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`App listening on port ${PORT}`);
  console.log('Press Ctrl+C to quit.');
});
```

The response I get is:
```json
{"statusCode":400,"body":"App Engine APIs over the Service Bridge are disabled.\nIf they are required, enable them by setting the following to your app.yaml:\n\nbeta_settings:\n  enable_app_engine_apis: true\n","headers":{"date":"Tue, 02 Jan 2018 02:41:18 GMT","content-length":"178","content-type":"text/plain; charset=utf-8","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"appengine.googleapis.internal:10001","port":"10001","hostname":"appengine.googleapis.internal","hash":null,"search":null,"query":null,"pathname":"/rpc_http","path":"/rpc_http","href":"http://appengine.googleapis.internal:10001/rpc_http"},"method":"POST","headers":{"X-Google-RPC-Service-Endpoint":"app-engine-apis","X-Google-RPC-Service-Method":"/VMRemoteAPI.CallRemoteAPI","Content-Type":"application/octet-stream","X-Google-RPC-Service-Deadline":"60","Content-Length":86}}}
```

Updating the **app.yaml** file with `enable_app_engine_apis` causes the deploy (`gcloud app deploy`) to fail:
```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Support for the custom runtimes based on compat images (enable_app_engine_apis: true) has been deprecated.  Please migrate to a new base image, or use a Google managed runtimes. To learn more, visit https://cloud.google.com/appengine/docs/flexible/python/migrating.
```

Apparentely, there is no way to get to  `appengine.googleapis.internal` when using `env:flex`.

**Comment by JustinBeckwith** [comment]
Greetings!  And apologies for taking a while to get back on this one.  As far as I can tell right now, this is all working as intended (though I agree it isn't ideal).  

As far as I know, there is no way to change the OAuth scopes provisioned against application default credentials.  The GCE Metadata server automatically assumes the adc account has the `cloud-platform` scope, which is generally enough for a number of other cloud services.  The scopes enabled for this account cannot be changed. 

On the App Engine APIs and Go SDK bit - this is a red herring.  The stuff in there applies to "Managed VMs", a sorta weird product that went Beta, and then was deprecated.  It only really works against a limited number of APIs that were very specific to App Engine.  

Your best bet right now is to create a service account and service account credential, upload those credentials as part of your app, and rely on the presence of the local GOOGLE_APPLICATION_CREDENTIALS file to provide access to the services you want (TL;DR: Use JWT).  

I apologize for not having a better answer, and hope this at least helps a little.

**Comment by dinvlad** [comment]
Does this restriction apply equally to GAE Standard and Flex?

**Comment by JustinBeckwith** [comment]
@dinvlad yup
