### ISSUE TITLE
Support for Cloud Endpoints service-to-service authentication

### ISSUE THREAD

**Issue by rochdev** [google/google-api-nodejs-client#915]
This is not supported according to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/endpoints/getting-started#sending-authenticated-requests

**Comment by rochdev** [comment]
See https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started/clients for python examples

**Comment by rochdev** [comment]
After investigating a bit more and trying to use Cloud Endpoints, it seems the most important missing parts are `google.auth.crypto` and `google.auth.jwt.encode`. This makes authenticating using a key file impossible.

See http://google-auth.readthedocs.io/en/latest/reference/google.auth.jwt.html

**Comment by JustinBeckwith** [comment]
This issue was moved to google/google-auth-library-nodejs#351
