### ISSUE TITLE
Release 25.0.0

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-api-nodejs-client#923]
With #891 landed, we should release a new major version of the npm module.  I drafted a release with breaking changes and release notes that is ready to go as well.

**Comment by iamclaytonray** [comment]
Will the fix for #503 be included in this release?

**Comment by asyrique** [comment]
Is there a specific reason a new version of this has not been released?

**Comment by JustinBeckwith** [comment]
It's out!  https://github.com/google/google-api-nodejs-client/releases/tag/v25.0.0
