### ISSUE TITLE
Error over incorrect Axios request configuration

### ISSUE THREAD

**Issue by MrSlide** [google/google-api-nodejs-client#936]
I'm using the Google APIs client 24.0.0 and the OAuth2Client from Google Auth library 1.0.0 to read a spreadsheet from Google Sheets, and it outputs a message to the console every time I make a request:

`'json' is not a valid configuration option. Please use 'data' instead. This library is using Axios for requests. Please see https://github.com/axios/axios to learn more about the valid request options.`

Basically when the Google APIs library makes a request to the OAuth2Client it includes `json: true` in the options, which is not a valid Axios option and fails the validation of the options passed to the DefaultTransporter.

I managed to trace the source of the issue back to the file `src/lib/apirequest.ts` and the following bit of code (taken from the non-typescript version):
```
options.json = resource ||
            ((options.method === 'GET' || options.method === 'DELETE') ? true : {});
```
The option to set the content type to JSON in Axios is `responseType` and it already has the default value of `json`, so this is not necessary.

A couple of lines below I also found this:
```
options.qs = params;
```
This options is not a valid Axios option either and the correct option is `params`, which is being deleted from the options object.

**Comment by bogdan-calapod** [comment]
I've also stumbled upon this while trying to make a Drive GET request with a Service account (JWT)

Any idea if we can override the options object that the library passes to axios ?

**Comment by MrSlide** [comment]
I don't think it's possible.
This is apparently happening because Google Auth library 1.0.0 had breaking changes, they changed from Request to Axios for dealing with requests and didn't transform the options object so that it was compatible.

Downgrading to the previous version of Google Auth library solved the problem.

**Comment by bogdan-calapod** [comment]
Do you have any idea on how to specify the request body in the Google Auth library's `request` function that the client provides? I've been using it to access the Spreadsheet and Google Drive Metadata apis and it's been working great.

What I'm stuck on now is updating permissions and can't for the life of me figure how to pass the body parameters - I keep getting 403 or a cryptic 'Not Found' error

**Comment by MrSlide** [comment]
I don't think you're meant to be able to pass anything like that. This looks like it should be pretty much a plug and play thing without much configuration. You should just just be able to get the right permissions at the point where you obtain an access token by setting the correct scopes.

**Comment by MrSlide** [comment]
I guess the library is simply feature complete and they are not adding anything new

**Comment by MrSlide** [comment]
Version 25 of the client fixed the issue
