### ISSUE TITLE
Example of API docs lists all events

### ISSUE THREAD

**Issue by Skuriles** [google/google-api-nodejs-client#946]
Hello all,

I've tried to implement the calendar API with a simple nodejs server.
I just copied the quickstart exmaple form here:
[Google Calendara Node Quickstart](https://developers.google.com/google-apps/calendar/quickstart/nodejs)

It all works fine, besides the issue, that I can't filter any events. Instead of receiving only requested events the API lists all events in calendar:

```
function listEvents(auth) {
  var calendar = google.calendar('v3');
  calendar.events.list({
    auth: auth,
    calendarId: 'primary',
    timeMin: (new Date()).toISOString(),
    maxResults: 10,
    singleEvents: true,
    orderBy: 'startTime'
  }, function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }
    var events = response.items;
    if (events.length == 0) {
      console.log('No upcoming events found.');
    } else {
      console.log('Upcoming 10 events:');
      for (var i = 0; i < events.length; i++) {
        var event = events[i];
        var start = event.start.dateTime || event.start.date;
        console.log('%s - %s', start, event.summary);
      }
    }
  });
}
```
AS response I get every single calendar entry (currently 63 items from 2014 till end of 2018). So either timeMin nor maxresults have any effect on the query...
I'm doing something wrong? I currently only tested it local but it should work in debug mode as well, or?

Environment: Windows 10 
Node: V8.9.2

Any tips? Or is this just a bug.
To check it again, I've set up a new nodejs project which only contains the quickstart example file. But same result

**Comment by bloodrizer** [comment]
Can confirm the same.

REQUEST { url: 'https://www.googleapis.com/calendar/v3/calendars/primary/events',
  method: 'GET',
  paramsSerializer: [Function],
  headers:
   { Authorization: XXXX
     'User-Agent': 'google-api-nodejs-client/0.12.0' },
  params:
   { timeMin: '2018-01-23T03:25:25.103Z',
     timeMax: '2018-04-01T07:00:00.000Z',
     maxResults: 10,
     singleEvents: true,
     orderBy: 'startTime' },
  uri: 'https://www.googleapis.com/calendar/v3/calendars/primary/events',
  callback: [Function] }

Lists all events. Something is wrong with API call signature.

**Comment by matthew-reilly** [comment]
Seeing the same!

**Comment by uskithub** [comment]
In apirequest.ts, it uses OAuth2Client of "google-auth-library".
OAuth2Client.request does not use the values of options.params, but use "qs".

So, changing options.params to options.qs, it will be work I think.

https://github.com/google/google-api-nodejs-client/blob/8669d9ae0f183fec5e08875957f5d881db9b5b30/src/lib/apirequest.ts#L196

**Comment by uskithub** [comment]
Use those versions and change a little something like below.

> npm install googleapis@25.0.0 --save
> npm install google-auth-library@1.0.0 --save

```
let google = require('googleapis');
```

```
let OAuth2 = google.auth.OAuth2;
let oauth2Client = new OAuth2(clientId, clientSecret, redirectUrl);
```

```
let events = response.data.items;
```

**Comment by spmihai** [comment]
I can confirm the problem from the Google Calendar Node Quickstart.
The fix mentioned by @uskithub works perfect so you should give it a try.

**Comment by Skuriles** [comment]
The fix mentioned by @uskithub works perfect!
But docs need an update!

**Comment by JustinBeckwith** [comment]
Yeah - for others that fall into this, the trick is to *not* install your own version of `google-auth-library`.  That quickstart had some really bad advice.  Just install `googleapis`, and it will bring it's own copy of `google-auth-library` along with it :)
