### ISSUE TITLE
Incompatibility with `google-auth-library`

### ISSUE THREAD

**Issue by artisonian** [google/google-api-nodejs-client#951]
As I mentioned on #644, it seems that `createAPIRequest` won't serialize query parameters properly when using `google-auth-library`. The option for `paramsSerializer` is ignored because `google-auth-library` delegates to [Request](https://www.npmjs.com/package/request) instead of [axios](https://www.npmjs.com/package/axios) (for making the request).

Is there any known workaround?

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Could you share an example of the code that's giving you trouble?  It would be *super* helpful.  Under the hood, we're just using the `qs` module, and passing the serialized result to axios:

```js
  // When forming the querystring, override the serializer so that array
  // values are serialized like this:
  // myParams: ['one', 'two'] ---> 'myParams=one&myParams=two'
  // This serializer also encodes spaces in the querystring as `%20`,
  // whereas the default serializer in axios encodes to a `+`.
  options.paramsSerializer = (params) => {
    return qs.stringify(params, {arrayFormat: 'repeat'});
  };
```

Thanks!

**Comment by artisonian** [comment]
Sure. I'm using a modified version of the [quickstart](https://developers.google.com/sheets/api/quickstart/nodejs). I've only changed the call from `sheet.spreadsheets.value.get` to `sheet.spreadsheets.value.batchGet`.

When stepping through the code, in the case of `get`, the following lines from `apirequest.ts` get executed:

```js
// Parse urls
  if (options.url) {
    options.url = parseString(options.url, params);
  }
```

This creates a URL containing the value range for that particular spreadsheet. But when using `batchGet`, the problem occurs later:

```js
// create request (using authClient or otherwise and return request obj)
  if (authClient) {
    authClient.request(options, callback);
  } else {
    (new DefaultTransporter()).request(options, callback);
  }
```

In this case, `authClient` is the client from [google-auth-library](https://github.com/google/google-auth-library-nodejs).

**Comment by artisonian** [comment]
Turns out that quickstart is outdated. It uses `google-auth-library@0.*`. Once I updated to the latest version (and made changes for its API), I got it to work.

**Comment by artisonian** [comment]
FYI, I left feedback on the documentation site to ask if someone could make an update to the code sample.

**Comment by JustinBeckwith** [comment]
Yikes!  Could you drop a link to the specific doc that was giving you trouble?  I'd be happy to update it.

**Comment by artisonian** [comment]
Sure. It's here:

https://developers.google.com/sheets/api/quickstart/nodejs
