### ISSUE TITLE
sheets.spreadsheets.values.append 24.0.0 OK // 25.0.0.0 KO [valueInputOption]

### ISSUE THREAD

**Issue by laurentdebricon** [google/google-api-nodejs-client#964]
```
sheets.spreadsheets.values.append({
    auth: auth,
    spreadsheetId: 'spreadshiiitID',
    range: 'id_clients!A1:B2',
    valueInputOption: "USER_ENTERED",
    resource: {
      values: [
        ["Void", "Canvas", "Website"],
        ["Paul", "Shan", "Human"]
      ]
    }
  }, function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }

    console.log(JSON.stringify(response, null, 2));
  });

```
Error: 'valueInputOption' is required but not specified

this code works if
npm install googleapis@24.0.0
but not with  npm install googleapis@25.0.0

What is the new code snippet for "valueInputOption" ? Maybe there is a regression.

Thanks!

**Comment by JustinBeckwith** [comment]
We shipped a pretty big update in 25, so it's entirely likely something regressed.  I can take a look at this today.

**Comment by pasevin** [comment]
Can confirm "valueInputOption" is not being parsed as param.

**Comment by howebenhowe** [comment]
Reconfirm.

**Comment by KamilHawk123** [comment]
that works thanks

**Comment by benperrier** [comment]
@KamilHawk123 did you find out how to fix this?
If yes, what was the solution?

**Comment by Anthalasath** [comment]
Hello. Same issue here, valueInputOption is still not being parsed on 26.0.1. 

Here's my code: 
`sheets.spreadsheets.values.update({
        valueInputOption: 'RAW',
        auth: auth,
        spreadsheetId: tokenSheets[sheet],
        range:`${ sheet }!A2:H`,
        resource: body
    }, (err, result) => {
            if (err) {
                console.log(err);
            } else {
                console.log(`${ result.updatedCells } updated.`)
            }
        }
    );`

**Comment by JustinBeckwith** [comment]
Greetings folks!  I am struggling to reproduce this one.  I went ahead and added a sample and a test over here, just to make sure I'm not crazy:
https://github.com/google/google-api-nodejs-client/pull/1067

Is there anything in that sample that I'm missing?

Sometimes things like this will pop up if you have an old version of `google-auth-library` installed.  Can you check your `package.json`, and verify you *DO NOT* have `google-auth-library` added there?

**Comment by fahidmohammad** [comment]
Dear All,
the issue **Error: 'valueInputOption' is required but not specified** is still exist in version ^27.0.0.

While executing the below code im still getting the error.

```
sheets.spreadsheets.values.update({
	auth: auth,
	spreadsheetId: '<id>',
	range: 'Sheet1!A1',
	valueInputOption: 'USER_ENTERED',
	insertDataOption: 'INSERT_ROWS',
}, function(err, response) {
	console.log('err', err);
	console.log(response);
	res.send('done!');
});
```

Any suggestion or workaround for the above issue would be highly appreciated.

**Comment by JustinBeckwith** [comment]
Can you share a full code samples?  How are you getting your 'auth' object?

**Comment by fahidmohammad** [comment]
```
var googleAuth = require('google-auth-library')
, googleAuth= new googleAuth()
, clientId = googleAppSheet.clientId
, clientSecret = googleAppSheet.clientSecret
, redirectUrl = config.get('baseurl') + '/google/sheet/create' 
, auth = new googleAuth.OAuth2(clientId, clientSecret, redirectUrl);

generateToken: function(callback) {
	auth .credentials = {
		access_token: googleAppSheet.accessToken,
		refresh_token: googleAppSheet.refreshToken
	};
	return callback(auth);
}

```

**Comment by sanmak** [comment]
Migrating to version 24.0.0 works.

**Comment by Klervix** [comment]
Hey,

3 versions later, is there a real solution coming for this issue? 

Thanks! (c:

**Comment by Perskep-tionist** [comment]
Still working on it
