### ISSUE TITLE
nextPageToken not found

### ISSUE THREAD

**Issue by Harrmalik** [google/google-api-nodejs-client#982]
Does this API not return nextPageToken when using the youtube API? 
Want to browse through a large playlist and can't get more than 50 tracks

Thanks!

**Comment by JustinBeckwith** [comment]
Yes it does :) You can see this in action here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/youtube/search.js

If you're having trouble getting this to work, please post a code snippet!

**Comment by bugs181** [comment]
Had a look at the code you referenced. Nowhere in the code do I see `nextPageToken` listed or how pagination works. Here's my snippet and it's only returning 50 results (the max).

Here's my snippet.

      const res = await youtube.playlists.list({
        part: 'snippet',
        maxResults: 50,
        mine: true,
      })

**Comment by jejesh26** [comment]
Hi, 
why are U using **this.**retrieve(res.data.nextPageToken) in your recursive function ?

**Comment by bugs181** [comment]
> Hi,
> why are U using **this.**retrieve(res.data.nextPageToken) in your recursive function ?

Semantics. It's personal preference when dealing with multiple classes. That way I ensure I'm speaking to the correct class. Let's say I have two classes with `retrieve` function along with an app scoped `retrieve` function. Now there are three functions, when I only want to recurse into the function that belongs to this class object.
