### ISSUE TITLE
Unable to set subject for automatically retrieved auth client

### ISSUE THREAD

**Issue by 3thanZ** [google/google-api-nodejs-client#985]
There is no way to set the subject (and therefore impersonate an admin user which is pretty necessary when making Admin SDK calls) when using an auth client that is automatically retrieved as outlined here: https://github.com/google/google-api-nodejs-client#choosing-the-correct-credential-type-automatically

Thanks!

**Comment by 3thanZ** [comment]
Should be resolved in https://github.com/google/google-api-nodejs-clien

**Comment by tshamz** [comment]
the answer to this is pertinent to me but the link above is broken

**Comment by JustinBeckwith** [comment]
👋 hi there!  You can just set the subject on the client if you need to:

```js
const {google} = require('googleapis');
const client = await google.auth.getClient();
if (client instanceof google.auth.JWT) {
  client.subject = 'foobar@google.com';
}
...
```

Hope this helps!

**Comment by 3thanZ** [comment]
Hi @JustinBeckwith 

Sorry my initial question was a bit vague. I was actually referring to Application Default Credentials (ADC). The sample code https://github.com/google/google-api-nodejs-client#service-to-service-authentication did not provide such examples. 

The example that you have provided indeed works for JWT tokens.
