### ISSUE TITLE
Destructuring assignment doesn't work properly in samples

### ISSUE THREAD

**Issue by maxint137** [google/google-api-nodejs-client#986]
I tried to use the samples, and for some reason it appears that the following destructuring assignment (in `/samples/urlshortener/urlshortener.js` for example) doesn't work as expected:

```js
const {google} = require('googleapis');
```

Specifically, after that line `google` is undefined. Replaced with a simple assignment this seems to work properly. Is there anything I'm missing?

**Comment by JustinBeckwith** [comment]
Greetings!  What version of nodejs are you using?

**Comment by maxint137** [comment]
I have upgraded to `9.5.0` - same results. But I'm afraid I'm doing something wrong - is that possible to use the examples with the version of `googleapis` which `npm` brings by default?

**Comment by JustinBeckwith** [comment]
That is most likely what's happening :) . In the root directory can you try running `npm link && npm link googleapis`, then running the examples?

I switched those over to make copypasta easier, but I can see how that's confusing :/

**Comment by maxint137** [comment]
Well, it's definitely working better - there is no problem with `require('googleapis')`, but the example doesn't really work. It opens `https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=524...`, where I can choose an account. Then `Please copy this code, switch to your application and paste it there` screen appears, but I don't really see how to use that code - the application doesn't expect me to type it in, as much as I can see...
In any case I think it's better to close this issue now - and create a new one, in case my problem is relevant, right?

**Comment by JustinBeckwith** [comment]
That sounds right :) . If this is still a problem...  please open a new issue with your code sample!
