### ISSUE TITLE
26.0.0 released but package.json version still at 25.0.0

### ISSUE THREAD

**Issue by firemuzzy** [google/google-api-nodejs-client#988]
@JustinBeckwith released 26.0.0 but `package.json` still has version 25.0.0 which I think is preventing the publishing to npmjs. NPMjs still has 25.0.0

If I missed something about the release process, disregard this, just wanted to point out the anomaly.

Thanks!

**Comment by ddgenome** [comment]
I've published v26.0.0 here https://atomist.jfrog.io/atomist/npm-dev/googleapis/-/googleapis-26.0.0.tgz until this gets sorted out.

**Comment by JustinBeckwith** [comment]
Greetings folks!  We just cut a release which should fix the issue.  Apologies for the mixup!
