### ISSUE TITLE
People API personFields

### ISSUE THREAD

**Issue by megapat** [google/google-api-nodejs-client#989]
Unable to find out which is the proper way to use People API. According to the docs the following code should works fine:

```js
var contact = google.people({ version: 'v1', auth: auth });
contact.people.get({
  resourceName: 'people/me',
  personFields: 'names'
}, (err, connections) => {
  if (err) {
    throw err;
  }
});
```

but the response is:
```
Error: personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get
```

**Comment by trekiteasy** [comment]
Same here. This is my code :
`var contacts = google.people('v1')
    var list = contacts.people.connections.list(
      {
        resourceName: 'people/me',
        auth: auth,
        personFields: 'names'
      }, 
function(err, response) {...})`
I get the following response 
`The API returned an error: Error: personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get.`

**Comment by JustinBeckwith** [comment]
Greetings!  I don't see any of these as options in this doc:
https://developers.google.com/+/web/api/rest/latest/people/get

Can you share the specific doc you're following?  Thanks!

**Comment by JustinBeckwith** [comment]
Greetings folks!  If someone can share the doc, I'd be happy to re-open this and take a look :)
