### ISSUE TITLE
Unable to upload more than 10MB

### ISSUE THREAD

**Issue by Lergin** [google/google-api-nodejs-client#991]
When using the example code for uploading videos to youtube using the api (https://developers.google.com/youtube/v3/docs/videos/insert) i'm getting the following error for all videos over 10MB:

```
The API returned an error:  Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (C:\Users\Malte\Googl…w-redirects\ind…:66)
    at PassThrough.ondata (_stream_readable.js:642)
    at emitOne (events.js:125)
    at PassThrough.emit (events.js:221)
    at addChunk (_stream_readable.js:265)
    at readableAddChunk (_stream_readable.js:252)
    at PassThrough.Readable.push (_stream_readable.js:209)
    at PassThrough.Transform.push (_stream_transform.js:146)
    at PassThrough.afterTransform (_stream_transform.js:87)
    at PassThrough._transform (_stream_passthrough.js:42)
```

~I was able to fix this by editing https://github.com/olalonde/follow-redirects/blob/master/index.js#L226 of the follow-redirects module to something bigger as this is stopping all bigger requestbodys and therefor stop the uploading of most videos.~

Edit: A better way to fix this is to install Version 1.2.6 of follow-redirect as this is the newest version without this new "feature".

See also this commit that implemented this restriction to follow-redirects https://github.com/olalonde/follow-redirects/commit/847a47fb00ea2dcb7a8886ca16d9d82dc6accb5d

**Comment by escobar5** [comment]
I'm having the same issue uploading a file to google drive, is there a way to override that setting from this library?

**Comment by Lergin** [comment]
Another way to prevent this issue from happening is to install Version 1.2.6 of follow-redirect as this is the newest version without this new "feature".

**Comment by escobar5** [comment]
@Lergin thanks, that worked

**Comment by simonplend** [comment]
I'm also seeing this issue.

**Comment by condorman** [comment]
I resolve with "maxContentLength"

`const youtube = google.youtube({ version: 'v3', auth: client, maxContentLength: 100 * 1024 * 1024})`

**Comment by simonplend** [comment]
Thank you @JustinBeckwith for fixing this by raising the default of `maxContentLength` in #1016 !

In the meantime for anyone else waiting for this fix to land in a release, the workaround that @condorman proposed above works a treat. Or if you'd prefer:

`google.options({ maxContentLength: (100 * 1024 * 1024) });`

**Comment by Revadike** [comment]
Perhaps this should be somewhere in the docs. Perhaps add `google.options({ maxContentLength: (100 * 1024 * 1024) });` to the Youtube video upload sample, as videos files tend to be quite big.

**Comment by JustinBeckwith** [comment]
We haven't shipped the code that's on master just yet.  This will be in the v37 release :)

**Comment by Revadike** [comment]
Yeah, so far it seems to be working! Looks like I'm currently uploading a 2.5h 9gb video via googleapis.

**Comment by hanselsen** [comment]
This is not working for google.drive. I tried:


```

const maxContentLength = maxBodyLength = 10000 * 1024 * 1024;

function uploadFile(file, folder) {
  authorize(auth => {
	  const drive = google.drive({version: 'v3', auth, maxContentLength, maxBodyLength});
	  const resource = {
		name: path.basename(file)
	  };
	  if(folder) {
		resource.parents = [folder];
	  }
	  const media = {
		body: fs.createReadStream(file)
	  };
	  drive.files.create({media, resource}, (err, res) => {
	    if (err) {
		return console.log('The API returned an error: ' + err);
	    } else {
		console.log('success!');
	    }
	  });
  });
}
```
