### ISSUE TITLE
Cant search threads with multiple query parameters

### ISSUE THREAD

**Issue by abhanshgiri21** [google/google-api-nodejs-client#993]
Hi, I am trying to search for all the threads related to a particular sender's email ( to and from ). And it is listed in Gmail API documentation that the optional query parameter follow the search parameters form gmail inbox search. So i read up on it and passed multiple query parameters for retrueving all the threads related to a particular mail id. If i use only "to:" field, i get the following response

> searching threads for : customerservice@kotisdesign.com
> serching messages with query : {to:customerservice@kotisdesign.com}
> { threads: 
>    [ { id: '16000c34d629d821',
>        snippet: 'Hey, It started working now. I guess the UPS didn&#39;t updated the package details that time. Thanks for all the help Brianna Vann. On Wed, Jan 17, 2018 at 12:45 AM, Customer Service &lt;',
>        historyId: '2148931' } ],
>   resultSizeEstimate: 1 }

and whenever i use only "from:" query

> searching threads for : customerservice@kotisdesign.com
> serching messages with query : {from:customerservice@kotisdesign.com}
> { threads: 
>    [ { id: '16000c34d629d821',
>        snippet: 'Perfect! I&#39;m happy its working for you. Have a wonderful day! —Brianna Vann | Customer Service | Kotis Design 888-GO-KOTIS On Tue, Jan 16, 2018 at 11:05 pm, &lt;abhanshgiri21@gmail.com&gt; abhansh',
>        historyId: '2148931' },
>      { id: '15f5e4796ed7548c',
>        snippet: 'We received your order - thanks! ORDER #2202873 Items may not ship immediately. See delivery details below. Shipping To: aditya giri Attn: student 134-c suryadev nagar behind hawa bunglow INDORE,',
>        historyId: '1822481' },
>      { id: '15f5e444566d5781',
>        snippet: 'We received your order - thanks! ORDER #2202850 Items may not ship immediately. See delivery details below. Shipping To: abhansh giri Attn: student 134-c suryadev nagar, behind hawa bunglow INDORE,',
>        historyId: '1822398' } ],
>   resultSizeEstimate: 3 }
> 

But when i use both to and from fields, i get the same response as when i use only from query

This is my function which retrieves thread ID's
```
function getThreadIds(clientEmails){
	var gmail = google.gmail('v1');
	var threadIds = [ ];
	clientEmails.forEach((email) => {
		console.log("searching threads for : " + email);
		var query = "{from:"+email + " to:" + email + "}";
		console.log("serching messages with query : " + query);
		gmail.users.threads.list({
			auth:oauth2Client,
			userId:'me'
		}, {
			qs: {
				q:query
			}
		}, function(err, results){
			if(err){
				console.log("The api returned an error while retrieving threads for emails : " + err);
				return;
			}
			console.log(results);
		})
	})
}

**Comment by JustinBeckwith** [comment]
Greetings!  The trick is in this doc:
https://developers.google.com/gmail/api/v1/reference/users/threads/list

> Supports the same query format as the Gmail search box.

That means you can use `OR` here!  Update your query to something like this:
```
from:somebody OR to:somebody
```

Hope this helps!
