### ISSUE TITLE
sheets quickstart.js needs updating to reflect the es6 'optimizations' 

### ISSUE THREAD

**Issue by smurftruesmart** [google/google-api-nodejs-client#999]
Hi,

quickstart.js ( taken from https://developers.google.com/sheets/api/quickstart/nodejs ) currently fails when trying to reference google.sheets('v4') due to changes in google-api-nodejs-client 26.0.0.

    var google = require('googleapis');

should be replaced with:

    const {google} = require('googleapis');

otherwise the following error occurs:

/var/nodejs/sheets/quickstart.js:105
  var sheets = google.sheets('v4');
                      ^

TypeError: google.sheets is not a function
    at listMajors (/var/nodejs/sheets/quickstart.js:105:23)
    at /var/nodejs/sheets/quickstart.js:78:7
    at /var/nodejs/sheets/node_modules/google-auth-library/lib/auth/oauth2client.js:95:13
    at Request._callback (/var/nodejs/sheets/node_modules/google-auth-library/lib/transporters.js:113:17)
    at Request.self.callback (/var/nodejs/sheets/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/var/nodejs/sheets/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/var/nodejs/sheets/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)

Hope this helps.

Thanks!

**Comment by cepm-nate** [comment]
Same thing for the google.calendar('v3') in the quickstart.

**Comment by JustinBeckwith** [comment]
Apologies for the issues folks.  We added a sample in #1022, and we're waiting on a docs change to roll out with the update.  For other Googlers, this is b/73865350.

**Comment by grant** [comment]
The quickstart on https://developers.google.com/sheets/api/quickstart/nodejs should now be runnable using `@25.*` (instructions are updated).
Updating to `@26`+ is WIP.

**Comment by JustinBeckwith** [comment]
👋 Hey @grant!  I wrote a sample for this in the repo here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/sheets/quickstart.js

I'm trying to move the samples on codesite over to GitHub so we can write tests against them, preventing this kind of thing from happening again :)  I also made a few suggestions over in b/73865350 that should be added as well. Thanks!

**Comment by grant** [comment]
👋 @JustinBeckwith, I appreciate this. See https://github.com/google/google-api-nodejs-client/pull/1022#issuecomment-370085691 and the internal bug for more details.

**Comment by JustinBeckwith** [comment]
Pretty sure this is fixed now :)  Please do let us know if you run into any other doc snags!
